### PR TITLE
Update Symbols-only fonts for #249 and #429

### PR DESCRIPTION
**Pull request by polyzen**
#### Description

Updated Symbols-only fonts for #249 and #429

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### Any background context you can provide?

https://github.com/ryanoasis/nerd-fonts/commit/b9c842d4d6e1fc9092f8d41445ddc26d7128ecb0#commitcomment-37240254

### CODE REVIEW

**Comment by polyzen** [comment]
Didn't test this properly. Seems I messed something up. 🤔

**Comment by polyzen** [comment]
Seems [this](https://github.com/ryanoasis/nerd-fonts/wiki/Release-Workflow#ad-hoc-updating-of-the-glyph-only-fonts) needs to be changed to use the new `Symbols Template {1000,2048} em.ttf` files.

**Comment by ryanoasis** [comment]
Thanks this is definitely an oversight on the last release. To be honest I'm not _sure_ why I had to use those template files but yeah there probably was _some_ reason to get the symbol only fonts to generate and turn out correctly. 

Did [that](https://github.com/ryanoasis/nerd-fonts/wiki/Release-Workflow#ad-hoc-updating-of-the-glyph-only-fonts) fix what you referred to as being messed up?

I haven't had a chance to pull down the MR yet...

**Comment by polyzen** [comment]
> Thanks this is definitely an oversight on the last release. To be honest I'm not _sure_ why I had to use those template files but yeah there probably was _some_ reason to get the symbol only fonts to generate and turn out correctly.
> 
> Did [that](https://github.com/ryanoasis/nerd-fonts/wiki/Release-Workflow#ad-hoc-updating-of-the-glyph-only-fonts) fix what you referred to as being messed up?

With the current commands listed there, the symbols were all lower (in the y axis) than they should be ┐('～`；)┌. They generated properly with:
```
./font-patcher -ext ttf -out ./src/glyphs/ --complete ./src/glyphs/Symbols\ Template\ 1000\ em.ttf
./font-patcher -ext ttf -out ./src/glyphs/ --complete ./src/glyphs/Symbols\ Template\ 2048\ em.ttf
```

> I haven't had a chance to pull down the MR yet...

**Comment by ryanoasis** [comment]
Ah okay cool, so good then for now? Let me know if you need anything! Thanks.

**Comment by polyzen** [comment]
Looks good to me, but you may want to change the commands in the Release Workflow doc.

**Comment by polyzen** [comment]
Just a heads up, for some reason the 1000 em font doesn't want to work for me today.

**Comment by polyzen** [comment]
No idea why it's working again, but it is.

**Comment by ryanoasis** [comment]
so to summarize:

### new/correct/working:

```
./font-patcher -ext ttf -out ./src/glyphs/ --complete ./src/glyphs/Symbols\ Template\ 1000\ em.ttf
./font-patcher -ext ttf -out ./src/glyphs/ --complete ./src/glyphs/Symbols\ Template\ 2048\ em.ttf
```

### old/incorrect:

```
./font-patcher -ext ttf -out ./src/glyphs/ --complete ./src/glyphs/NerdFontsSymbols\ 1000\ EM\ Nerd\ Font\ Complete\ Blank.sfd
./font-patcher -ext ttf -out ./src/glyphs/ --complete ./src/glyphs/NerdFontsSymbols\ 2048\ EM\ Nerd\ Font\ Complete\ Blank.sfd
```

I have updated the wiki as well: https://github.com/ryanoasis/nerd-fonts/wiki/Release-Workflow#ad-hoc-updating-of-the-glyph-only-fonts

Thanks!

**Comment by polyzen** [comment]
Added a commit that fixes this overlap issue in status bars:
https://bugs.archlinux.org/task/66212

**Comment by ryanoasis** [comment]
Cool, I think we could likely have this in for the next release/rebuild of all fonts if all looks good

**Pull request merged**
