### PR TITLE
Introduce a font name parser

### PR DESCRIPTION
**Pull request by Finii**
**[why]**
A lot of the fonts have incorrect naming after patching. A completely
different approach can help to come up with a consistent naming scheme.

**[how]**
See [README](https://github.com/ryanoasis/nerd-fonts/blob/feature/rewrite-setup_font_names/bin/scripts/name_parser/README.md)

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [x] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### Any background context you can provide?

In general (MS or Apple, is the same):
https://docs.microsoft.com/en-us/typography/opentype/spec/name#name-ids
https://www.fonttutorials.com/how-to-name-font-family/

About the length limits:
https://adobe-type-tools.github.io/font-tech-notes/pdfs/5088.FontNames.pdf
https://forum.glyphsapp.com/t/overly-strict-font-name-max-length-recommendation-in-naming-tutorial/10164
https://github.com/googlefonts/fontbakery/issues/1488
https://typedrawers.com/discussion/617/family-name/p2

#### Screenshots (if appropriate or helpful)

_Edit: Add all links in Background paragraph_

### CODE REVIEW

**Comment by Finii** [comment]
## Here an example.

This is how the fonts come out now:

```
 |PSname                                             | | Fullname                                           | | Family                         | | Subfamily                      | | Typogr. Family                 | | Typogr. Subfamily
 |-------------------------------------------------- |-| -------------------------------------------------- |-| ------------------------------ |-| ------------------------------ |-| ------------------------------ |-| ------------------------------
 |CaskaydiaCoveNerdFontComplete-BoldItalic           | | Caskaydia Cove Bold Italic Nerd Font Complete      | | CaskaydiaCove Nerd Font        | | Bold Italic                    | | CaskaydiaCove Nerd Font        | |
 |CaskaydiaCoveNerdFontComplete-Bold                 | | Caskaydia Cove Bold Nerd Font Complete             | | CaskaydiaCove Nerd Font        | | Bold                           | | CaskaydiaCove Nerd Font        | |
 |CaskaydiaCoveNerdFontComplete-ExtraLightItalic     | | Caskaydia Cove ExtraLight Italic Nerd Font Complet | | Cascadia Code ExtraLight       | | Italic                         | | CaskaydiaCove Nerd Font        | | ExtraLight Italic
 |CaskaydiaCoveNerdFontComplete-ExtraLight           | | Caskaydia Cove ExtraLight Nerd Font Complete       | | Cascadia Code ExtraLight       | | Regular                        | | CaskaydiaCove Nerd Font        | | ExtraLight
 |CaskaydiaCoveNerdFontComplete-LightItalic          | | Caskaydia Cove Light Italic Nerd Font Complete     | | Cascadia Code Light            | | Italic                         | | CaskaydiaCove Nerd Font        | | Light Italic
 |CaskaydiaCoveNerdFontComplete-Light                | | Caskaydia Cove Light Nerd Font Complete            | | Cascadia Code Light            | | Regular                        | | CaskaydiaCove Nerd Font        | | Light
 |CaskaydiaCoveNerdFontComplete-Italic               | | Caskaydia Cove Italic Nerd Font Complete           | | CaskaydiaCove Nerd Font        | | Italic                         | | CaskaydiaCove Nerd Font        | |
 |CaskaydiaCoveNerdFontComplete-Regular              | | Caskaydia Cove Regular Nerd Font Complete          | | CaskaydiaCove Nerd Font        | | Regular                        | | CaskaydiaCove Nerd Font        | |
 |CaskaydiaCoveNerdFontComplete-SemiBoldItalic       | | Caskaydia Cove SemiBold Italic Nerd Font Complete  | | Cascadia Code SemiBold         | | Italic                         | | CaskaydiaCove Nerd Font        | | SemiBold Italic
 |CaskaydiaCoveNerdFontComplete-SemiBold             | | Caskaydia Cove SemiBold Nerd Font Complete         | | Cascadia Code SemiBold         | | Regular                        | | CaskaydiaCove Nerd Font        | | SemiBold
 |CaskaydiaCoveNerdFontComplete-SemiLightItalic      | | Caskaydia Cove SemiLight Italic Nerd Font Complete | | Cascadia Code SemiLight        | | Italic                         | | CaskaydiaCove Nerd Font        | | SemiLight Italic
 |CaskaydiaCoveNerdFontComplete-SemiLight            | | Caskaydia Cove SemiLight Nerd Font Complete        | | Cascadia Code SemiLight        | | Regular                        | | CaskaydiaCove Nerd Font        | | SemiLight
```

Everything looks fine, but ... `Family` is unchanged for some/most fonts (because of a `fontforge` ~bug~ unexpected behavior). And because this font has a RFN, we _need_ to change the Family (this is where the problems start).

If we would **'write want we want'** we would end up with this:

```
 |PSname                                             | | Fullname                                           | | Family                         | | Subfamily                      | | Typogr. Family                 | | Typogr. Subfamily
 |-------------------------------------------------- |-| -------------------------------------------------- |-| ------------------------------ |-| ------------------------------ |-| ------------------------------ |-| ------------------------------
 |CaskaydiaCoveNerdFont-BoldItalic                   | | Caskaydia Cove Bold Italic Nerd Font               | | CaskaydiaCove Nerd Font        | | Bold Italic                    | | CaskaydiaCove Nerd Font        | |
 |CaskaydiaCoveNerdFont-Bold                         | | Caskaydia Cove Bold Nerd Font                      | | CaskaydiaCove Nerd Font        | | Bold                           | | CaskaydiaCove Nerd Font        | |
 |CaskaydiaCoveNerdFont-ExtraLightItalic             | | Caskaydia Cove ExtraLight Italic Nerd Font         | | CaskaydiaCove Nerd Font        | | ExtraLightItalic               | | CaskaydiaCove Nerd Font        | | ExtraLight Italic
 |CaskaydiaCoveNerdFont-ExtraLight                   | | Caskaydia Cove ExtraLight Nerd Font                | | CaskaydiaCove Nerd Font        | | ExtraLight                     | | CaskaydiaCove Nerd Font        | | ExtraLight
 |CaskaydiaCoveNerdFont-Italic                       | | Caskaydia Cove Italic Nerd Font                    | | CaskaydiaCove Nerd Font        | | Italic                         | | CaskaydiaCove Nerd Font        | |
 |CaskaydiaCoveNerdFont-LightItalic                  | | Caskaydia Cove Light Italic Nerd Font              | | CaskaydiaCove Nerd Font        | | LightItalic                    | | CaskaydiaCove Nerd Font        | | Light Italic
 |CaskaydiaCoveNerdFont-Light                        | | Caskaydia Cove Light Nerd Font                     | | CaskaydiaCove Nerd Font        | | Light                          | | CaskaydiaCove Nerd Font        | | Light
 |CaskaydiaCoveNerdFont-Regular                      | | Caskaydia Cove Regular Nerd Font                   | | CaskaydiaCove Nerd Font        | | Regular                        | | CaskaydiaCove Nerd Font        | |
 |CaskaydiaCoveNerdFont-SemiBoldItalic               | | Caskaydia Cove SemiBold Italic Nerd Font           | | CaskaydiaCove Nerd Font        | | SemiBoldItalic                 | | CaskaydiaCove Nerd Font        | | SemiBold Italic
 |CaskaydiaCoveNerdFont-SemiBold                     | | Caskaydia Cove SemiBold Nerd Font                  | | CaskaydiaCove Nerd Font        | | SemiBold                       | | CaskaydiaCove Nerd Font        | | SemiBold
 |CaskaydiaCoveNerdFont-SemiLightItalic              | | Caskaydia Cove SemiLight Italic Nerd Font          | | CaskaydiaCove Nerd Font        | | SemiLightItalic                | | CaskaydiaCove Nerd Font        | | SemiLight Italic
 |CaskaydiaCoveNerdFont-SemiLight                    | | Caskaydia Cove SemiLight Nerd Font                 | | CaskaydiaCove Nerd Font        | | SemiLight                      | | CaskaydiaCove Nerd Font        | | SemiLight
```

The names in `Family` use now our new name, **but** they do not contain the weight anymore (compare with the Cascadia Family names above), i.e. `SemiLight`. Instead the weight ended up in the `SubFamily`.

The Family/SubFamily grouping is for sets of four font, that have combinations of *Bold* and *Italic*. Not for weights.
We want two write the same stuff that belongs into the Typographic Family / Subfamily fields, that allow an indefinite number of fonts grouped... (BTW: Typographic Subfamily we do not try to change at all).

#### Obviously what we want is not correct.

This is not so easy to tackle with the current naming code; and the reason I started the complete thing from scratch.

A compromise is to **Really set SubFamily to what we want** #690.

With that it would look like this:
```
 |PSname                                             | | Fullname                                           | | Family                         | | Subfamily                      | | Typogr. Family                 | | Typogr. Subfamily
 |-------------------------------------------------- |-| -------------------------------------------------- |-| ------------------------------ |-| ------------------------------ |-| ------------------------------ |-| ------------------------------
 |CaskaydiaCoveNerdFont-BoldItalic                   | | Caskaydia Cove Bold Italic Nerd Font               | | CaskaydiaCove Nerd Font        | | Bold Italic                    | | CaskaydiaCove Nerd Font        | |
 |CaskaydiaCoveNerdFont-Bold                         | | Caskaydia Cove Bold Nerd Font                      | | CaskaydiaCove Nerd Font        | | Bold                           | | CaskaydiaCove Nerd Font        | |
 |CaskaydiaCoveNerdFont-ExtraLightItalic             | | Caskaydia Cove ExtraLight Italic Nerd Font         | | CaskaydiaCove Nerd Font        | | Italic                         | | CaskaydiaCove Nerd Font        | | ExtraLight Italic
 |CaskaydiaCoveNerdFont-ExtraLight                   | | Caskaydia Cove ExtraLight Nerd Font                | | CaskaydiaCove Nerd Font        | | Regular                        | | CaskaydiaCove Nerd Font        | | ExtraLight
 |CaskaydiaCoveNerdFont-Italic                       | | Caskaydia Cove Italic Nerd Font                    | | CaskaydiaCove Nerd Font        | | Italic                         | | CaskaydiaCove Nerd Font        | |
 |CaskaydiaCoveNerdFont-LightItalic                  | | Caskaydia Cove Light Italic Nerd Font              | | CaskaydiaCove Nerd Font        | | Italic                         | | CaskaydiaCove Nerd Font        | | Light Italic
 |CaskaydiaCoveNerdFont-Light                        | | Caskaydia Cove Light Nerd Font                     | | CaskaydiaCove Nerd Font        | | Regular                        | | CaskaydiaCove Nerd Font        | | Light
 |CaskaydiaCoveNerdFont-Regular                      | | Caskaydia Cove Regular Nerd Font                   | | CaskaydiaCove Nerd Font        | | Regular                        | | CaskaydiaCove Nerd Font        | |
 |CaskaydiaCoveNerdFont-SemiBoldItalic               | | Caskaydia Cove SemiBold Italic Nerd Font           | | CaskaydiaCove Nerd Font        | | Italic                         | | CaskaydiaCove Nerd Font        | | SemiBold Italic
 |CaskaydiaCoveNerdFont-SemiBold                     | | Caskaydia Cove SemiBold Nerd Font                  | | CaskaydiaCove Nerd Font        | | Regular                        | | CaskaydiaCove Nerd Font        | | SemiBold
 |CaskaydiaCoveNerdFont-SemiLightItalic              | | Caskaydia Cove SemiLight Italic Nerd Font          | | CaskaydiaCove Nerd Font        | | Italic                         | | CaskaydiaCove Nerd Font        | | SemiLight Italic
 |CaskaydiaCoveNerdFont-SemiLight                    | | Caskaydia Cove SemiLight Nerd Font                 | | CaskaydiaCove Nerd Font        | | Regular                        | | CaskaydiaCove Nerd Font        | | SemiLight
```
Now the Family is the same for all fonts, which is too many in the Family but anyhow. Because we do not touch the SubFamily it at least does make sense a bit - if only one weight is installed by the user. Which can be the case; is often the case? I don't know.

And there are other issues aplenty. One is this:
```
The PostScript font name "CaskaydiaCoveNerdFont-Bold Italic" is invalid.
It should be printable ASCII, must not contain (){}[]<>%/ or space and must be shorter than 63 characters
```

What `font-patcher` needs is some understanding how fonts are to be grouped.

This MR adds a class [`FontnameTools`](https://github.com/ryanoasis/nerd-fonts/blob/feature/rewrite-setup_font_names/bin/scripts/name_parser/FontnameTools.py), where the name is analyzed and classified into
* Name Base
* Name Suffix
* Weight
* Style
* Other naming parts
* Unclassified rest

Once you have this information it is easy to assemble all name fields in a consistent matter ([`FontnameParser`](https://github.com/ryanoasis/nerd-fonts/blob/feature/rewrite-setup_font_names/bin/scripts/name_parser/FontnameParser.py)).

I guess a lot of this is already in the [README](https://github.com/ryanoasis/nerd-fonts/blob/feature/rewrite-setup_font_names/bin/scripts/name_parser/README.md) file, but I wanted to add the images here.

**Comment by Finii** [comment]
Just stumbled over #107 with this cite:
> When using the windows-compatible named fonts on MacOS, I found that some font families where not being handled properly. Different weights of the same font would conflict with each other. This was caused by the font name being the identical across the font weights. I solved this by tweaking how the windows name is generated, and ensure it is unique for each font weight. IMHO, it would be better to have only one naming convention that works everywhere. This would eliminate half of the binary fonts and generation time.

Well, I guess this is a solution. Apart maybe for the limited Family name length on Windows. But then, maybe that is fixed in Windows now. I can run a check if the (supposed) length restriction is ever violated, and if not we can for sure drop the 'for Windows' prepatched fonts.

**Comment by Finii** [comment]
@xsrvmy: Now I understood the issue. We need to remove the WWS entries, so that the Typographic entries are used. They are set with the correct names already, and as they follow WWS no extra WWS entries are needed (and existing have to be removed).

I missed the step in parens, because no font `src/unpatched-fonts/` (except Iosevka) has WWS set.

Thanks for pointing that out.

I'm still looking for a nice way to modify `fsSelection`...

**Comment by Finii** [comment]
I have forgotten what I wanted to add to these comments before review. Probably everything has been said already, but unfortunately all over the place and not only here. Maybe it is sufficient anyhow.

Please let me know if you need more information and / or examples.

---

What can be done in CI is to run a `name_parser_test2` on any changed source-font, and it shall not find any new 'Issues'.
I would not run it on all fonts, because that takes ages.
If new fonts are added one needs to run the `test2` and replace its `known_issues` file (with `known_issues.new`, that will be created).

**Comment by Finii** [comment]
https://github.com/fontforge/fontforge/pull/4877

**Comment by Finii** [comment]
Pulled last two commits developed while working on #723 that would really belong here.

CodeClimate has some issue, but I can not see the job page... trying ...

The short names we generate for Windows are probably not needed, or only for very old stuff. The exact origin of that issue is hard to get, talks about Microsort Word 2011 for Mac that had it? Maybe we should try to run without the short names. I for my part usually use the 'normal' fonts with no issues on Windows 10.

See also
https://github.com/fontforge/fontforge/commit/dadd4e5bf8f5a1a02bf60ec4c1ed846942f3e7ad (authored 2006!)
https://typedrawers.com/discussion/617/family-name/p2
https://www.fonttutorials.com/how-to-name-font-family/

**Comment by Finii** [comment]
Note to self: Check regression #526

**Comment by Finii** [comment]
I guess this is finally superseeded by #723; as that contains THIS and some more.

**Comment by torarnv** [comment]
One thing I also noticed in the current state of the code (not applying this patch), is that:

- The family name is pulled out of the PS name, resulting in "Avenir Next" becoming "AvenirNext" in the patched font
- The family name and full name not agreeing on where to inject the "Nerd Font" part:
  - Family name: Menlo Nerd Font
  - Full name: Menlo Regular Nerd Font
    -  This should be "Menlo Nerd Font Regular" I think

**Comment by Finii** [comment]
> The family name is pulled out of the PS name, resulting in "Avenir Next" becoming "AvenirNext" in the patched font

I code in this MR keeps the blank, I believe.
Relevant code here https://github.com/ryanoasis/nerd-fonts/blob/0e252dda415ac481b908587cd52db717a086c6a3/bin/scripts/name_parser/FontnameTools.py#L21

> * The family name and full name not agreeing on where to inject the "Nerd Font" part:
>       
>   * Family name: Menlo Nerd Font
>   * Full name: Menlo Regular Nerd Font
>         
>     * This should be "Menlo Nerd Font Regular" I think

You are correct. It's fixed by this MR. This is the reason why the code must be 'smart' enough to differentiate between 'name parts' and 'style/weight' parts.

**Comment by Finii** [comment]
> >     * This should be "Menlo Nerd Font Regular" I think
> 
> You are correct.

The FamilyName should of course not contain `Regular`, probably you mean FontName. (very few fonts have that).

For that fonts it can be selected... see https://github.com/ryanoasis/nerd-fonts/blob/0e252dda415ac481b908587cd52db717a086c6a3/bin/scripts/name_parser/FontnameParser.py#L56

Here a list of the changes that this MR does (`+`: new, `-`: old, `>`: original) for all our prepatched fonts.
https://github.com/ryanoasis/nerd-fonts/blob/feature/cascadia-2111.01/bin/scripts/name_parser/name_parser_test2.known_issues

**Comment by Finii** [comment]
> The family name is pulled out of the PS name, resulting in "Avenir Next" becoming "AvenirNext" in the patched font

This 'camelcasing' (i.e. removing blank between name parts) is a Nerd Fonts quirk :grimacing:
Can be turned on or off ;-) with this MR:
https://github.com/ryanoasis/nerd-fonts/blob/0e252dda415ac481b908587cd52db717a086c6a3/bin/scripts/name_parser/FontnameParser.py#L94

**Comment by torarnv** [comment]
> The FamilyName should of course not contain `Regular`, probably you mean FontName. (very few fonts have that).

Right, in the above example the family name should be "Menlo Nerd Font", and the full name "Menlo Nerd Font Regular".

Which seems to be the pattern followed by this, which is great:

https://github.com/ryanoasis/nerd-fonts/blob/feature/cascadia-2111.01/bin/scripts/name_parser/name_parser_test2.known_issues

**Comment by Finii** [comment]
Just noticed that `Meslo` is missing from the `name_parser_test2.known_issues` 'database'??!
Which is strange, because `Meslo` is mentioned in a comment in `name_parser_test2`.
That's a bug. Need to investigate.

...

According to the README one has to call (from the `bin/scripts/name-parser/` directory)
`fontforge name_parser_test2 ../../../src/unpatched-fonts/**/*.[ot]tf 2>/dev/null`

And it finds the Meslo fonts, so why are they missing?
```
$ ll  ../../../src/unpatched-fonts/**/*.[ot]tf | grep Meslo
-rw-rw-r-- 1 fini fini  442516 Mär 11 10:46 ../../../src/unpatched-fonts/Meslo/L/Bold-Italic/Meslo LG L Bold Italic for Powerline.ttf
[...]
```

Puzzling

**Comment by Finii** [comment]
This has been pulled indirectly via #723

**Pull request closed without merging**
