### PR TITLE
Add box drawing glyphs

### PR DESCRIPTION
**Pull request by Finii**
#### Description

This is just a stub and the commits, more will follow

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What are the relevant tickets (if any)?

Fixes: #1108
Fixes: #1122
Fixes: #1128
Fixes: #589

### CODE REVIEW

**Comment by Finii** [comment]
Test case stuff, taken from Wikipedia:

```
┌─┬┐  ╔═╦╗  ╓─╥╖  ╒═╤╕
│ ││  ║ ║║  ║ ║║  │ ││
├─┼┤  ╠═╬╣  ╟─╫╢  ╞═╪╡
└─┴┘  ╚═╩╝  ╙─╨╜  ╘═╧╛
┌───────────────────┐
│  ╔═══╗ Some Text  │▒
│  ╚═╦═╝ in the box │▒
╞═╤══╩══╤═══════════╡▒
│ ├──┬──┤           │▒
│ └──┴──┘           │▒
└───────────────────┘▒   
 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒

```
_as image:_

image

**Comment by Finii** [comment]
This looks bad: 
image

**Comment by Finii** [comment]
Rendering in `Tilix` (left) and `kitty`

image

WAT, Tilix is rendering it as solid gray and not checkered black and white?

image

**Comment by Finii** [comment]
image
image
image

image

**Comment by Finii** [comment]
Font Book is content

Screenshot 2023-03-07 at 15 14 10

iTerm2:

Screenshot 2023-03-07 at 15 11 24

**Comment by Finii** [comment]
Another issue, as seen with iTerm2:

image

It's not high enough. It's not even v centered?

**Comment by Finii** [comment]
Examining 600 font files

| Name | # of box glyphs |
|---|---|
| 3270 | 80 |
| Agave | 74 |
| AnonymousPro | 40 |
| Arimo | 48 |
| AurulentSansMono | 0 |
| BitstreamVeraSansMono | 0 |
| CascadiaCode | 160 |
| CodeNewRoman | 48 |
| Cousine | 48 |
| DaddyTimeMono | 159 |
| DejaVuSansMono | 160 |
| DroidSansMono | 0 |
| FantasqueSansMono | 160 |
| FiraCode | 160 |
| FiraMono | 148 |
| Gohu | 0, 125, 160 |
| Go-Mono | 48 |
| Hack | 160 |
| Hasklig | 160 |
| HeavyData | 0 |
| Hermit | 17 |
| iA-Writer | 0 |
| IBMPlexMono | 0 |
| Inconsolata | 160 |
| InconsolataGo | 0 |
| InconsolataLGC | 160 |
| Iosevka | 160 |
| JetBrainsMono | 160 |
| Lekton | 0 |
| LiberationMono | 48 |
| Lilex | 0 |
| Meslo | 32, 160 |
| Monofur | 48 |
| Monoid | 0, 1 |
| Mononoki | 160 |
| MPlus | 129 |
| Noto | 0, 160 |
| OpenDyslexic | 0 |
| Overpass | 0, 128 |
| ProFont | 0, 48 |
| ProggyClean | 0 |
| RobotoMono | 0 |
| ShareTechMono | 0 |
| SourceCodePro | 160 |
| SpaceMono | 0 |
| Terminus | 150 |
| Tinos | 48 |
| Ubuntu | 0 |
| UbuntuMono | 44 |
| VictorMono | 160 |

**Comment by Finii** [comment]
Rebase on master (because version changed there), force push.

I believe this is good to go now. It seems to render fine in all terminals (that I checked).
Still a bit hard to decide to replace the box glyphs if the source has SOME included. But alas...
This has other fixes in the code that we definitively want. Maybe we roll back a bit later :grimacing:

**Comment by igniscyan** [comment]
> Rebase on master (because version changed there), force push.
> 
> 
> 
> I believe this is good to go now. It seems to render fine in all terminals (that I checked).
> 
> Still a bit hard to decide to replace the box glyphs if the source has SOME included. But alas...
> 
> This has other fixes in the code that we definitively want. Maybe we roll back a bit later :grimacing: 

This has been fun to follow! Thank you for all of the work on this, I love that these glyphs work out of the box now.

**Pull request merged**
