### PR TITLE
Add VictorMono

### PR DESCRIPTION
**Pull request by kule**
#### Description

Added the VictorMono font

#### Requirements / Checklist
 
- [ x ] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)

- [ x ] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ x ] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [ x ] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [ x ] Extended the README and documentation if necessary, e.g. You added a new font please update the table

### CODE REVIEW

**Comment by kule** [comment]
Not sure how to interpret that ci error? If there’s something I need to tweak let me know...

**Comment by ryanoasis** [comment]
Thanks @kule 

You can ignore the build error. That's from some shellcheck violations. To be fixed...

**Comment by mhartington** [comment]
Note that this has the same issue as listed here

https://github.com/ryanoasis/nerd-fonts/issues/254

Because Victor ships with ligatures already, the font needs to either have a config to disable the `fi`/`fl` ligatures. I've attempted this myself, but to no success.

**Comment by ryanoasis** [comment]
Thanks @mhartington 

There is another option that I had forgot about, that is using the `careful` flag. You would lose any glyphs that would stomp over but that would ensure ligatures don't get replaced.

Cross posting reply from #254:

> Sorry for the late reply, yeah I think the real solution will involve not clobbering the ligatures but that will involve moving some of the codepoints of some glyphs. That would probably result in a `3.0` release (breaking change).
> 
> There is another workaround worth mentioning (if one patches themselves). that is using the `--careful` flag. That will ensure existing glyphs don't get clobbered, for example:
> 
> left: original font
> center: straight up patch
> right: patch with the `--careful` flag
> VictorMono-Regular-patching-comparisons
> 
> Ref: [#57 (comment)](https://github.com/ryanoasis/nerd-fonts/issues/57#issuecomment-515654441)

**Comment by ryanoasis** [comment]
I think this looks good, at least good enough to be in `master`. There are issues such as the one mentioned that probably need to be reconciled before a release. That seems out of scope of this PR since other fonts with ligatures currently have the same issue :smile: 

Also looks like you @kule instructions perfectly so appreciate that

**Comment by ryanoasis** [comment]
fixing milestone, need to update changelog and release and all-contributors

**Pull request merged**
