### PR TITLE
Inconsolata go

### PR DESCRIPTION
**Pull request by sodiumjoe**
#### Description

Added the font [InconsolataGo](http://levien.com/type/myfonts/inconsolata.html) (an experimental, tentatively titled version of Inconsolata with straight quotes by the original author).

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts#faq)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [x] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### What does this Pull Request (PR) do?

Adds new font InconsolataGo.

### CODE REVIEW

**Comment by ryanoasis** [comment]
@sodiumjoe Hey thanks for contribution :smile: . I cannot promise when I will do the merge but you can be sure it will happen :wink:

**Comment by ryanoasis** [comment]
Ping. haven't forgotten about this. will definitely go in next release

**Comment by ryanoasis** [comment]
@sodiumjoe Sorry that I haven't gotten to this yet. I thank you for your patience _*and*_ your contribution. 

We are finally making some progress toward getting a [`dev`](https://github.com/ryanoasis/nerd-fonts/tree/dev) branch up with all the latest fixes, etc. Also I think we are going to _improve_ the process (and therefore time) to merge in **PRs**

**Comment by sodiumjoe** [comment]
what's the release schedule? wondering when I'll be able to `brew install` this.

**Comment by ryanoasis** [comment]
@sodiumjoe I was thinking about doing releases once a month:
- whatever is merged into master at that time would go in the release
- items that don't make it wouldn't hold up the entire release
- items that don't make it would get their chance in the next release

I am open to any suggestions or thoughts you may have on this or ways to improve

**Comment by sodiumjoe** [comment]
that seems fine to me!

**Pull request merged**
