### PR TITLE
Add Intel One Mono

### LINKED ISSUE #1238: Add Intel One Mono font
**Requirements**

- [x] I have searched the [issues](https://github.com/ryanoasis/nerd-fonts/issues) for my request and found nothing related and/or helpful
- [x] I have searched the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting) for help
- [c] I have searched the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki) for help

**Is your feature request related to a problem? Please describe.**

Intel released a new open source font, Intel One Mono: https://github.com/intel/intel-one-mono . This font has been designed with maximum legibility especially for low vision folks. I think it would make a great addition to Nerd Fonts.

**Describe the solution you'd like**

Distribute this font with necessary patches.

**Describe alternatives you've considered**

self patch as per wiki instructions.

**Additional context**

Intel typically make processors.

### PR DESCRIPTION
**Pull request by sorashi**
#### Description

Added and patched Intel One Mono

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What does this Pull Request (PR) do?

- add Intel One Mono unpatched font
- add license & readme
- rename the resulting font due to OTF license reserved font name requirement
  - had to edit `font-patcher`
  - I chose the name Intone Mono, but I'm open to suggestions
- patch the font
- update readme
- provide an update script for the font

#### What are the relevant tickets (if any)?

Closes #1238

### CODE REVIEW

**Comment by Finii** [comment]
Thanks for the PR!

The patched fonts are generated by the workflow and should not be included in the PR (but you do not need to remove them now).
I just looked superficially, but it seems the RFN clause is missing in the FontnameTools. `--makegroups 0` is of course not what we want for release fonts. But also no worrys.

My 'problem' with this font (and similar PRs) is mostly that it consists of a very large number of styles and weights. I am not sure the more exotic ones are of any particular interest. That would not matter if they are not in the repo, which is growing exponentially.

We need to somehow change the release mechanism, as detailed elsewhere. There are some constrains and problems that are not solved yet. One way could be to put the patched fonts in the release artifact but NOT in the repo. That means people need to download the release zip (or even better the xz) of a desired font and can not select just one font file. Do you think that is an acceptable course? Already existing fonts will of course stay in the repo, also patched, at least for the time being.

And generally, at the moment I mostly try to fix the last 1 or 2 remaining issues of `v3.0.1` to get `v3.0.2` out. Only if we got a stable `v3.0` out I will have time to add fonts or stuff for a `v3.1`.

**Comment by Finii** [comment]
> I chose the name Intone Mono, but I'm open to suggestions

I like that name :-D

**Comment by sorashi** [comment]
> it consists of a very large number of styles and weights

True, it would make sense to include just Regular, Bold, Italic and maybe Bold-Italic

> That means people need to download the release zip (or even better the xz) of a desired font and can not select just one font file. Do you think that is an acceptable course?

Absolutely, that seems very reasonable to me. Build artifacts should not be tracked in the repo of course, I just thought you did it like this, because other fonts are tracked. Now I see that they are committed by CI, if I understand correctly.

> And generally, at the moment I mostly try to fix the last 1 or 2 remaining issues of v3.0.1 to get v3.0.2 out. Only if we got a stable v3.0 out I will have time to add fonts or stuff for a v3.1.

Sure, I will try to keep an eye out and later rebase and update this PR if needed. Or just ping me. :)

Other than that, is there anything I should do at the moment, concerning this PR?

**Comment by Finii** [comment]
Everything find, no need to do anything.

> Now I see that they are committed by CI

Yes. In principle I would like to change (i.e. drop) that, but some repackagers fetch the fonts for historic reasons from there. We had some discussions on that. For sure we can drop that for newly added fonts ;-D

And in principle the whole setup should change, separating the patcher from the prepatched fonts, and we already have the organization set up ... but that is very slow going.

I hope to release 3.0.2 this weekend, then we could discuss release modus of operandi ;-) if you are interested. One problem is that I can discuss all the thing just we me, which makes no lively discussions :-D

**Comment by Finii** [comment]
> and later rebase

There is no need to rebase (and if, I will do it right before merging). As this mainly just adds new files there will be no conflicts and the few text lines that need to be added can be done manually. There are also changes in the `gh-pages` that need to be performed in sync anyhow, I believe. The font-example needs to be installed there. Or did I automatize that already? :thinking: Does not matter.

**Comment by yooakim** [comment]
Thanks for putting in work here @sorashi and @Finii - I look forward to be able to use the Intel One Mono with glyphs and more :-)

**Comment by pkking** [comment]
Any progress on this PR?

**Comment by Finii** [comment]
Thanks @pkking; in principle this is very easy to do, and iirc the `v3.1.0` is due already.

But I still have a problem with the release model. What we did in the past just does not scale - the in-repo patched fonts are a burden for everyone.

One possible solution is this:
* Put the unpatched fonts in the repo (as before)
* Create the release with the release archives per font (i.e. `IntoneMono.zip` and `IntoneMono.tar.zx`) on the release page
* in `patched/fonts/IntelMono/` we have no individual fonts but just a page that directs people to download the release archive (with link)
* That means no possibility to download individual patched fonts from the Github repo pages

Any opinions (from anyone) on this are welcome!

**Comment by Finii** [comment]
We need to adapt...
image

**Comment by Finii** [comment]
Rebase on master - force push.

Change some minor details. Most notably is the naming change; it will get the abbreviated `NF` instead of the more lengthy `Nerd Font` added to the name to comply with name length limits.

**Comment by Finii** [comment]
I guess we can pull this now and out-of-sync release the font to see and check if this is a good way for future releases.

Will manually simulate the release process.

**Comment by Finii** [comment]
Looks like it works...

image

**Comment by Finii** [comment]
Note to self: The download button could be split in halves, one zip and one xz :thinking:

**Comment by Finii** [comment]
Whoever is interested, Cask is in the pipeline: https://github.com/Homebrew/homebrew-cask-fonts/pull/7971

All other packagers probably are triggered only by a new Nerd Fonts release.
I 'smuggled' the font in with the old 3.0.2 release :grimacing: We have no good workflow for new fonts :thinking:

**Comment by pkking** [comment]
@Finii Thank you!

**Pull request merged**
