### PR TITLE
Update Iosevka font to 6.1.3

### PR DESCRIPTION
**Pull request by FollieHiyuki**
#### Description

This PR updates Iosevka (patched and unpatched) to version 6.1.3

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [x] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### What does this Pull Request (PR) do?

Updates Iosevka (patched and unpatched) to version 6.1.3

#### Any background context you can provide?

<details>
<summary>Output of `./gotta-patch-em-all-font-patcher\!.sh Iosevka` :</summary>

```
# [Nerd Fonts]  Parameter given, limiting search and patch to pattern 'Iosevka' given
# [Nerd Fonts]  Total source fonts found: 42
# [Nerd Fonts]  Complete Variation Count after max parallel process is  0

Done with Patch Sets, generating font...

Generated: IosevkaNerdFontComplete-Bold Italic
Removing ligatures from configfile `Subtables` section
Removing subtable: 'dlig' Discretionary Ligatures lookup 9 subtable
Removing subtable: 'dlig' Discretionary Ligatures lookup 11 subtable
Removing subtable: 'dlig' Discretionary Ligatures lookup 12 contextual 0
Removing subtable: 'dlig' Discretionary Ligatures lookup 12 contextual 1
Removing subtable: 'dlig' Discretionary Ligatures lookup 12 contextual 2
Removing subtable: 'dlig' Discretionary Ligatures lookup 18 subtable
Removing subtable: 'dlig' Discretionary Ligatures lookup 19 contextual 0
Removing subtable: 'dlig' Discretionary Ligatures lookup 24 contextual 0
Removing subtable: 'dlig' Discretionary Ligatures lookup 24 contextual 1
Removing subtable: 'dlig' Discretionary Ligatures lookup 24 contextual 2
Removing subtable: 'dlig' Discretionary Ligatures lookup 24 contextual 3
Removing subtable: 'dlig' Discretionary Ligatures lookup 24 contextual 4
Removing subtable: 'dlig' Discretionary Ligatures lookup 24 contextual 5
Removing subtable: 'dlig' Discretionary Ligatures lookup 26 subtable
Removing subtable: 'dlig' Discretionary Ligatures lookup 33 contextual 0
Removing subtable: 'dlig' Discretionary Ligatures lookup 33 contextual 1
Failed to remove subtable: 'dlig' Discretionary Ligatures lookup 33 contextual 1
...
```
</details>

<details>
<summary>Output of `./font-patcher src/unpatched-fonts/Iosevka/Regular/iosevka-regular.ttf -c` :</summary>

```
Internal Error: Your version of iconv does not support the "Mac Roman" encoding.
If this causes problems, reconfigure --without-iconv.
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
The truetype encoding specified by platform=1 specific=0 (which we map to Mac) is not supported by your version of iconv(3).
Adding 55 Glyphs from Seti-UI + Custom Set
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set
╢████████████████████████████████████████╟ 100%
Adding 3 Glyphs from Powerline Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 4 Glyphs from Powerline Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Powerline Extra Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 21 Glyphs from Powerline Extra Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Powerline Extra Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 8 Glyphs from Powerline Extra Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 11 Glyphs from Pomicons Set
╢████████████████████████████████████████╟ 100%
The following table(s) in the font have been ignored by FontForge
  Ignoring 'EPAR'
The glyph named asterisk is mapped to U+F069.
But its name indicates it should be mapped to U+002A.
The glyph named plus is mapped to U+F067.
But its name indicates it should be mapped to U+002B.
The glyph named question is mapped to U+F128.
But its name indicates it should be mapped to U+003F.
The glyph named minus is mapped to U+F068.
But its name indicates it should be mapped to U+2212.
The glyph named heart is mapped to U+F004.
But its name indicates it should be mapped to U+2665.
The glyph named home is mapped to U+F015.
But its name indicates it should be mapped to U+21B8.
The glyph named check is mapped to U+F046.
But its name indicates it should be mapped to U+2713.
The glyph named bell is mapped to U+F0A2.
But its name indicates it should be mapped to U+2407.
The glyph named lessequal is mapped to U+F500.
But its name indicates it should be mapped to U+2264.
The glyph named circle is mapped to U+F111.
But its name indicates it should be mapped to U+25CB.
The glyph named smile is mapped to U+F118.
But its name indicates it should be mapped to U+263A.
The glyph named frown is mapped to U+F119.
But its name indicates it should be mapped to U+2322.
The glyph named bullseye is mapped to U+F140.
But its name indicates it should be mapped to U+25CE.
The glyph named compass is mapped to U+F14E.
But its name indicates it should be mapped to U+263C.
The glyph named female is mapped to U+F182.
But its name indicates it should be mapped to U+2640.
The glyph named male is mapped to U+F183.
But its name indicates it should be mapped to U+2642.
The glyph named sun is mapped to U+F185.
But its name indicates it should be mapped to U+263C.
The glyph named venus is mapped to U+F221.
But its name indicates it should be mapped to U+2640.
Adding 679 Glyphs from Font Awesome Set
╢████████████████████████████████████████╟ 100%
The glyph named slash is mapped to U+E016.
But its name indicates it should be mapped to U+002F.
The glyph named pi is mapped to U+E02C.
But its name indicates it should be mapped to U+03C0.
The glyph named ring is mapped to U+E03D.
But its name indicates it should be mapped to U+02DA.
The glyph named infinity is mapped to U+E055.
But its name indicates it should be mapped to U+221E.
The glyph named equal is mapped to U+E079.
But its name indicates it should be mapped to U+003D.
Adding 170 Glyphs from Font Awesome Extension Set
╢████████████████████████████████████████╟ 100%
Adding 4 Glyphs from Power Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Power Symbols Set
╢████████████████████████████████████████╟ 100%
The PostScript font name "Material Design Icons" is invalid.
It should be printable ASCII,
must not contain (){}[]<>%/ or space
and must be shorter than 63 characters
The PostScript font name "Material Design Icons" is invalid.
It should be printable ASCII,
must not contain (){}[]<>%/ or space
and must be shorter than 63 characters
The glyph named alpha is mapped to U+F02B.
But its name indicates it should be mapped to U+03B1.
The glyph named at is mapped to U+F065.
But its name indicates it should be mapped to U+0040.
The glyph named backspace is mapped to U+F06E.
But its name indicates it should be mapped to U+2408.
The glyph named bell is mapped to U+F09A.
But its name indicates it should be mapped to U+2407.
The glyph named beta is mapped to U+F0A1.
But its name indicates it should be mapped to U+03B2.
The glyph named box is mapped to U+F0D4.
But its name indicates it should be mapped to U+25A1.
The glyph named check is mapped to U+F12C.
But its name indicates it should be mapped to U+2713.
The glyph named compass is mapped to U+F18B.
But its name indicates it should be mapped to U+263C.
The glyph named delete is mapped to U+F1C0.
But its name indicates it should be mapped to U+2421.
The glyph named delta is mapped to U+F1C2.
But its name indicates it should be mapped to U+03B4.
The glyph named diamond is mapped to U+F1C8.
But its name indicates it should be mapped to U+2666.
The glyph named earth is mapped to U+F1E7.
But its name indicates it should be mapped to U+2641.
The glyph named equal is mapped to U+F1FC.
But its name indicates it should be mapped to U+003D.
The glyph named heart is mapped to U+F2D1.
But its name indicates it should be mapped to U+2665.
The glyph named home is mapped to U+F2DC.
But its name indicates it should be mapped to U+21B8.
The glyph named image is mapped to U+F2E9.
But its name indicates it should be mapped to U+22B7.
The glyph named minus is mapped to U+F374.
But its name indicates it should be mapped to U+2212.
The glyph named omega is mapped to U+F3C9.
But its name indicates it should be mapped to U+03C9.
The glyph named percent is mapped to U+F3F0.
But its name indicates it should be mapped to U+0025.
The glyph named pi is mapped to U+F3FF.
But its name indicates it should be mapped to U+03C0.
The glyph named plus is mapped to U+F415.
But its name indicates it should be mapped to U+002B.
The glyph named sigma is mapped to U+F4A0.
But its name indicates it should be mapped to U+03C3.
The glyph named tie is mapped to U+F519.
But its name indicates it should be mapped to U+2040.
The glyph named triangle is mapped to U+F536.
But its name indicates it should be mapped to U+25B3.
The glyph named bullseye is mapped to U+F5DD.
But its name indicates it should be mapped to U+25CE.
The glyph named copyright is mapped to U+F5E6.
But its name indicates it should be mapped to U+00A9.
The glyph named lambda is mapped to U+F627.
But its name indicates it should be mapped to U+03BB.
The glyph named gradient is mapped to U+F69F.
But its name indicates it should be mapped to U+2207.
The glyph named asterisk is mapped to U+F6C3.
But its name indicates it should be mapped to U+002A.
The glyph named hook is mapped to U+F6E1.
But its name indicates it should be mapped to U+2440.
The glyph named infinity is mapped to U+F6E3.
But its name indicates it should be mapped to U+221E.
The glyph named prescription is mapped to U+F705.
But its name indicates it should be mapped to U+211E.
The glyph named tilde is mapped to U+F724.
But its name indicates it should be mapped to U+02DC.
The glyph named cancel is mapped to U+F739.
But its name indicates it should be mapped to U+2418.
The glyph named square is mapped to U+F763.
But its name indicates it should be mapped to U+25A1.
The glyph named circle is mapped to U+F764.
But its name indicates it should be mapped to U+25CB.
The glyph named null is mapped to U+F7E1.
But its name indicates it should be mapped to U+2400.
The glyph named pipe is mapped to U+F7E4.
But its name indicates it should be mapped to U+01C0.
The glyph named ring is mapped to U+F7EA.
But its name indicates it should be mapped to U+02DA.
Adding 2119 Glyphs from Material Set
╢████████████████████████████████████████╟ 100%
The following table(s) in the font have been ignored by FontForge
  Ignoring 'webf'
Adding 228 Glyphs from Weather Icons Set
╢████████████████████████████████████████╟ 100%
Adding 44 Glyphs from Font Logos (Font Linux) Set
╢████████████████████████████████████████╟ 100%
The glyph named question is mapped to U+F02C.
But its name indicates it should be mapped to U+003F.
The glyph named check is mapped to U+F03A.
But its name indicates it should be mapped to U+2713.
The glyph named plus is mapped to U+F05D.
But its name indicates it should be mapped to U+002B.
The glyph named x is mapped to U+F081.
But its name indicates it should be mapped to U+0078.
The glyph named home is mapped to U+F08D.
But its name indicates it should be mapped to U+21B8.
The glyph named ellipsis is mapped to U+F09A.
But its name indicates it should be mapped to U+2026.
The glyph named bell is mapped to U+F0DE.
But its name indicates it should be mapped to U+2407.
Adding 169 Glyphs from Octicons Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Octicons Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Octicons Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Octicons Set
╢████████████████████████████████████████╟ 100%

Done with Patch Sets, generating font...
Internal Error: Attempt to output 67254 into a 16-bit field. It will be truncated and the file may not be useful.

Generated: IosevkaNerdFontComplete-
```
</details>

#### What are the relevant tickets (if any)?

#455

### CODE REVIEW

**Comment by ttys3** [comment]
Iosevka version 7.2.3 released

https://github.com/be5invis/Iosevka/releases

**Comment by Icy-Thought** [comment]
Iosevka version 9.0.1 was released 11 days ago.
https://github.com/be5invis/Iosevka/releases/tag/v9.0.1

**Comment by ttys3** [comment]
Iosevka version 10.1.1 released 5 days ago

https://github.com/be5invis/Iosevka/releases/tag/v10.1.1

**Comment by FollieHiyuki** [comment]
Sorry for the late reply. My laptop doesn't have good specs so the build takes lots of time to finish.
It's better if someone else is willing to do the task, since I don't have the time to do so at the moment.

**Comment by ryanoasis** [comment]
should now be at `v11.0.1`

**Pull request merged**
