### PR TITLE
Update Symbols-2048-em Nerd Font Complete.ttf

### PR DESCRIPTION
**Pull request by fabrizioschiavi**
#### Description

I just moved all the icons from Unicode Ranges used for Arabic, standard ligatures and other important sets to empty and clean F0000-FFFFD private set where is possible add more than 65,000 glyphs!
The positioning consider the actual codepoint, (e.g. E001 was changed to F0001) to limited the renaming process with the changes of some prefixes

#### Requirements / Checklist

- [v] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [ ] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ ] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [ ] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [ ] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### What does this Pull Request (PR) do?

Avoid conflicts with the necessary glyphs of complete typefaces

#### How should this be manually tested?

Opening the changed ttf file

#### Any background context you can provide?

This is an important and necessary change because complete fonts like PragmataPro can be include all the glyphs possible without conflicts with very useful Nerd Font icons. Please don't ignore this request, it's important for all.

#### What are the relevant tickets (if any)?

https://github.com/ryanoasis/nerd-fonts/issues/346

#### Screenshots (if appropriate or helpful)

Actual:
before

After pull request:
after

### CODE REVIEW

**Comment by polyzen** [comment]
I believe you're meant to edit the [1000-em](https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/Symbols%20Template%201000%20em.ttf) and [2048-em](https://github.com/ryanoasis/nerd-fonts/blob/master/src/glyphs/Symbols%20Template%202048%20em.ttf) template files that are used in generating the complete symbols font files.

**Comment by fabrizioschiavi** [comment]
I changed just one file. I hope in the help of the community

**Comment by andrew-t-james-hm** [comment]
+1

**Comment by TheSecEng** [comment]
Any updates on this PR?

**Comment by andrew-hm** [comment]
I see no objections to this PR, hoping it can be merged by end of May 2021?? Just in time for summer!!

**Comment by Finii** [comment]
Well, I believe this MR has two points to be solved before it can be merged.

1. The technical ascpect is far from complete here. As @polyzen already pointed out it does not really help to patch some font file. What about all the patched fonts? Shall they not follow the new codepoints? This also means changes in the `font-patcher`.

2. With this all powerline setups will break. People need to update their prompts; programs that show icons need to be recompiled, powerline templates have to be updated, ... etc pp. The list is endless.

Because of 2 I believe the MR in its deceivingly simple logic (move `uE000` to `uF0000`) will not come. I personally would not want that. Albeit there is a problem with some (only a few) symbols we add that are outside the _private_ areas. Probably they and only they will be shifted ... somewhen.

See Issue #365

**Comment by wismill** [comment]
As a first step, could these symbols be duplicated in Arabic range _and_ PUA? Then mark the Arabic range as deprecated in order to give time to the tools to migrate (one year?). Once done, we could just free the legacy Arabic range.

**Comment by Finii** [comment]
Note possible interference with
* #801

**Comment by Finii** [comment]
This is superseeded by
* #773

Which will solve the PUA problems that we discussed in a lot of threads all over, in a different way than the one suggested with the PR (i.e. `Plan 5`).

**Comment by Finii** [comment]
Thank you @fabrizioschiavi for the PR, as it was part of the solution finding process! :+1:

**Pull request closed without merging**
