### PR TITLE
sh icon names, close #145

### LINKED ISSUE #145: Shell variables with established names for icons
I've gathered established names for all icons from many places and created https://github.com/powerman/nerd-fonts-sh to make it easier to use icons in shell scripts. In case there are several established names - I've provided aliases.

It may make sense to merge these files into your repo - this should make it easier to keep them in sync with font changes. If you'll do this - I'll close my repo. If you don't wanna merge them - you may like to add link to my repo.

I was unable to find established names for some icons (16 for Powerline Extra Symbols, 5 for Custom and 8 for Devicons), I suppose it's mostly for icons you've added on your own. So, if you know names for them - please send me PR. :)

### PR DESCRIPTION
**Pull request by powerman**
#### Description

I've moved everything from https://github.com/powerman/nerd-fonts-sh.
Also I've added i_all.sh helper to load all available icon names (tested with bash and zsh).

#### What does this Pull Request (PR) do?

Adds shell helper scripts to access icons by their names from shell.

#### How should this be manually tested?

Following example in README.

### CODE REVIEW

**Comment by ryanoasis** [comment]
Thanks for this again. Hopefully this weekend but we'll see

**Comment by ryanoasis** [comment]
@powerman This looks good to me at a glance. Question: How did you build the glyph variables listed: `$i_*` ? Looks like it was by hand or did you have some helper script?

My only worry going forward is keeping the lists up to date :smile: in case we upgrade any of the glyph sets and get new glyphs or add more glyph sets.

Thanks

**Comment by powerman** [comment]
> How did you build the glyph variables listed: $i_* ? Looks like it was by hand or did you have some helper script?

I've copied lists of icon names from official websites/doc and used manual Vim-kung-fu to convert them. I don't think this can be automated, at least not for all of the lists.

> My only worry going forward is keeping the lists up to date 😄 in case we upgrade any of the glyph sets and get new glyphs or add more glyph sets.

Yep. But that's one of main reasons to add these lists into this repo - at least you know when and which icons you've added.

**Comment by ryanoasis** [comment]
@powerman Makes sense!

> Vim-kung-fu to convert them

Wow that's impressive,thanks for this :smile:

**Comment by ryanoasis** [comment]
Wow your script(s) already proved their worth!

I made a script that used them that eventually helped me make this: 

http://nerdfonts.com/#cheat-sheet

new website theme

**Pull request merged**
