### PR TITLE
Fira Code

### PR DESCRIPTION
**Pull request by jrolfs**
Add patched version of Fira Code as metioned in #59

### CODE REVIEW

**Comment by jrolfs** [comment]
Looks like I got the directory structure all wrong, I'll fix it as soon as a I have a chance.

**Comment by ryanoasis** [comment]
@jrolfs Yep I saw this last night. Awesome and thank you :+1: 

I was waiting for more PRs regarding fonts :stuck_out_tongue_closed_eyes: 

So I am glad the patcher seems to be working well for other people not just me :smile: 

I will add this to the next release.

**Comment by ryanoasis** [comment]
Oh one more thing I will merge this in but I might have to rebuild if I also add #48 and I will update the readme accordingly :smile:

**Comment by jrolfs** [comment]
I can also handle the rebuild after #48 goes in, just let me know.

**Comment by ryanoasis** [comment]
Great thanks. I will let you know :+1:

**Pull request merged**
