### PR TITLE
Material Icons: Ensure icons in the private use area (fixes #365)

### LINKED ISSUE #365: [Suggestion] Fix invalid code points for some glyphs
## Summary

The current builds overwrites some code points that Unicode Consorthium prohibits to use for custom glyphs. I want to change this by fixing font_patcher.

## Problem Detail

Unicode defines [Private Use Areas][pua] and the consorthium itself decide not to add characters on these areas. So we can add glyphs as we like.

[pua]: https://en.wikipedia.org/wiki/Private_Use_Areas

The areas has these code points: U+E000..U+F8FF, U+F0000..U+FFFFD, U+100000..U+10FFFD.

But the Nerd Fonts is overwriting more code points than them. The font_patcher writes glyphs as below.

* source: the ones from source font files.
* current: the ones font_patcher writes into.

| Font Name               |   source  |    current    |   plan 1  |          plan 2         |
|-------------------------|:---------:|:-------------:|:---------:|:-----------------------:|
| Seti-UI + Custom        | E4FA-E52E |   E5FA-E62E   |     ←     |            ←            |
| Devicons                | E600-E6C5 |   E700-E7C5   | E630-E6F6 | E700-E7C5 (not changed) |
| Powerline Symbols       | E0A0-E0B3 |       ←       |     ←     |            ←            |
| Powerline Extra Symbols | E0A3-E0D4 |       ←       |     ←     |            ←            |
| Pomicons                | E000-E00A |       ←       |     ←     |            ←            |
| Font Awesome            | F000-F2E0 |       ←       |     ←     |            ←            |
| Font Awesome Extension  | E000-E0A9 |   E200-E2A9   |     ←     |            ←            |
| Power Symbols           | 23FB-2B58 |       ←       |     ←     |            ←            |
| Material                | F001-F847 | **F500-FD46** | E700-EF47 |   F500-F8FF,E800-EC47   |
| Weather Icons           | F000-F0EB |   E300-E3EB   |     ←     |            ←            |
| Font Logos (Font Linux) | F100-F11C |   F300-F31C   |     ←     |            ←            |
| Octicons                | F000-F105 |   F400-F505   |     ←     |            ←            |
| Octicons                | 2665-2665 |       ←       |     ←     |            ←            |
| Octicons                | 26A1-26A1 |       ←       |     ←     |            ←            |
| Octicons                | F27C-F27C |   F4A9-F4A9   |     ←     |            ←            |

It is the problem that font_patcher writes glyphs from Material into the range: **U+F500 - U+FD46**. This range overlaps areas that should not use for such purpose.

| area           | name                                                                                         |
|----------------|----------------------------------------------------------------------------------------------|
| U+F900..U+FAFF | [CJK Compatibility Ideographs](https://en.wikipedia.org/wiki/CJK_Compatibility_Ideographs)   |
| U+FB00..U+FB4F | [Alphabetic Presentation Forms](https://en.wikipedia.org/wiki/Alphabetic_Presentation_Forms) |
| U+FB50..U+FDFF | [Arabic Presentation Forms-A](https://en.wikipedia.org/wiki/Arabic_Presentation_Forms-A)     |

## Suggestion

So I suggest two plans to solve this.

### plan 1

1. Move Devicons just after Seti-UI + Custom.
2. Move Material to U+E700..U+EF47.

* Pros - Material will be still in a cluster.
* Cons - Two glyph sets will be moved.

### plan 2

1. Move and separate Material into U+F500..U+F8FF, U+E800-U+EC47.

* Pros - Only one set will be moved.
* Pros - The former part of Material still has the same code points.
* Cons - Material will be separated into two clusters.

----

I prefer _plan 2_ because it has less impact on the current builds. How do you think?

### PR DESCRIPTION
**Pull request by earboxer**
#### Description

This is following @delphinus "Plan 2" in #365 

#### Requirements / Checklist

- [X] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [X] Verified the license of any newly added font, glyph, or glyph set

#### How should this be manually tested?

Build the font and notice that:
- [X] nf-mdi-access-point is still F501  
- [X] E802 is a pushpin (which was previously F902)

#### Any background context you can provide?

It should be noticed that the material icons we are using are an older version of https://github.com/Templarian/MaterialDesign (it now has 6675 icons).

Google also has a newer version at https://github.com/google/material-design-icons (They have 2142 code points in their Regular font (no variants), which includes some codepoints with semantic meaning but identical appearance (our nf-mdi-sim_alert looks the same as their sim_card_alert **and** sd_card_alert))

both of these have added several new icons, but they've also removed icons such as nf-mdi-pinterest and nf-mdi-pinterest_box (which notably are redundant with the fontawesome icons nf-fa-pinterest_p and nf-fa-pinterest_square).

While the merge request is moving the code points, you could view this merge request as doing two things:

1. Removing bugged icons
2. Adding new icons (and assigning them to new codepoints).

#### What are the relevant tickets (if any)?

Fixes https://github.com/ryanoasis/nerd-fonts/issues/365

### CODE REVIEW

**Comment by Finii** [comment]
This just is the technical aspect, all the needed documentation files are missing in the PR.
If this would be pulled someone else would need to fix the documentation afterwards?
It should all be in ONE commit.

**Comment by Finii** [comment]
This MR does not implement _Plan Plus_ as per https://github.com/ryanoasis/nerd-fonts/issues/365#issuecomment-1022906071.
Which I personally find unfortunate, but nothing has been discussed yet.

But I like this MR, as it finally tries to get some momentum going in this issue :-)

One question for @earboxer: You say there are new/updated Material icons available. Did you by chance check if they move codepoints? Font Logos does it :-( (https://github.com/lukas-w/font-logos/issues/72).

**Comment by earboxer** [comment]
@Finii Yeah, they (Templarian) moved the codepoints to starting at 0f0001.

It looks like the layout is roughly the same, but many breaking changes (replaced icons). e.g. 0f002e is now a pair of rollerblades instead of nf-mdi-amazon_clouddrive (which was f02e in the older source).

But then when we get to the bottom of the code page, nf-mdi-home_heart is at 0F0827, where it was previously at F826.

Scrolling back through the icons, it seems the 'off-by-one' discrepancy between the old and new sheets starts at F675 (which is now starting at 0F0676), nf-mdi-credit_card_plus.

(This is comparing our installed file against v6.5.95, downloaded from their website)

**Comment by Finii** [comment]
> What all needs to be updated?

I thought about the documentation, but as I try to link here, that is in another repo / wiki...
I'll strike the comment.

**Pull request closed without merging**
