### PR TITLE
Fixed European Portuguese and Spanish translations errors

### PR DESCRIPTION
**Pull request by gusbemacbe**
#### Description

Fixing the European Portuguese and Spanish translations errors.

#### Requirements / Checklist

- [X] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [X] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [X] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [X] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [X] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### What does this Pull Request (PR) do?

Fixing the European Portuguese and Spanish errors.

## European Portuguese

- Fixed many European Portuguese translation errors;
- Fixed grammar errors;
- Fixed orthography errors;
- Purged the Brazilian words, replacing with pure European Portuguese words;
- Fixed wrong references (links) that @LiTO773 forgot of fixing.

Renamed the file, using the correct LCID code. 

## Spanish

- Fixed `quiero` error, replacing with `quieres`;
- Replaced "parámetro script" with "parámetro `-script`".

### CODE REVIEW

**Comment by gusbemacbe** [comment]
@ryanoasis 

Ready!

**Comment by LiTO773** [comment]
Thanks for helping with the translation of the pt-pt file. I've been extremely busy lately and sadly couldn't fix the changes myself. I've reviewed your file and the translation seems correct.

However, **DO NOT** use the old AO in the pt-pt file. The current AO is how the pt-pt language is written and has already been adopted and enforced in the country.

`(the most of people from Portugal rejected the new AO agreement)` is a biased argument to revert to the old spelling ([and couldn't be further from the truth](https://www.jn.pt/nacional/educacao/chega-ao-fim-o-periodo-de-transicao-do-acordo-ortografico-4564905.html)).

If you want to use the old AO please create a pt-br README, since it is still in use in Brazil.

**Comment by gusbemacbe** [comment]
Hello @LiTO773 !

I have talked with a native Portuguese, he suggested me to use the new AO. I have just reverted to the new AO. In spite of it, Público.pt, ironically Jornal de Notícias and many people still use the old AO. 

> If you want to use the old AO please create a pt-br README, since it is still in use in Brazil.

It is already enforced in the whole country, in spite of many people opposing the new AO.

**Comment by ryanoasis** [comment]
I am not much help here but did scan through it.

If you are both good with the changes I'll merge it!


Thanks!

**Comment by gusbemacbe** [comment]
Hey @LiTO773, where are you? We need your approval.

**Comment by LiTO773** [comment]
LGTM

Just change `parámetro` to `parâmetro`, since that's the correct spelling (only noticed now sry).

Everything else is great 👏

**Comment by gusbemacbe** [comment]
@LiTO773, done. 

@ryanoasis, done. @LiTO773 approved.

**Comment by ryanoasis** [comment]
Thanks

**Pull request merged**
