### PR TITLE
feat(font): add new font which is called Twilio Sans Mono

### PR DESCRIPTION
**Pull request by CoolPlayLin**
#### Description

- Issue: #1458 

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
@Finii Hello, this PR has opened since 5 day ago, but it has not been reviewed. Would you mind taking a look?

**Comment by Finii** [comment]
> @Finii Hello, this PR has opened since 5 day ago, but it has not been reviewed. Would you mind taking a look?

Hej, we have this Xmas - New Year - Season - Holiday times right now and I'm with my family; not working, sorry.

**Comment by CoolPlayLin** [comment]
@Finii 
Sorry for trouble. There is no Christmas in China since we have the Spring Festival instead. Anyway, merry Christmas.

**Comment by Finii** [comment]
I fixed some details for the automatic processing etc.

One problem remains: The name. `Twilio` is a reserverd font name and due to licensing terms we are not allowd to modify the font and keep the name. See all the other RFN fonts, that needed a rename (e.g. `Terminus` -> `Terminess`, `Monaspace` -> `Monaspice`, ...)

**Comment by CoolPlayLin** [comment]
CC @twilio

**Comment by CoolPlayLin** [comment]
How I resolve this?

**Comment by getawaywithrmdir** [comment]
So, like...?

1. Twirlio
2. Twinlio
3. Trilio
4. Twileo
5. Twylio
6. Tweelio
7. ...

I personally like Twirlio Sans Mono. 💃

**Comment by CoolPlayLin** [comment]
I don't know how I can solve this.

**Comment by Finii** [comment]
@CoolPlayLin You don't need to, if this font will be added the renaming is simple.

I also like Twirlio :-D

**Comment by TheBeeBoi** [comment]
Twillyo Font Nerd Font Mono?

**Comment by TheBeeBoi** [comment]
Twillyo is the same sound, so like Terminus -> Terminess
Twillyo will keep the original name, yes?

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

It will be evaluated on next release (as the others that 'just' raised an Issue)

**Pull request closed without merging**
