### PR TITLE
Add Gleam icon

### PR DESCRIPTION
**Pull request by okkdev**
#### Description

Adds Lucy the Gleam Logo/Mascot.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What does this Pull Request (PR) do?

Adds Lucy the Gleam Logo/Mascot to the Glyph set.

### CODE REVIEW

**Comment by Finii** [comment]
Thanks for the PR!

Can you describe
* What gleam is and why it is relevant
* Where the svg originates from

**Comment by okkdev** [comment]
Sorry about that.

Gleam is an awesome programming language that just reached it's 1.0
Here is the website: https://gleam.run/

The icon is from the website but I removed the pink fill and slightly thickened the lines to make it a bit more legible at small sizes.

**Comment by okkdev** [comment]
Do you require any additional information? 😄

**Comment by Finii** [comment]
Closing because transferred to https://github.com/ryanoasis/nerd-fonts/discussions/1095

It will be evaluated on next release (as the others that 'just' raised an Issue)

**Comment by okkdev** [comment]
The Gleam logo has been merged into devicon https://github.com/devicons/devicon/pull/2319 but devicon doesn't allow for multiple icon variants, but Gleam offers a logo optimized for small (16x16px) use cases, like fonts, on their branding page https://gleam.run/branding/
So I think it would still be valuable to include the optimized version in nerd fonts.
I've updated my pr branch (https://github.com/ryanoasis/nerd-fonts/compare/master...okkdev:nerd-fonts:gleam-icon) with the small optimized gleam logo.

**Pull request closed without merging**
