### PR TITLE
Improve custom patching

### PR DESCRIPTION
**Pull request by Finii**
#### Description

This changes how custom patching (i.e. with `--custom`) is handled.
When I tried to use the feature myself several shortcomings became obvious.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What are the relevant tickets (if any)?
This is mostly triggered by @siduck 's problem

* https://github.com/ryanoasis/nerd-fonts/issues/1213#issuecomment-1539214446
* https://github.com/ryanoasis/nerd-fonts/issues/1190#issuecomment-1532632029
* #1207

### CODE REVIEW

**Comment by siduck** [comment]
@Finii  thanks for adding file-dir icon back man :D

**Comment by Finii** [comment]
This is so utterly disappointing. Create your own set of fonts, but call them differently. Maybe `NvchatFont` or whatever, but DO NOT publish packages with tampered-with `Nerd Fonts` :-(

Spent several hours on you problem and this is how you thank me.

**Comment by siduck** [comment]
> > nvchad users probably and they'd have to do the same
> 
> Why on earth should they want an icon that has been dropped from Octo years ago and does not fit nicely with all others roll_eyes

it looks better imo and the users are already complaining when their fav folder icon got removed! And that icon does matches with other folder related icons we use ( cod* ), it looks like a filled version of the cod-folder, thats why I like it 

image

I wouldnt be bothered much if I was the only one using this icon, it has become a part of our UI since the beginning and made our folders unique ( similar to doom emacs filetree icons ) 

I really appreciate your work tho, no need to get mad! I never meant to be rude / disrespectful in our conversations. Just wanted to bring that icon back on a large scale

**Comment by siduck** [comment]
> The old icon could only move into `nf-custom-` which is where we preserved some other old ones, but that means a codepoint change.

a codepoint change wouldnt do any harm as icon's still preserved!

**Comment by siduck** [comment]
> What will happen when Microsoft updates its Codicons? At the moment they kept the symbols, but what if. Other icon changes will occur in the future with modernization I'm sure.

we use those folders only at few places and they're rarely visible, so not much of big deal. but that file-directory icon was our main one, we used it at the statusline etc too

**Comment by Finii** [comment]
Found other bugs while moving the icon to `custom` ... :roll_eyes: 
Some `custom` icons are ~~broken~~ slightly deformed ?!

I fear it (the folder icon) will be patched a bit more to the right, because the custom icons are all centered (on something) while the octicons were left aligned. Need to check how much.

**Comment by Finii** [comment]
Hmm, it is still left aligned but a bit smaller :thinking: 

image

**Comment by siduck** [comment]
>  custom icons are all centered 

didnt know! I thought only the fonts that end with "Mono" are centered :thinking:

**Comment by siduck** [comment]
> Hmm, it is still left aligned but a bit smaller thinking
> 
> image

oops looks a bit smaller  :fearful:

**Pull request merged**
