### PR TITLE
Add CLI cheatsheet script

### PR DESCRIPTION
**Pull request by hasecilu**
#### Description

_CLI cheatsheet._

#### Requirements / Checklist

- [X] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan.
      Issue number where discussion took place: #xxx
- [ ] If this contains a font/glyph add its origin as background info below (e.g. URL)
- [ ] Verified the license of any newly added font, glyph, or glyph set. License is: xxx

#### What does this Pull Request (PR) do?
Adds a script that let users to search for an icon using its name using the NF library scripts.
#### How should this be manually tested?
```shell
$ ./cheatsheet divider
       e0b0    i_pl_left_hard_divider
       e0b1    i_pl_left_soft_divider
       e0b2    i_pl_right_hard_divider
       e0b3    i_pl_right_soft_divider
       e0d7    i_ple_left_hard_divider_inverse
       e0d6    i_ple_right_hard_divider_inverse
```
#### Any background context you can provide?
There are times when I want to look for a glyph but using the online cheatsheet tool takes "a lot of time". The tool is not slow I mean the whole workflow.

### CODE REVIEW

**Comment by hasecilu** [comment]
To fix the shellcheck fail we can update the hook to use `-x` flag to let it access external files `shellcheck -x cheatsheet.sh` or add a config file. [docs](https://www.shellcheck.net/wiki/Directive#external-sources)

**Comment by Finii** [comment]
Thanks! Excellent!

**Comment by Finii** [comment]
Ah, added also these commits:

66ae03de2 `shellcheck.sh: Unify variable style`
d294607b1 `cheatsheet.sh: Make CWD independent`

**Comment by Finii** [comment]
This (again) reminds me that `glyphnames` needs a mechanism for aliases, so that in some far future we can drop the `i_` files and instead work with the json 'database'.

**Comment by Finii** [comment]
What is `redundant` ?! :thinking: 

image

**Pull request merged**
