### PR TITLE
font info: Remove references to 'Terminess' from non-Terminus fonts

### PR DESCRIPTION
**Pull request by Finii**
#### Description

**[why]**
In some fonts, on in the `patched-fonts/` directory the font information
files contain an explanation why the font is called "Terminess" and not
"Termius" - but the font is neither.

Affected: `DroidSansMono` and `Ubuntu` (non mono)

I assume this is a 'I copied the info file over from an existing font
and just change the names' (but the source was unfortunately Terminess).

**[how]**
Manually remove the paragraph from all files that contain it which but
have another name altogether.

**[note]**
Not shure if they are autogenerated somehow, with for example
`standardize-and-complete-readmes.sh` ... but a `git grep` showed only
the files that are changed with this PR.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] ~Scripts execute without error (if necessary):~
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [x] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### What does this Pull Request (PR) do?

Remove wrong paragraph from font info `*.md` files.

#### How should this be manually tested?

Look on web pages in the branch, patched fonts, Ubuntu.
[Direct link](https://github.com/ryanoasis/nerd-fonts/tree/bugfix/markdown-contains-terminess/patched-fonts/Ubuntu)

#### Any background context you can provide?

While I fetched `Ubuntu` to try it out on Windows with Panose.

#### Screenshots (if appropriate or helpful)

image

_Edit: Add direct link to changed web page(s)_

### CODE REVIEW

**Comment by Finii** [comment]
> Manually remove the paragraph from all files that **contain it which but have** another name altogether.

Hello! Grammar?! Word order? :disappointed:

**Comment by Finii** [comment]
Hmm,

```
$ git grep config_rfn_substitue

bin/scripts/standardize-and-complete-readmes.sh:  local config_rfn_substitue=$1; shift
bin/scripts/standardize-and-complete-readmes.sh:  if [ "$config_rfn" ] && [ "$config_rfn_substitue" ]
bin/scripts/standardize-and-complete-readmes.sh:      printf "\\n## Why \`%s\` and not \`%s\`?\\n" "$config_rfn_substitue" "$config_rfn"
bin/scripts/standardize-and-complete-readmes.sh:      unset config_rfn_substitue
bin/scripts/standardize-and-complete-readmes.sh:      appendRfnInfo "$config_rfn" "$config_rfn_substitue" "$PWD" "$to"
bin/scripts/standardize-and-complete-readmes.sh:      appendRfnInfo "$config_rfn" "$config_rfn_substitue" "$PWD" "$to"
bin/scripts/standardize-and-complete-readmes.sh:      appendRfnInfo "$config_rfn" "$config_rfn_substitue" "$PWD" "$to"
bin/scripts/standardize-and-complete-readmes.sh:    appendRfnInfo "$config_rfn" "$config_rfn_substitue" "$PWD" "$to"
src/unpatched-fonts/FiraMono/config.cfg:config_rfn_substitue=Fura
src/unpatched-fonts/Hasklig/config.cfg:config_rfn_substitue=Hasklug
src/unpatched-fonts/Hermit/config.cfg:config_rfn_substitue=Hurmit
src/unpatched-fonts/IBMPlexMono/config.cfg:config_rfn_substitue=Blex
src/unpatched-fonts/LiberationMono/config.cfg:config_rfn_substitue=Literation
src/unpatched-fonts/ShareTechMono/config.cfg:config_rfn_substitue=Shure
src/unpatched-fonts/SourceCodePro/config.cfg:config_rfn_substitue=Sauce
src/unpatched-fonts/Terminus/config.cfg:config_rfn_substitue=Terminess
src/unpatched-fonts/iA-Writer/config.cfg:config_rfn_substitue="iM Writing"
$
```

I do not really / exactly know what `s&c-readmes` does, but this looks like something would be needed for Cascadia.

Rules for `Fira`/`Fura` seem to be missing from `font-patcher`.
Rules for `Anka/Coder` exist in `font-patcher` but we don't have the font (which is ok).

**Comment by ryanoasis** [comment]
It looks like somewhere/somehow a few fonts haven't had their specific readme updated by the script (DroidSansMono also seems to be incorrect).

> I do not really / exactly know what s&c-readmes does, but this looks like something would be needed for Cascadia.

Agree Cascadia should have it. I tried to put a basic description at the top of the script. basically tries to compile a standard readme from all the various possible variations a font's readme might be in and also adds a few extra bits like the RFN info and common FAQ.

> Rules for Fira/Fura seem to be missing from font-patcher.

You mean for the reserved font name right? It _was_ there previously but has been [removed](https://github.com/ryanoasis/nerd-fonts/commit/86dff75f7e7faf3f22f8a5234810163489d10e4d) because Fira's [RFN clause was removed](https://github.com/tonsky/FiraCode/issues/767#issuecomment-495163622)

**Comment by Finii** [comment]
> Fira's RFN clause was removed

Ah, wow! :+1:

What puzzles me is that `patched_fonts/FiraMono/` (still) contains `Fura Mono Nerd Font`, but that name is already in the source fonts, so ;-) Just mentioning in case that it is not intended.

**Comment by ryanoasis** [comment]
yeah so I found an issue there with FiraMono which still _does_ have an RFN. I.e. FiraMono has the RFN but FiraCode does not. That is my understanding at least... I pushed up some fixes either way

**Pull request merged**
