### PR TITLE
Update JetBrainsMono to version v2.001

### PR DESCRIPTION
**Pull request by moritzdietz**
#### Description

This PR updates JetBrainsMono from version v1.0.5 to version v2.001

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] Scripts execute without error (if necessary):
- [x] Extended the README and documentation if necessary, e.g. You added a new font please update the table
----
```text
$ ./gotta-patch-em-all-font-patcher\!.sh "" info
# [Nerd Fonts]  Total runtime: 0:00:00:38
# All fonts patched to sub-directories in                       'patched-fonts'
# The total number of font typefaces patched was                '50'
# The total number of font families patched was                 '719'
# The total number of 'complete' patched fonts created was      '2876'
# The total number of 'variation' patched fonts created was     '1485410'
# The total number of patched fonts created was                 '1488286'
```
Ran `./gotta-patch-em-all-font-patcher\!.sh JetBrainsMono` and it didn't throw any obvious errors.
```
$ ./gotta-patch-em-all-font-patcher\!.sh JetBrainsMono
# [Nerd Fonts]  Total runtime: 0:00:10:34
# All fonts patched to sub-directories in                       'patched-fonts'
# The total number of font typefaces patched was                '50'
# The total number of font families patched was                 '30'
# The total number of 'complete' patched fonts created was      '120'
# The total number of 'variation' patched fonts created was     '122820'
# The total number of patched fonts created was                 '122940'
```

This PR is ready for review.

### CODE REVIEW

**Comment by moritzdietz** [comment]
I just noticed that the variable font folder hasn't been filled with fonts. I'll look into it.

**Comment by moritzdietz** [comment]
Ok so it seems that the variable font won't patch:
```
$ fontforge -script ./font-patcher src/unpatched-fonts/JetBrainsMono/Variable/JetBrainsMono-Variable.ttf --complete
Copyright (c) 2000-2020. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20190801
 Based on sources from 03:10 UTC  6-Mar-2020-ML-D-GDK3.
Failed to open hotkey definition file: /usr/local/share/fontforge/hotkeys/default
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
  Ignoring 'STAT' style attributes table
Warning: Mac string is a subset of the Windows string in the 'name' table
  for the Family string in the English (US) language.
Warning: Mac and Windows entries in the 'name' table differ for the
  Styles (SubFamily) string in the language English (US)
  Mac String: Variable
  Windows String: Regular
Adding 54 Glyphs from Seti-UI + Custom Set
╢██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟ 4%./font-patcher:823: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  glyph.left_side_bearing = 0.0
╢████████████████░░░░░░░░░░░░░░░░░░░░░░░░╟ 41%[1]    42192 segmentation fault (core dumped)  fontforge -script ./font-patcher  --complete
```

**Comment by moritzdietz** [comment]
Ok so for the folks interested: know that there must be something wrong with some glyphs. I will check if this is caused by generating them with nerd-fonts glyphs or if this an issue with the font itself.
image

**Comment by juchom** [comment]
I reported a similar issue when I tried the docker image [here](https://github.com/ryanoasis/nerd-fonts/pull/449#issuecomment-629997324)

**Pull request merged**
