### PR TITLE
Update Cascadia Code to version 2007.01

### PR DESCRIPTION
**Pull request by natebwangsut**
#### Description

- Allowing weighted font families for Cascadia Code
  -  Switching to .otf format as .ttf contains multiple weights
- Fix ryanoasis/nerd-fonts#498

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ ] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [x] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### What does this Pull Request (PR) do?
- Update Cascadia Code to version 2007.11

### CODE REVIEW

**Comment by natebwangsut** [comment]
The CI failure is unrelated to PR

**Comment by ryanoasis** [comment]
That CI error should be fixed going forward. Thanks for the PR as well :+1: :smile:

**Comment by kppullin** [comment]
I noticed that the `Mono` version of the font contains ligatures which is contrary to this statement in the readme: `By the Nerd Font policy, the variant with the 'Mono' suffix is not supposed to have any ligatures. Use the non-Mono variants to have ligatures.`  The 2007.01 mono version of Cascadia Code from the Microsoft repo does not contain ligatures so I'd guess they're added downstream of the source.

This also exists in the current version of the font in `master` and might be better suited to open a separate issue.

**Comment by adrian5** [comment]
Any progress on this? Was it mostly just a sporadic CI failure that a rerun fixes, or are the misplaced ligatures a show-stopper?

I'd like to use CaskaydiaCove with different font weights.

**Comment by natebwangsut** [comment]
> I noticed that the `Mono` version of the font contains ligatures which is contrary to this statement in the readme: `By the Nerd Font policy, the variant with the 'Mono' suffix is not supposed to have any ligatures. Use the non-Mono variants to have ligatures.` The 2007.01 mono version of Cascadia Code from the Microsoft repo does not contain ligatures so I'd guess they're added downstream of the source.
> 
> This also exists in the current version of the font in `master` and might be better suited to open a separate issue.

Yes the ligature was added by the patcher. There's a conflicting definition on what does "Mono" mean, however per nerd-font repository:

> ## Features
> Monospaced (fixed-pitch, fixed-width) or double-width (non-monospaced) glyphs version of each font. This refers to the Nerd Font glyphs themselves not necessarily the Font as a whole

So, IMO since the PR was on nerd-font repo, I don't see any issues here.

**Comment by natebwangsut** [comment]
> Any progress on this? Was it mostly just a sporadic CI failure that a rerun fixes, or are the misplaced ligatures a show-stopper?
> 
> I'd like to use CaskaydiaCove with different font weights.

I cannot rerun the CI job, only maintainer / owner can do. @ryanoasis can you please rerun the job?

**Comment by ryanoasis** [comment]
Not sure what's going on with the CI jobs but these changes look good. Thanks!

**Pull request merged**
