### PR TITLE
Update Cascadia Code to 2102.25

### PR DESCRIPTION
**Pull request by nezorflame**
#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] ~Scripts execute without error (if necessary)~
- [x] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### What does this Pull Request (PR) do?

Updated the Cascadia Code font with the most recent ([v2102.25](https://github.com/microsoft/cascadia-code/releases/tag/v2102.25)) version of it (since the version in the repo doesn't have Cyrillic symbols which I need).

#### How should this be manually tested?

Works on Win10, need to check on other OSes.

#### Any background context you can provide?

Since this is my first PR and I'm on WIn10, I haven't found a way to produce non-Windows Compatible version of the font (yet), so I just copied the Windows Compatible patched font and renamed into the simple one (so the simple one and the Windows Compatible versions are identical). If that's inappropriate I'd like to know how to fix this.

Another thing: I might have messed the Mono-fonts - they're named differently it seems (check the last screenshot). Not sure how to fix this (just rename?)...

#### What are the relevant tickets (if any)?

None.

#### Screenshots (if appropriate or helpful)

Some examples:

image
image

Mono font:

image

### CODE REVIEW

**Comment by ryanoasis** [comment]
Thanks for updating this, it's appreciated.

>  I might have messed the Mono-fonts - they're named differently it seems

Yeah that is wrong. It doesn't seem to use the correct RFN same name but the Microsoft one. I can take a look..

> Since this is my first PR and I'm on WIn10, I haven't found a way to produce non-Windows Compatible version of the font (yet)

Hmm, even if you ware on Windows you should be able to produce the non windows specific versions. Can you tell me if you had some specific trouble doing so?

> so I just copied the Windows Compatible patched font and renamed into the simple one (so the simple one and the Windows Compatible versions are identical). If that's inappropriate I'd like to know how to fix this.

Seems reasonable but there are some specific adjustments the patcher makes if it's Windows vs not. So I think this is wrong sorry. Can you see my question above about the trouble you had in generating the patched fonts on Windows?

Thanks!

**Comment by notes365** [comment]
last version: [v2105.24](https://github.com/microsoft/cascadia-code/releases/tag/v2105.24)

**Comment by zzhaolei** [comment]
Looking forward to any updates here 😚

**Comment by codemacabre** [comment]
It may be worth bumping this further, to [2105.24](https://github.com/microsoft/cascadia-code/releases/tag/v2105.24), to also include Cascadia 'Curve' (the cursive variant).

**Comment by nezorflame** [comment]
I'll look into this when I have some spare time.

**Comment by KexyBiscuit** [comment]
Any update on this? @nezorflame

**Comment by Finii** [comment]
Temporary solution could be to use https://github.com/adam7/delugia-code which patches within hours after a new Cascadia Code has been released. This is done with the nerd-font tools.

**Comment by ryanoasis** [comment]
Now that #681 is merged the mono fonts should no longer be "messed up". @nezorflame if you have time would you like to pull in the latest master and try re-patching? Otherwise feel free to close the PR itself and start fresh.

If you don't have the time are you okay if we close the PR?

Apologize for getting back into things late, it has caused PRs to languish.

**Comment by nezorflame** [comment]
It's OK, I planned to do this earlier but didn't have time in the end.
I'd like to finish this PR so I'll rebase from master and fix the issues in 
the upcoming week.

Best regards,
Danilkin Ilya
_____________________

С уважением,
Данилкин Илья
Ryan L McIntyre ***@***.***> 19 ноября 2021 г. 08:33:49 написал:

**Comment by Finii** [comment]
Possibly it is also good to update the `src/unpatched-fonts/CascadiaCode/`?
From my understanding someone should be able to clone this repo and redo the patching by invoking `gotta-patch-em-all-font-patcher`. In this way there are no extra manual steps done when creating the patched versions that are later _lost_ because noone can remember them.

`src/unpatched-fonts/CascadiaCode/Regular/CascadiaCode-Regular.otf` is **2007.1**
`src/unpatched-fonts/CascadiaCode/README.rst` states **2007.11** (cough)

**Comment by KexyBiscuit** [comment]
@Finii Delugia looks awesome! Just wondering how are the fonts licensed? I see that the code is licensed under MIT License, but the fonts still contain (incorrect?) license info from Cascadia Code.

**Comment by Finii** [comment]
**Issue**: Patched font does not show up in some strictly-monospaced applications like `cmd` or `PowerShell`.

These are the names encoded in the font file:
image

And they do not turn up in `cmd`:
image

(Just the un-uninstallable MS original Cascadia Code fonts are selectable here).

This might be a general problem with a lot of nerd fonts, did not check ;-D

**Comment by Finii** [comment]
> Just wondering how are the fonts licensed? I see that the code is licensed under MIT License, but the fonts still contain (incorrect?) license info from Cascadia Code.

The MIT License just affects the scripts, that that repo consists of.

The generated font files hold the MS licensing information as required by the license that MS gives us with Cascadia Code, at least this is how I read the https://github.com/microsoft/cascadia-code/blob/main/LICENSE:

2) Original or Modified Versions of the Font Software may be bundled,
redistributed and/or sold with any software, provided that each copy
contains the above copyright notice and this license. These can be
included either as stand-alone text files, human-readable headers or
in the appropriate machine-readable metadata fields within text or
binary files as long as those fields can be easily viewed by the user.

3) No Modified Version of the Font Software may use the Reserved Font
Name(s) unless explicit written permission is granted by the corresponding
Copyright Holder. This restriction only applies to the primary font name as
presented to the users.

Form 2 I get the MS copyright needs to be kept and from 3 that the font needs to be renamed (of course).
Maybe I'm wrong, I'm no lawyer ;)

**Comment by KexyBiscuit** [comment]
> **Issue**: Patched font does not show up in some strictly-monospaced applications like `cmd` or `PowerShell`.
> 
> These are the names encoded in the font file: image
> 
> And they do not turn up in `cmd`: image
> 
> (Just the un-uninstallable MS original Cascadia Code fonts are selectable here).
> 
> This might be a general problem with a lot of nerd fonts, did not check ;-D

Yes, I also found that problem, though have no idea how to fix.

**Comment by Finii** [comment]
> Yes, I also found that problem, though have no idea how to fix.

If you tried some NerdFont fonts that have this issue on Windows, please raise an issue with the names of that fonts and possible a screenshot. I have a fix and will file a MR if there is an issue :-)

I just do not know if there is more than one font affected and because I'm no windows user experimenting on Windows is always a pain for me (setting up a machine, etc pp).

 (The commit itself is ready, but I myself did not put enough energy into researching the broadness of the issue, which I feel would be needed before patching `font-patcher`.)

**Comment by KexyBiscuit** [comment]
> > Yes, I also found that problem, though have no idea how to fix.
> 
> If you tried some NerdFont fonts that have this issue on Windows, please raise an issue with the names of that fonts and possible a screenshot. I have a fix and will file a MR if there is an issue :-)
> 
> I just do not know if there is more than one font affected and because I'm no windows user experimenting on Windows is always a pain for me (setting up a machine, etc pp).
> 
> (The commit itself is ready, but I myself did not put enough energy into researching the broadness of the issue, which I feel would be needed before patching `font-patcher`.)

The font with issue is not yet merged into the repo :-P once it's in I'll do.

**Comment by Finii** [comment]
Yesterday Cascadia released 2111.01 :roll_eyes:

Well, with no changes for us (only VF has been touched). But 2110.31 is should be.

Just rambling ;)

**Comment by Finii** [comment]
The PR above does not include `Cascadia Mono`.
Maybe that font should be added to our Cascadia portfolio?

**Comment by nezorflame** [comment]
Hi. I've finally got some time I can dedicate to opensource, so will probably update this PR or create a new one.

**Comment by Finii** [comment]
@nezorflame Did you notice #723? The patched-by-723 fonts can be grabbed [here](https://github.com/Finii/nerd-fonts/tree/feature/cascadia-2111.01-patched/patched-fonts/CascadiaCode)

**Comment by nezorflame** [comment]
@Finii yeah, just saw it, will probably create a new one.

**Pull request closed without merging**
