### PR TITLE
Fix markdown by forcing html

### PR DESCRIPTION
**Pull request by aloisdg**
#### Description

I found a markup problem in the readme.
I fixed the markdown by adding the html directly.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)

#### What does this Pull Request (PR) do?

Fix markup

#### Screenshots (if appropriate or helpful)

see the diff :)

### CODE REVIEW

**Comment by ryanoasis** [comment]
@aloisdg Woah I haven't noticed that! Thanks for the fix! :smile: 

This had rendered correctly before, seems like a recent GitHub change has caused this. Perhaps: https://github.com/blog/2333-a-formal-spec-for-github-flavored-markdown

**Comment by aloisdg** [comment]
@ryanoasis Yes maybe. I didnt check the whold document by the way.

**Comment by ryanoasis** [comment]
@aloisdg Yep sure that makes sense. Actually I see another issue down below I will fix. I think there will be quite a few repos on GitHub with some fixes needed :laughing:

**Comment by aloisdg** [comment]
A bot could fix that. :)

**Comment by ryanoasis** [comment]
Hah you are probably right :smile: 

Thanks again for the PR, inspired me to make some improvements to the readme and wiki :blush:

**Pull request merged**
