### PR TITLE
add support for codicons

### PR DESCRIPTION
**Pull request by cstrahan**
#### Description

Add support for codicons (https://github.com/microsoft/vscode-codicons).

@all-contributors please add @cstrahan for code

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [x] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### What does this Pull Request (PR) do?

Add support for codicons (https://github.com/microsoft/vscode-codicons).

#### How should this be manually tested?

Perhaps. I have tested this in the gedit text editor as well as within neovim (from gnome-terminal) using the configuration here: https://github.com/onsails/lspkind-nvim

#### Any background context you can provide?

These are the same glyphs used by VSCode for Language Server icons (e.g. Enum, Member, Class, etc).

#### What are the relevant tickets (if any)?

Closes https://github.com/ryanoasis/nerd-fonts/issues/620

#### Screenshots (if appropriate or helpful)

Screenshot from 2021-12-04 16-53-27

### CODE REVIEW

**Comment by cstrahan** [comment]
I'll note here that `codicon.ttf` is licensed under CC BY 4.0: 

* https://github.com/microsoft/vscode-codicons/blob/main/LICENSE
* https://creativecommons.org/licenses/by/4.0/

**Comment by cstrahan** [comment]
And the symbol start/end code points were taken from here: https://raw.githubusercontent.com/microsoft/vscode-codicons/main/dist/codicon.csv

**Comment by ryanoasis** [comment]
This is great. I'll check it out

**Comment by ryanoasis** [comment]
Could you move it into a sub directory and also drop the license file in the same folder?

I made a similar recent change here: https://github.com/ryanoasis/nerd-fonts/commit/9633b4d3625d1052514b51852a1e8bd8dc37e7d4

**Comment by ryanoasis** [comment]
@all-contributors please add @cstrahan for code

**Pull request merged**
