### PR TITLE
Update search page style

### PR DESCRIPTION
**Pull request by fadihania**
- Fix having multiple vertical scrollbars
 - Update icons lazy loading accordingly

#### Description
Fix having multiple vertical scrollbars while searching the icons, it's easier to use and better for User Experience. It's also update the lazy loading to work on the document scrolling instead of icons container

#### Requirements / Checklist

- [X] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [X] Verified the license of any newly added font, glyph, or glyph set

### CODE REVIEW

**Comment by Finii** [comment]
This looks excellent! Thank you very much!

**Comment by Finii** [comment]
WHAT!!?

```diff
CommitDate: Mon Jun 5 22:42:31 2023 +0300

    Update search page style
     - Fix having multiple vertical scrollbars
     - Update icons lazy loading accordingly
---
 _includes/css/nerd-font-tweaks.scss | 4 ++--
 cheat-sheet.js                      | 9 ++++++---
 2 files changed, 8 insertions(+), 5 deletions(-)
```

This looks so trivial, I have expected some very complicated stuff :-D

:+1:

**Comment by Finii** [comment]
What do you think about the commit I added, that...

```
    cheat-sheet: Show no icons by default
    
    [why]
    The additional hints in the bottom are hard to notice if we flood users
    with all available items first.
    Usually users want to search the icons and not browse, so showing them
    all per default seems better.
    
    [how]
    Just do not change the search term from "" to something else, so the
    search comes up empty on an empty search.
    
    If people search for a blank the previous mechanics to show all icons is
    triggered instead. A message to hint for this is added to the empty
    search result.
```

...starts the page up like this

image

**Comment by rszyma** [comment]
While this is still open, for further UX improvement I'd suggest adding autofocus on the search box (just like google.com) does

**Comment by rszyma** [comment]
Another suggestion: the text "Enter (part) of a word to search" is not grammatically correct usage of parantheses. The correct version would be this: "Enter (a part of) a word to search"

**Comment by Finii** [comment]
I have bad experience with this autofocus stuff, but that might be a browser problem, where reloading a page steals my focus from other applications or something. But, well, why not. If you could supply an idea what needs to change I can do that together with the grammar correction (tnx, that is the result of doing multiple things in parallel I guess :grimacing: ).

**Comment by fadihania** [comment]
> What do you think about the commit I added, that...
> 
> ```
>     cheat-sheet: Show no icons by default
>     
>     [why]
>     The additional hints in the bottom are hard to notice if we flood users
>     with all available items first.
>     Usually users want to search the icons and not browse, so showing them
>     all per default seems better.
>     
>     [how]
>     Just do not change the search term from "" to something else, so the
>     search comes up empty on an empty search.
>     
>     If people search for a blank the previous mechanics to show all icons is
>     triggered instead. A message to hint for this is added to the empty
>     search result.
> ```
> 
> ...starts the page up like this
> 
> image

That works for showing the comments below, but I think if the website redesigned so the upper section is smaller then we can have those comments at the top, with smaller font and maybe a catchy color or effect

**Comment by Finii** [comment]
So I just merge this now, and more changes can come later.
I know that the commit I added is just a workaround, but while we have no other solution this is the cheapest (easiest) change to still get that information across.
At least for the information on including into websites, that information is maybe out of place anyhow, but we could not come up with a better solution at that time (see 46168d53d00bd43069e292e0df048175b9debb18).

If @rszyma just comments with a diff or idea regarding the focus I can just add that without PR.

**Pull request merged**
