### PR TITLE
Add Lilex font

### PR DESCRIPTION
**Pull request by adavidzh**
#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ ] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [x] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### Any background context you can provide?

Some things that are unclear to me:
- If/how to add more functionality to `src/unpatched-fonts/Lilex`.
- Some of the icons on the table in the main `readme.md`, esp. since I do not have a Linux or Windows machine to test on and do not know what "EM Size" is.

#### Screenshots (if appropriate or helpful)

Screenshots would be nice, I agree. 😉

### CODE REVIEW

**Comment by adavidzh** [comment]
The travis failure is [not related to this PR](https://travis-ci.org/github/ryanoasis/nerd-fonts/builds/680665323#L141) but rather an `apt-get` issue that also affects #473.

**Comment by kierun** [comment]
@ryanoasis Is there any reasons why we cannot merge this? Not hassling, just curious.

**Comment by kazukazuinaina** [comment]
@kierun @adavidzh @ryanoasis 

Please see this PR > https://github.com/ryanoasis/nerd-fonts/pull/493
shellcheck comes standard with travis. Therefore, there is no need to install it explicitly.

## reference
https://github.com/koalaman/shellcheck/wiki/TravisCI

**Comment by ryanoasis** [comment]
Thanks for the PR and also the follow up. I'll be catching up but hope to make progress fairly soon. :smile:

**Comment by adavidzh** [comment]
@ryanoasis, since you merged #493, I can update my branch to reflect the CI fix.

**Comment by ryanoasis** [comment]
Sure. Great thanks :+1:

**Comment by adavidzh** [comment]
Any news here?

**Pull request merged**
