### PR TITLE
Add icon for hacklang

### PR DESCRIPTION
**Pull request by 4e554c4c**
#### Description

_Please explain the changes you made here._

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What does this Pull Request (PR) do?
I downloaded the Hack icon from [hacklang.org](https://hacklang.org/) whose source is on [github](https://github.com/hhvm/hacklang.org) and is licensed CC BY 4.0. Then edited it to be monochrome/font friendly in inkscape, added it to `original-source.otf` in fontforge as `U+E535`, and modified `font-patcher` and friends to support the changes.

#### What are the relevant tickets (if any)?

Similar PRs: #862 #833 #429

Closes:  #904

#### Screenshots (if appropriate or helpful)
fontforge
neovim

### CODE REVIEW

**Comment by 4e554c4c** [comment]
I have just been told this icon was already added to `seti-ui` upstream: https://github.com/jesseweed/seti-ui/blob/master/icons/hacklang.svg
might want to use that icon instead

**Comment by Finii** [comment]
Hmm, their latest release is still 0.8.3 from 2015.
Yet they talk about 1.0.0 in the readme.
Do you have a clue how they get that into atom?

**Comment by Finii** [comment]
Maybe the complete Seti stuff should be updated?

We have 59 'Seti & custom' at the moment, they have 168...

**Comment by 4e554c4c** [comment]
https://github.com/microsoft/vscode/commit/8023f20a6b0a397da1b49691262720dbbb59704f this is the VSCode commit including the Hack icon from Seti UI, it looks like they just update the `.woff` font and give names to the codepoints

**Comment by 4e554c4c** [comment]
It seems like VSCode pins a certain commit of that repo any time they update, they don't depend on releases

**Comment by Finii** [comment]
Ah, I fount the font :-}

image

**Comment by Finii** [comment]
Quick comparison

image

Notably the C and C++ icons look not very nice with new seti (personal opinion). Some other icons got nice updates.

**Comment by Finii** [comment]
And that again reminds me, which I already mentioned somewhere else, that me should generate the `original-source` from the svgs.

**Comment by Finii** [comment]
@4e554c4c Maybe you are inclined to have a look at the PR above (981), that does away with the manual labor on glyph updates/inserts.

**Comment by 4e554c4c** [comment]
@Finii I think I actually prefer the icon from the seti repo. How should I import it?

**Comment by Finii** [comment]
> @Finii I think I actually prefer the icon from the seti repo. How should I import it?

Thank you. I would rather update all/most of Seti and add the 'new' Seti icons while being at that. Now with the autogen that is a breeze ;-)

At some point in the future we need a `v2.3.0-RC1` :-> so that you can already try the new icon.

**Comment by 4e554c4c** [comment]
ok, if that's coming in the near future this commit shouldn't be necessary
thank you :)

**Comment by Finii** [comment]
Thank you; without your info about Seti I would not have come round to finally implement auto-rebuilding and thinking about updating Seti - at all.

**Pull request closed without merging**
