### PR TITLE
Update JetBrainsMono to version v2.210

### PR DESCRIPTION
**Pull request by moritzdietz**
#### Description
This PR updates JetBrainsMono to version v2.210. This is a follow up PR for #518.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `fontforge -script font-patcher src/unpatched-fonts/JetBrainsMono/Ligatures/Regular/JetBrainsMono-Regular.ttf --complete`
    - `./gotta-patch-em-all-font-patcher\!.sh JetBrainsMono`
- [x] Extended the README and documentation if necessary, e.g. You added a new font please update the table

### Script output:
<details>
  <summary>fontforge -script font-patcher src/unpatched-fonts/JetBrainsMono/Ligatures/Regular/JetBrainsMono-Regular.ttf --complete</summary>
  
  ```shell
fontforge -script font-patcher src/unpatched-fonts/JetBrainsMono/Ligatures/Regular/JetBrainsMono-Regular.ttf --complete
Copyright (c) 2000-2020. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20190801
 Based on sources from 03:10 UTC  6-Mar-2020-ML-D-GDK3.
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
Adding 54 Glyphs from Seti-UI + Custom Set
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set
╢████████████████████████████████████████╟ 100%
Adding 3 Glyphs from Powerline Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 4 Glyphs from Powerline Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Powerline Extra Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 21 Glyphs from Powerline Extra Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Powerline Extra Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 8 Glyphs from Powerline Extra Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 11 Glyphs from Pomicons Set
╢████████████████████████████████████████╟ 100%
The following table(s) in the font have been ignored by FontForge
  Ignoring 'EPAR'
The glyph named asterisk is mapped to U+F069.
  But its name indicates it should be mapped to U+002A.
The glyph named plus is mapped to U+F067.
  But its name indicates it should be mapped to U+002B.
The glyph named question is mapped to U+F128.
  But its name indicates it should be mapped to U+003F.
The glyph named minus is mapped to U+F068.
  But its name indicates it should be mapped to U+2212.
The glyph named heart is mapped to U+F004.
  But its name indicates it should be mapped to U+2665.
The glyph named home is mapped to U+F015.
  But its name indicates it should be mapped to U+21B8.
The glyph named check is mapped to U+F046.
  But its name indicates it should be mapped to U+2713.
The glyph named bell is mapped to U+F0A2.
  But its name indicates it should be mapped to U+2407.
The glyph named lessequal is mapped to U+F500.
  But its name indicates it should be mapped to U+2264.
The glyph named circle is mapped to U+F111.
  But its name indicates it should be mapped to U+25CB.
The glyph named smile is mapped to U+F118.
  But its name indicates it should be mapped to U+263A.
The glyph named frown is mapped to U+F119.
  But its name indicates it should be mapped to U+2322.
The glyph named bullseye is mapped to U+F140.
  But its name indicates it should be mapped to U+25CE.
The glyph named compass is mapped to U+F14E.
  But its name indicates it should be mapped to U+263C.
The glyph named female is mapped to U+F182.
  But its name indicates it should be mapped to U+2640.
The glyph named male is mapped to U+F183.
  But its name indicates it should be mapped to U+2642.
The glyph named sun is mapped to U+F185.
  But its name indicates it should be mapped to U+263C.
The glyph named venus is mapped to U+F221.
  But its name indicates it should be mapped to U+2640.
Adding 679 Glyphs from Font Awesome Set
╢████████████████████████████████████████╟ 100%
The glyph named slash is mapped to U+E016.
  But its name indicates it should be mapped to U+002F.
The glyph named pi is mapped to U+E02C.
  But its name indicates it should be mapped to U+03C0.
The glyph named ring is mapped to U+E03D.
  But its name indicates it should be mapped to U+02DA.
The glyph named infinity is mapped to U+E055.
  But its name indicates it should be mapped to U+221E.
The glyph named equal is mapped to U+E079.
  But its name indicates it should be mapped to U+003D.
Adding 170 Glyphs from Font Awesome Extension Set
╢████████████████████████████████████████╟ 100%
Adding 4 Glyphs from Power Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Power Symbols Set
╢████████████████████████████████████████╟ 100%
The PostScript font name "Material Design Icons" is invalid.
It should be printable ASCII,
must not contain (){}[]<>%/ or space
and must be shorter than 63 characters
The PostScript font name "Material Design Icons" is invalid.
It should be printable ASCII,
must not contain (){}[]<>%/ or space
and must be shorter than 63 characters
The glyph named alpha is mapped to U+F02B.
  But its name indicates it should be mapped to U+03B1.
The glyph named at is mapped to U+F065.
  But its name indicates it should be mapped to U+0040.
The glyph named backspace is mapped to U+F06E.
  But its name indicates it should be mapped to U+2408.
The glyph named bell is mapped to U+F09A.
  But its name indicates it should be mapped to U+2407.
The glyph named beta is mapped to U+F0A1.
  But its name indicates it should be mapped to U+03B2.
The glyph named box is mapped to U+F0D4.
  But its name indicates it should be mapped to U+25A1.
The glyph named check is mapped to U+F12C.
  But its name indicates it should be mapped to U+2713.
The glyph named compass is mapped to U+F18B.
  But its name indicates it should be mapped to U+263C.
The glyph named delete is mapped to U+F1C0.
  But its name indicates it should be mapped to U+2421.
The glyph named delta is mapped to U+F1C2.
  But its name indicates it should be mapped to U+03B4.
The glyph named diamond is mapped to U+F1C8.
  But its name indicates it should be mapped to U+2666.
The glyph named earth is mapped to U+F1E7.
  But its name indicates it should be mapped to U+2641.
The glyph named equal is mapped to U+F1FC.
  But its name indicates it should be mapped to U+003D.
The glyph named heart is mapped to U+F2D1.
  But its name indicates it should be mapped to U+2665.
The glyph named home is mapped to U+F2DC.
  But its name indicates it should be mapped to U+21B8.
The glyph named image is mapped to U+F2E9.
  But its name indicates it should be mapped to U+22B7.
The glyph named minus is mapped to U+F374.
  But its name indicates it should be mapped to U+2212.
The glyph named omega is mapped to U+F3C9.
  But its name indicates it should be mapped to U+03C9.
The glyph named percent is mapped to U+F3F0.
  But its name indicates it should be mapped to U+0025.
The glyph named pi is mapped to U+F3FF.
  But its name indicates it should be mapped to U+03C0.
The glyph named plus is mapped to U+F415.
  But its name indicates it should be mapped to U+002B.
The glyph named sigma is mapped to U+F4A0.
  But its name indicates it should be mapped to U+03C3.
The glyph named tie is mapped to U+F519.
  But its name indicates it should be mapped to U+2040.
The glyph named triangle is mapped to U+F536.
  But its name indicates it should be mapped to U+25B3.
The glyph named bullseye is mapped to U+F5DD.
  But its name indicates it should be mapped to U+25CE.
The glyph named copyright is mapped to U+F5E6.
  But its name indicates it should be mapped to U+00A9.
The glyph named lambda is mapped to U+F627.
  But its name indicates it should be mapped to U+03BB.
The glyph named gradient is mapped to U+F69F.
  But its name indicates it should be mapped to U+2207.
The glyph named asterisk is mapped to U+F6C3.
  But its name indicates it should be mapped to U+002A.
The glyph named hook is mapped to U+F6E1.
  But its name indicates it should be mapped to U+2440.
The glyph named infinity is mapped to U+F6E3.
  But its name indicates it should be mapped to U+221E.
The glyph named prescription is mapped to U+F705.
  But its name indicates it should be mapped to U+211E.
The glyph named tilde is mapped to U+F724.
  But its name indicates it should be mapped to U+02DC.
The glyph named cancel is mapped to U+F739.
  But its name indicates it should be mapped to U+2418.
The glyph named square is mapped to U+F763.
  But its name indicates it should be mapped to U+25A1.
The glyph named circle is mapped to U+F764.
  But its name indicates it should be mapped to U+25CB.
The glyph named null is mapped to U+F7E1.
  But its name indicates it should be mapped to U+2400.
The glyph named pipe is mapped to U+F7E4.
  But its name indicates it should be mapped to U+01C0.
The glyph named ring is mapped to U+F7EA.
  But its name indicates it should be mapped to U+02DA.
Adding 2119 Glyphs from Material Set
╢████████████████████████████████████████╟ 100%
The following table(s) in the font have been ignored by FontForge
  Ignoring 'webf'
Adding 228 Glyphs from Weather Icons Set
╢████████████████████████████████████████╟ 100%
Adding 29 Glyphs from Font Logos (Font Linux) Set
╢████████████████████████████████████████╟ 100%
The glyph named question is mapped to U+F02C.
  But its name indicates it should be mapped to U+003F.
The glyph named check is mapped to U+F03A.
  But its name indicates it should be mapped to U+2713.
The glyph named plus is mapped to U+F05D.
  But its name indicates it should be mapped to U+002B.
The glyph named x is mapped to U+F081.
  But its name indicates it should be mapped to U+0078.
The glyph named home is mapped to U+F08D.
  But its name indicates it should be mapped to U+21B8.
The glyph named ellipsis is mapped to U+F09A.
  But its name indicates it should be mapped to U+2026.
The glyph named bell is mapped to U+F0DE.
  But its name indicates it should be mapped to U+2407.
Adding 169 Glyphs from Octicons Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Octicons Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Octicons Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Octicons Set
╢████████████████████████████████████████╟ 100%

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontComplete-Regular
  ```
</details>
<details>
  <summary>./gotta-patch-em-all-font-patcher\!.sh JetBrainsMono</summary>
  
  ```shell
$ ./gotta-patch-em-all-font-patcher\!.sh JetBrainsMono
# [Nerd Fonts]  Parameter given, limiting search and patch to pattern 'JetBrainsMono' given
# [Nerd Fonts]  Total source fonts found: 28
# [Nerd Fonts]  Complete Variation Count after max parallel process is  0

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontComplete-Bold Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Bold Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFo-Bold Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFo-Bold Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-Light

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-Italic

Generated: JetBrainsMonoNLNerdFontComplete-Bold Italic

Generated: JetBrainsMonoNLNerdFontComplete-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontComplete-Light

Generated: JetBrainsMonoNerdFontComplete-Bold

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontComplete-Italic

Generated: JetBrainsMonoNerdFontComplete-ExtraBold

Generated: JetBrainsMonoNerdFontComplete-Italic

Generated: JetBrainsMonoNerdFontComplete-Italic

Generated: JetBrainsMonoNerdFontComplete-Medium

Generated: JetBrainsMonoNerdFontComplete-Thin

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-Medium

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-ExtraBold

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-Italic

Generated: JetBrainsMonoNLNerdFontComplete-Italic

Generated: JetBrainsMonoNLNerdFontComplete-Thin

Generated: JetBrainsMonoNLNerdFontComplete-Regular

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-Bold

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-Italic

Generated: JetBrainsMonoNLNerdFontComplete-ExtraLight

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontComplete-Italic

Generated: JetBrainsMonoNerdFontComplete-ExtraLight

Generated: JetBrainsMonoNerdFontComplete-Regular

Generated: JetBrainsMonoNerdFontComplete-Italic

Generated: JetBrainsMonoNerdFontComplete-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Light

Generated: JetBrainsMonoNLNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Bold Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Light

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Thin

Generated: JetBrainsMonoNerdFontCompleteM-Italic

Generated: JetBrainsMonoNerdFontCompleteM-Italic

Generated: JetBrainsMonoNerdFontCompleteM-Bold

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Medium

Generated: JetBrainsMonoNLNerdFontCompleteM-Medium

Generated: JetBrainsMonoNerdFontCompleteM-ExtraBold

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Bold

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Regular

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-ExtraBold

Generated: JetBrainsMonoNLNerdFontCompleteM-Italic

Generated: JetBrainsMonoNLNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-ExtraLight

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Italic

Generated: JetBrainsMonoNLNerdFontCompleteM-Thin

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Regular

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Italic

Generated: JetBrainsMonoNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Italic

Generated: JetBrainsMonoNerdFontCompleteM-ExtraLight

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCo-Light

Generated: JetBrainsMonoNLNerdFontC-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Medium

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerd-Bold Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompl-Thin

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontComp-Light

Generated: JetBrainsMonoNerdFont-ExtraBold

Generated: JetBrainsMonoNerdFontCompl-Bold

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Medium

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCom-Bold

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFont-Regular

Generated: JetBrainsMonoNLNerdFo-ExtraBold

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Generated: JetBrainsMonoNLNerdF-ExtraLight

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCo-Regular

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCom-Thin

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFon-ExtraLight

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Medium

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerd-Bold Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Generated: JetBrainsMonoNLNerdFontCo-Light

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCom-Bold

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFont-ExtraBold

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Generated: JetBrainsMonoNLNerdFont-Regular

Generated: JetBrainsMonoNerdFontComp-Light

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFo-ExtraBold

Generated: JetBrainsMonoNLNerdFontC-Italic

Generated: JetBrainsMonoNerdFontCompl-Thin

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompl-Bold

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdF-ExtraLight

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Generated: JetBrainsMonoNLNerdFontC-Italic

Generated: JetBrainsMonoNerdFontCom-Medium

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCom-Thin

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCo-Regular

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Generated: JetBrainsMonoNerdFon-ExtraLight
# [Nerd Fonts]  Generating info for 'JetBrainsMono-BoldItalic.ttf':
# [Nerd Fonts]  * Re-generate parent directory readme
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-ThinItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-LightItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-Regular.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-ExtraBoldItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-Bold.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-Light.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-MediumItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-Medium.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-ExtraLight.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-ExtraLightItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-ExtraBold.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-Italic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-Thin.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-BoldItalic.ttf':
# [Nerd Fonts]  * Re-generate parent directory readme
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-ThinItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-LightItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-Regular.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-ExtraBoldItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-Bold.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-Light.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-MediumItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-Medium.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-ExtraLight.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-ExtraLightItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-ExtraBold.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-Italic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-Thin.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Total runtime: 0:00:13:56
# All fonts patched to sub-directories in                       'patched-fonts'
# The total number of font typefaces patched was                '51'
# The total number of font families patched was                 '28'
# The total number of 'complete' patched fonts created was      '112'
# The total number of 'variation' patched fonts created was     '114632'
# The total number of patched fonts created was                 '114744'
  ```
</details>

----

### CODE REVIEW

**Comment by moritzdietz** [comment]
Alright, this PR is now ready for review. I haven't done any visual comparisons and checks yet like I did in #518 but will do it tomorrow.

**Comment by JanPokorny** [comment]
There is a regression in Windows Terminal -- double-width icons are squished into single-width. Interestingly, this does not concern VSCode's or JetBrains IDE's terminal, just Windows Terminal. (So this might be a Windows Terminal issue -- but still, the issue is not occurring for the version currently in master.)

Version in master:
obrazek

This PR:
obrazek

The prompt text is:
```
Main on  master [?⇣]
 ❯
```

**Comment by moritzdietz** [comment]
It’s not just that terminal. I’ve seen it in my Alacritty as well. Not sure how to go about it though.

**Comment by ryanoasis** [comment]
@moritzdietz Are you okay with me closing #518 now that you have a new PR for the latest version? 

I only ask in case you want credit for work done in both :smile:. I am happy to go either way here, just let me know!

**Comment by moritzdietz** [comment]
@ryanoasis Sure you can close the other PR. I don't think folks are particularly interested in that specific version of the font anyway so I don't think it needs to be in the repo. So meh :man_shrugging: 

One thing I want to mention is that I did notice some behaviour change for glyphs too.
Not sure if it's only related to the ones already included in the new version here https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.210 or if it happens on the ones mentioned by @JanPokorny and others.

I "had" to replace the ❯ character with a bolder one as it was too tiny in my prompt.
image

Can we do anything about this?

**Comment by danielbayley** [comment]
Relating to https://github.com/ryanoasis/nerd-fonts/issues/487#issuecomment-745330827 …

@moritzdietz @ryanoasis Are the versions with the `Mono` suffix being generated here from the fonts in the `ttf/No ligatures` subfolder of the [original](https://jetbrains.com/lp/mono) download? If not, this might explain why, for example `JetBrains Mono Regular Nerd Font Complete Mono.ttf` still has ligatures despite this:

> By the Nerd Font policy, the variant with the 'Mono' suffix is not supposed to have any ligatures. Use the non-Mono variants to have ligatures.

**Comment by moritzdietz** [comment]
@JanPokorny I used the directory structure provided by the zip download of the original font and it **should** be the same. So if you go to either of the two folders here https://github.com/moritzdietz/nerd-fonts/tree/moritzdietz/JetBrainsMono-2.210/patched-fonts/JetBrainsMono you should get the right version.
Is this not the case?

**Comment by danielbayley** [comment]
@moritzdietz Yep, can confirm it works… Nice one! It's the current existing release that is broken. @ryanoasis Please can you merge this!

**Comment by moritzdietz** [comment]
Well before we can merge this I'd first like to talk about the change in glyph size - as mentioned before.
But I guess this will take place in 2021 :)

**Comment by kidonng** [comment]
FYI there's a new release of JBMono: https://github.com/JetBrains/JetBrainsMono/releases/tag/v2.221

**Comment by moritzdietz** [comment]
@kidonng There is an issue with the version you linked - https://github.com/JetBrains/JetBrainsMono/issues/387
I'll gladly do a PR for the next version if that one seems ok.

Yet I'd love to get some feedback on whether we/I can do something about the issues described here.

**Comment by kidonng** [comment]
@moritzdietz Looks like the issue is fixed in https://github.com/JetBrains/JetBrainsMono/commit/e41fd05d1f29e0c474a7c9d737982839690d4651, so just wait for an official release. Still, thanks for the updated fonts! ❤️

**Comment by moritzdietz** [comment]
Ok, I just made a new PR #572. This could, like the other one be merged or now, I don't really have an opinion about it :)

**Comment by ssoriche** [comment]
Can this be merged? There's an issue with the current Nerd Font version with spacing between box characters that there's a fix for in the newer JetBrainsMono version.

**Pull request merged**
