### PR TITLE
Update 0xProto to 2.201

### PR DESCRIPTION
**Pull request by my4ng**
#### Description

Update 0xProto from 1.603 to version 2.201. Check the [changelog](https://github.com/0xType/0xProto/compare/1.603...2.201) for more details.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set. License is: OFL-1.1 license (NO CHANGE)

#### What does this Pull Request (PR) do?

Update 0xProto to version 2.201.

#### How should this be manually tested?
```
fontforge --script ./font-patcher src/unpatched-fonts/0xProto/Regular/0xProto-Regular.ttf --complete --debug 2
fontforge --script ./font-patcher src/unpatched-fonts/0xProto/Italic/0xProto-Bold.ttf --complete --debug 2
fontforge --script ./font-patcher src/unpatched-fonts/0xProto/Italic/0xProto-Italic.ttf --complete --debug 2
```

### CODE REVIEW

**Comment by Finii** [comment]
Thanks for the nice PR!

One question: Why did you put the font file into sub-directories? Is there anything in the documentation that suggests it? I have seen this now with multiple PRs.

> "is a programming font focused on source code legibility."

Well, which font does not? That slogan is even lamer than before ;-) But that seems to be the official 'subtitle'.
Otoh we could add something meaningful instead, if you have any idea why it is great?

**Comment by my4ng** [comment]
> One question: Why did you put the font file into sub-directories? Is there anything in the documentation that suggests it? I have seen this now with multiple PRs.

I thought this is required in the Contributing Guidelines:

> Make sure to update the correct subfolders for each font style (e.g. `src/unpatched-fonts/xyz/bold/{BOLD FONT FILES HERE}`), if applicable

Since 0xProto has released a new dedicated italic version, I thought it makes sense to put them in Regular and Italic folders separately.

> Otoh we could add something meaningful instead, if you have any idea why it is great?

I think the features headings in the README are good pointers, especially clear differentiation and ligatures that do not deform.

**Comment by Finii** [comment]
Thanks for the feedback!

> > if applicable

Ah I see.

> are good pointers

What do you think about .... lets see

`... is a programming font with clear differentiation and ligatures that do not deform`

:-)

----

Marking this as ready, but I will hold it back until release time, and update to whatever version is current then (maybe 2.0.1 ;)

If you like maybe you can undo the sub-directory change and put both fonts into one directory. But I can change that later if you prefer.

**Comment by Finii** [comment]
@allcontributors please add @my4ng for code

**Comment by Finii** [comment]
:thought_balloon: allcontributors has some problem? I will try again later...

**Comment by my4ng** [comment]
> If you like maybe you can undo the sub-directory change and put both fonts into one directory. But I can change that later if you prefer.

Yeah I saw a couple other unpatched fonts were doing that, so I just followed suit :sweat_smile:. Anyway, I have corrected that but I left the one-line description as it was.

**Comment by Finii** [comment]
@allcontributors please add @my4ng for code

**Comment by my4ng** [comment]
I have updated 0xProto to [2.001](https://github.com/0xType/0xProto/releases/tag/2.001)

**Comment by Finii** [comment]
Thanks @my4ng :green_heart:

**Comment by Finii** [comment]
:thought_balloon: Need to start work for the new Release, milestone is 9/24. At the moment too many other things on my personal agenda

**Comment by Finii** [comment]
@my4ng 

:sob: 

Feel free to keep pinging me, I just struggle to find a longer time slot; the short times I do find currently just do not suffice to get the 'flow running' :-( I hope for some time in the coming weekend, but that already seems to be filled up by _stuff_ :grimacing: 

I know how frustrating that is for all the ppl waiting for the release, from when I was the person waiting for the maintainer to 'just trigger a release, what can be so difficult'.

One problem is of course #1691, if you want you could review the icon sizes etc ;-D

**Comment by Finii** [comment]
Thank you again!

**Pull request merged**
