### PR TITLE
docs: fix logo image source path

### PR DESCRIPTION
**Pull request by kurt-liao**
#### Description

Fix the logo source path in *cn* and *tw* documentation.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What does this Pull Request (PR) do?

Fix the logo source path in *cn* and *tw* documentation.

### CODE REVIEW

**Comment by Finii** [comment]
Great! Thank you!

Just did a quick check .. there are more broken image links as it seems:

```
$ grep images/ *.md | sed 's/.*images/images/; s/[")?].*//' | xargs ls -l
ls: cannot access 'images/nerd-fonts-logo.png': No such file or directory
ls: cannot access 'images/fontforge-glyph-set-font-linux.png': No such file or directory
ls: cannot access 'images/faux-shield-badge-os-logos.svg': No such file or directory
ls: cannot access 'images/faux-shield-badge-os-logos.svg': No such file or directory
ls: cannot access 'images/faux-shield-badge-os-logos.svg': No such file or directory
ls: cannot access 'images/faux-shield-badge-os-logos.svg': No such file or directory
ls: cannot access 'images/faux-shield-badge-os-logos.svg': No such file or directory
ls: cannot access 'images/faux-shield-badge-os-logos.svg': No such file or directory
ls: cannot access 'images/faux-shield-badge-os-logos.svg': No such file or directory
ls: cannot access 'images/faux-shield-badge-os-logos.svg': No such file or directory
ls: cannot access 'images/faux-shield-badge-os-logos.svg': No such file or directory
ls: cannot access 'images/nerd-fonts-logo.png': No such file or directory
ls: cannot access 'images/fontforge-glyph-set-font-linux.png': No such file or directory
ls: cannot access 'images/nerd-fonts-logo.png': No such file or directory
ls: cannot access 'images/fontforge-glyph-set-font-linux.png': No such file or directory
ls: cannot access 'images/faux-shield-badge-os-logos.svg': No such file or directory
```

**Comment by Finii** [comment]
A smarter search...

```
$ grep images/ *.md | sed 's/.*images/images/; s/[")?].*//' | xargs ls -l 2>&1 | grep cannot | sed "s/.* '//;s/'.*//" | sort | uniq
images/faux-shield-badge-os-logos.svg
images/fontforge-glyph-set-font-linux.png
images/nerd-fonts-logo.png
```

set-font-linux is now set-font-logos, but what was this faux-shield-badge? :thinking:

**Comment by kurt-liao** [comment]
Command so smart! I just found that by my eyes when I'm reading the docs, lol.

**Comment by kurt-liao** [comment]
After deep compare the current version of docs, it seems *cn* and *tw* docs are out of date.

Maybe I fix all of them and create a new pr to it.

**Comment by Finii** [comment]
Thank you. I already added a commit along the way.

The faux-badge thing comes from the wiki ... what a website design :grimacing:

**Comment by Finii** [comment]
Well, I can not read the translations :-(

It is always hard to update them, I try to do my best, but over time I guess the text itself gets more and more ridiculous.

Thanks again for reporting and fixing :+1:

**Comment by Finii** [comment]
> After deep comparing the current version of docs, it seems _cn_ and _tw_ docs are out of date.
> 
> Maybe I fix all of them and create a new pr to it.

That would be wonderful!!

**Comment by kurt-liao** [comment]
> Thank you. I already added a commit along the way.
> 
> The faux-badge thing comes from the wiki ... what a website design grimacing

I see. Thanks👍

**Comment by kurt-liao** [comment]
> Well, I can not read the translations :-(
> 
> It is always hard to update them, I try to do my best, but over time I guess the text itself gets more and more ridiculous.
> 
> Thanks again for reporting and fixing +1

Agree! Translation is always the hard part. Obviously, my English isn't good enough😅

I will finish the translation ASAP.

**Comment by Finii** [comment]
@all-contributors please add @kurt-liao for documentation

**Pull request merged**
