### PR TITLE
Add Kotlin icon

### PR DESCRIPTION
**Pull request by jereksel**
#### Description

Add icon for Kotlin programming language: https://kotlinlang.org/

Based on #429

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [ ] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### What does this Pull Request (PR) do?

Add icon for Kotlin programming language

I found this icon in `Brand` section on https://icomoon.io/app/#/select/library.

#### Screenshots (if appropriate or helpful)

`original-source.otf`

image

Font in vim (Hack font)
image

When creating this PR I've realized that this icon is from this GitHub repo:
https://github.com/simple-icons/simple-icons

Here seems to be repo for font generation: https://github.com/simple-icons/simple-icons-font

### CODE REVIEW

**Comment by ryanoasis** [comment]
@jereksel sorry it's taken some time, please feel free to open a fresh PR now that #429 is in

**Comment by diazgilberto** [comment]
@jereksel please reopen the pr.

**Comment by sicr0** [comment]
Has the Kotlin icon been added? I can't find it in the Nerd Fonts Cheatsheet and it doesn't show up in NERDTree

**Comment by ryanoasis** [comment]
@sicr0 It has **not**. This dates back to when PRs had languished on the repo, things have gotten better since. I believe it was waiting for the #429 because of a codepoint conflict. 

Unfortunately the codepoint where Kotlin was added is now taken up by Purescript.

We could re-open this PR and move it though...

**Comment by sicr0** [comment]
@ryanoasis it could be nice to have Kotlin added. Also Prolog is still not added

**Pull request closed without merging**
