### PR TITLE
Add Hasklig

### PR DESCRIPTION
**Pull request by jrolfs**
Perhaps there are more variants than we care about?

Chug-a-lug: 
patching

### CODE REVIEW

**Comment by ryanoasis** [comment]
Good question, it's both a positive of this whole project but also can be a negative :stuck_out_tongue: 

Sorry I haven't followed up on this yet until now.

**Comment by jrolfs** [comment]
No worries, yeah it's definitely both a plus and minus. Git has gotten better with binary files but dumping a bunch more in can definitely bloat the repo...

The problem here is that the source font provides so many variants which could be useful, however we could limit the variants included to something similar to another font that provides variants (like **Source Code Pro** from which this ligature font is derived).

**Comment by ryanoasis** [comment]
Yeah...

> Over 5,700 unique combinations/variations of patched fonts

Is more of a bragging point than something actually feasible/useful in real life :wink: 

--

My thinking on the whole massive amounts of variations issue is that should be addressed but maybe in a few versions (probably 1.0.0) and for now I'd like to move forward with enhancements and easy bugs (to avoid getting stuck on the hard ones). Anyway I am going to put more time into this project again and start preparing for v0.9.0. I'll probably create the branch and merge this in tomorrow :smile: 

Related:
* #58 , in particular removing the "windows" versions is something I want to do and should be feasible (just name length limitations)
* #102, shallow cloning

--

**Comment by ryanoasis** [comment]
whoops I did something wrong in the feature branch flow. the changes for this and commits are there but it's just not marked as 'merged'

**Pull request merged**
