### PR TITLE
Add glyph for fennel

### PR DESCRIPTION
**Pull request by Grazfather**
#### Description

Fennel is a popular lisp-like lang that compiles to Lua. See fennel-lang.org.

The logo is CC-BY-SA 4.0.

Attached is a monochrome svg by @m455 (+thanks to @eccentric-j for converting to monochrome), but I can look into converting it properly using IcoMoon.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What does this Pull Request (PR) do?

Adds a single glyph for the fennel-lang logo

#### How should this be manually tested?

Verify glyph shows up in patched fonts

#### What are the relevant tickets (if any)?
See https://github.com/bakpakin/Fennel/issues/438

### CODE REVIEW

**Comment by Grazfather** [comment]
Is anything else needed on my end, or is it just a waiting game until a bunch of changes are batched up for a new release?

**Comment by Finii** [comment]
/me working hard to get overdue `v3.0.0` ready with all that is already 'in'

**Comment by Grazfather** [comment]
Anything I can do to help get this included in the next release?

**Comment by Finii** [comment]
Thanks for the PR! Sorry for the long wait.

Small problem, overlapping path not handled correctly, fixing...

image

**Comment by Finii** [comment]
Rebase on master, force push.

**Comment by Finii** [comment]
@allcontributors please add @Grazfather for code or design or whatever ;)

**Comment by Grazfather** [comment]
Whoa! Thank you, and sorry for the trouble with the SVG. Thanks for fixing it for me.

**Pull request merged**
