### PR TITLE
I create a Chinese version read me file and I just complete the translation of introduction

### PR DESCRIPTION
**Pull request by hiby90hou**
#### Description

I create a Chinese version read me file and I just complete the translation of introduction.

#### Requirements / Checklist

- [ ] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [ ] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [ ] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [ ] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [ ] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### What does this Pull Request (PR) do?
I create a Chinese version read me file and I just complete the translation of introduction

### CODE REVIEW

**Comment by ryanoasis** [comment]
@hiby90hou Thanks! This looks great so far. :smile: Do you have plans to continue past the introduction?

I can merge either way but wanted to know if your plan was to translate the remaining text or just the "intro"?

**Comment by hiby90hou** [comment]
I will continue to do it.
I think I can at least complete the Font Installation part, but I need some time.

**Comment by ryanoasis** [comment]
@hiby90hou Thanks, I really appreciate it :smile: 

> I need some time.

No worries at all. Take your time, we will merge it when it is ready. Please don't feel like you are under pressure or a timeframe to complete it :smile: . We will merge it when you say you are done.

**Comment by hiby90hou** [comment]
Hi @ryanoasis ,
I just complete my translate,
I wish you like it.

**Comment by ryanoasis** [comment]
@hiby90hou I cannot read it but I love it :heart_eyes: 

Very much appreciate your work :+1: :smile: 

I will be merging soon...

**Pull request merged**
