### PR TITLE
FontAwesome: Reorder some glyphs

### PR DESCRIPTION
**Pull request by Finii**
#### Description

Fixes: https://github.com/ryanoasis/nerd-fonts/pull/1563#issuecomment-2041632343

> Hi, I detected that the glyph nf-fa-circle_thin at \uf1db () now is presented as a filled circle but before it was a thin ring. This exactly glyph is used in powerlevel10k to identify sr.ht git remote, I'm adding it to lazygit with the same purpose, that's how I found the problem.

From @hasecilu 

More details in the comments.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What are the relevant tickets (if any)?

Fixes: #1588 
Fixes: #1593

### CODE REVIEW

**Comment by Finii** [comment]
Thanks for reporting!

I guess the reason is that FA comes now with 3 sets of icons and we select one of the sets for each codepoint (script `remix`), and the super smart algorithm is not clever enough ;-)

Let me quickly check them all (again)

image

image

image

| code | observation | result |
|---|---|---|
| `F000` | not filled | This **is** from `solid`, there is no filled glass anymore |
| `F009`-`F00B` | look inverse | that is the new look |
| `F05C` - `F95D` | check-marks became arrows | Error: These should be from `regular`, where they are not the main codepoints |
| `F0E6` | talk bubble became plane | Error: Icon should have been taken from `regular` |
| `F10A` - `F10B` | now filled | Error: `F10A` -> `F3FA` and `F10B` -> `F3CD` |
| `F14D` | inverse? | is already from `solid`, there is no inverse |
| `F16A` | moved to `F167` on dropping one YT icon | Error: swap `F167` and `F16A` |
| `F172` | inverse bitbucket missing? | They dropped it, now there is the same icon twice in upstream |
| `F1CC` | inverse? | Thats the only jsfiddle they have |
| `F1DB` | now filled | Error: Take from `regular` instead |
| `F20C` | "mp" dropped? | dropped upstream |
| `F219` | not a diamond / gem anymore | Error: use `F3A5` from `regular` |
| `F230` | facebook square missing? | has been dropped |
| `F254` | filled hourglass now unfilled | there is no filled anymore |
| `F262` | what became of the old logo | tripadvisor dropped |
| `F27C` | " | upstream substituted that |
| `F289` | " | " |
| `F29E` | now inverse? | Thats the new audio description |
| `F2AC` | check all snapchat icons | dropped upstream |
| `F2B4` | now not filled | new font awesome logo already from `solid` |
| `F2D8` | inverse | upstream change |
| `F2D9` - `F2DA` | icon change? | upstream change |

## Action plan
* `F05C` - `F95D` from `regular`
* `F0E6` from `regular`
* `F10A` -> `F3FA` and `F10B` -> `F3CD`
* swap `F167` and `F16A`
* `F1DB` from `regular`
* `F219` -> `F3A5`

**Comment by Finii** [comment]
| target | was | shall | comment | commit |
|---|---|---|---|---|
| `F05C` | `F30B` `solid/right-long.svg` | `F05C` `regular/circle-xmark.svg` || 1 |
| `F05D` | `F30C` `solid/up-long.svg` | `F05D` `regular/circle-check.svg` || 1 |
| `F0E6` | `F374` `brands/avianex.svg` | `F0E6` `regular/comments.svg` || 2 |
| `F10A` | `F10A` `solid/tablet-button.svg` | `F3FA` `solid/tablet-screen-button.svg` | use different icon | 
| `F10B` | `F10B` `solid/mobile-button.svg` | `F3CD` `solid/mobile-screen-button.svg` | use different icon | 
| `F167` | `F167` `brands/youtube.svg` | `F384` `brands/cloudsmith.svg` | swapped | 3 |
| `F16A` | `F384` `brands/cloudsmith.svg` | `F167` `brands/youtube.svg` | swapped | 3 |
| `F1DB` | `F1DB` `solid/circle.svg` | `F1DB` `regular/circle.svg` | other set |
| `F219` | `F219` `solid/diamond.svg` | `F3A5` `regular/gem.svg` | | 3 |

**Review by hasecilu — COMMENTED** [review]
Hi, I regenerated the Symbols font with thise changes and seems to be fixed:
image

**Comment by Finii** [comment]
@hasecilu Thanks for having a look! :green_heart: 

This release seems to have less problems than others, still not many problems reported :grimacing:

**Pull request merged**
