### PR TITLE
Update JetBrainsMono to version v2.225

### PR DESCRIPTION
**Pull request by moritzdietz**
#### Description

This PR updates JetBrainsMono to version v2.210. This is a follow up PR for #540 and #518.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [x] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### What does this Pull Request (PR) do?
It updates JetBrainsMono to the latest available version as of yet which is 2.225.
#### How should this be manually tested?
N/A
#### Any background context you can provide?
N/A
#### What are the relevant tickets (if any)?
#540 and #518
#### Screenshots (if appropriate or helpful)
N/A
### Script output:
<details>
<summary>fontforge -script font-patcher src/unpatched-fonts/JetBrainsMono/Ligatures/Regular/JetBrainsMono-Regular.ttf --complete</summary>

```shell
fontforge -script font-patcher src/unpatched-fonts/JetBrainsMono/Ligatures/Regular/JetBrainsMono-Regular.ttf --complete
Copyright (c) 2000-2020. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20190801
 Based on sources from 03:10 UTC  6-Mar-2020-ML-D-GDK3.
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
Adding 54 Glyphs from Seti-UI + Custom Set
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set
╢████████████████████████████████████████╟ 100%
Adding 3 Glyphs from Powerline Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 4 Glyphs from Powerline Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Powerline Extra Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 21 Glyphs from Powerline Extra Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Powerline Extra Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 8 Glyphs from Powerline Extra Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 11 Glyphs from Pomicons Set
╢████████████████████████████████████████╟ 100%
The following table(s) in the font have been ignored by FontForge
  Ignoring 'EPAR'
The glyph named asterisk is mapped to U+F069.
  But its name indicates it should be mapped to U+002A.
The glyph named plus is mapped to U+F067.
  But its name indicates it should be mapped to U+002B.
The glyph named question is mapped to U+F128.
  But its name indicates it should be mapped to U+003F.
The glyph named minus is mapped to U+F068.
  But its name indicates it should be mapped to U+2212.
The glyph named heart is mapped to U+F004.
  But its name indicates it should be mapped to U+2665.
The glyph named home is mapped to U+F015.
  But its name indicates it should be mapped to U+21B8.
The glyph named check is mapped to U+F046.
  But its name indicates it should be mapped to U+2713.
The glyph named bell is mapped to U+F0A2.
  But its name indicates it should be mapped to U+2407.
The glyph named lessequal is mapped to U+F500.
  But its name indicates it should be mapped to U+2264.
The glyph named circle is mapped to U+F111.
  But its name indicates it should be mapped to U+25CB.
The glyph named smile is mapped to U+F118.
  But its name indicates it should be mapped to U+263A.
The glyph named frown is mapped to U+F119.
  But its name indicates it should be mapped to U+2322.
The glyph named bullseye is mapped to U+F140.
  But its name indicates it should be mapped to U+25CE.
The glyph named compass is mapped to U+F14E.
  But its name indicates it should be mapped to U+263C.
The glyph named female is mapped to U+F182.
  But its name indicates it should be mapped to U+2640.
The glyph named male is mapped to U+F183.
  But its name indicates it should be mapped to U+2642.
The glyph named sun is mapped to U+F185.
  But its name indicates it should be mapped to U+263C.
The glyph named venus is mapped to U+F221.
  But its name indicates it should be mapped to U+2640.
Adding 679 Glyphs from Font Awesome Set
╢████████████████████████████████████████╟ 100%
The glyph named slash is mapped to U+E016.
  But its name indicates it should be mapped to U+002F.
The glyph named pi is mapped to U+E02C.
  But its name indicates it should be mapped to U+03C0.
The glyph named ring is mapped to U+E03D.
  But its name indicates it should be mapped to U+02DA.
The glyph named infinity is mapped to U+E055.
  But its name indicates it should be mapped to U+221E.
The glyph named equal is mapped to U+E079.
  But its name indicates it should be mapped to U+003D.
Adding 170 Glyphs from Font Awesome Extension Set
╢████████████████████████████████████████╟ 100%
Adding 4 Glyphs from Power Symbols Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Power Symbols Set
╢████████████████████████████████████████╟ 100%
The PostScript font name "Material Design Icons" is invalid.
It should be printable ASCII,
must not contain (){}[]<>%/ or space
and must be shorter than 63 characters
The PostScript font name "Material Design Icons" is invalid.
It should be printable ASCII,
must not contain (){}[]<>%/ or space
and must be shorter than 63 characters
The glyph named alpha is mapped to U+F02B.
  But its name indicates it should be mapped to U+03B1.
The glyph named at is mapped to U+F065.
  But its name indicates it should be mapped to U+0040.
The glyph named backspace is mapped to U+F06E.
  But its name indicates it should be mapped to U+2408.
The glyph named bell is mapped to U+F09A.
  But its name indicates it should be mapped to U+2407.
The glyph named beta is mapped to U+F0A1.
  But its name indicates it should be mapped to U+03B2.
The glyph named box is mapped to U+F0D4.
  But its name indicates it should be mapped to U+25A1.
The glyph named check is mapped to U+F12C.
  But its name indicates it should be mapped to U+2713.
The glyph named compass is mapped to U+F18B.
  But its name indicates it should be mapped to U+263C.
The glyph named delete is mapped to U+F1C0.
  But its name indicates it should be mapped to U+2421.
The glyph named delta is mapped to U+F1C2.
  But its name indicates it should be mapped to U+03B4.
The glyph named diamond is mapped to U+F1C8.
  But its name indicates it should be mapped to U+2666.
The glyph named earth is mapped to U+F1E7.
  But its name indicates it should be mapped to U+2641.
The glyph named equal is mapped to U+F1FC.
  But its name indicates it should be mapped to U+003D.
The glyph named heart is mapped to U+F2D1.
  But its name indicates it should be mapped to U+2665.
The glyph named home is mapped to U+F2DC.
  But its name indicates it should be mapped to U+21B8.
The glyph named image is mapped to U+F2E9.
  But its name indicates it should be mapped to U+22B7.
The glyph named minus is mapped to U+F374.
  But its name indicates it should be mapped to U+2212.
The glyph named omega is mapped to U+F3C9.
  But its name indicates it should be mapped to U+03C9.
The glyph named percent is mapped to U+F3F0.
  But its name indicates it should be mapped to U+0025.
The glyph named pi is mapped to U+F3FF.
  But its name indicates it should be mapped to U+03C0.
The glyph named plus is mapped to U+F415.
  But its name indicates it should be mapped to U+002B.
The glyph named sigma is mapped to U+F4A0.
  But its name indicates it should be mapped to U+03C3.
The glyph named tie is mapped to U+F519.
  But its name indicates it should be mapped to U+2040.
The glyph named triangle is mapped to U+F536.
  But its name indicates it should be mapped to U+25B3.
The glyph named bullseye is mapped to U+F5DD.
  But its name indicates it should be mapped to U+25CE.
The glyph named copyright is mapped to U+F5E6.
  But its name indicates it should be mapped to U+00A9.
The glyph named lambda is mapped to U+F627.
  But its name indicates it should be mapped to U+03BB.
The glyph named gradient is mapped to U+F69F.
  But its name indicates it should be mapped to U+2207.
The glyph named asterisk is mapped to U+F6C3.
  But its name indicates it should be mapped to U+002A.
The glyph named hook is mapped to U+F6E1.
  But its name indicates it should be mapped to U+2440.
The glyph named infinity is mapped to U+F6E3.
  But its name indicates it should be mapped to U+221E.
The glyph named prescription is mapped to U+F705.
  But its name indicates it should be mapped to U+211E.
The glyph named tilde is mapped to U+F724.
  But its name indicates it should be mapped to U+02DC.
The glyph named cancel is mapped to U+F739.
  But its name indicates it should be mapped to U+2418.
The glyph named square is mapped to U+F763.
  But its name indicates it should be mapped to U+25A1.
The glyph named circle is mapped to U+F764.
  But its name indicates it should be mapped to U+25CB.
The glyph named null is mapped to U+F7E1.
  But its name indicates it should be mapped to U+2400.
The glyph named pipe is mapped to U+F7E4.
  But its name indicates it should be mapped to U+01C0.
The glyph named ring is mapped to U+F7EA.
  But its name indicates it should be mapped to U+02DA.
Adding 2119 Glyphs from Material Set
╢████████████████████████████████████████╟ 100%
The following table(s) in the font have been ignored by FontForge
  Ignoring 'webf'
Adding 228 Glyphs from Weather Icons Set
╢████████████████████████████████████████╟ 100%
Adding 29 Glyphs from Font Logos (Font Linux) Set
╢████████████████████████████████████████╟ 100%
The glyph named question is mapped to U+F02C.
  But its name indicates it should be mapped to U+003F.
The glyph named check is mapped to U+F03A.
  But its name indicates it should be mapped to U+2713.
The glyph named plus is mapped to U+F05D.
  But its name indicates it should be mapped to U+002B.
The glyph named x is mapped to U+F081.
  But its name indicates it should be mapped to U+0078.
The glyph named home is mapped to U+F08D.
  But its name indicates it should be mapped to U+21B8.
The glyph named ellipsis is mapped to U+F09A.
  But its name indicates it should be mapped to U+2026.
The glyph named bell is mapped to U+F0DE.
  But its name indicates it should be mapped to U+2407.
Adding 169 Glyphs from Octicons Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Octicons Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Octicons Set
╢████████████████████████████████████████╟ 100%
Adding 1 Glyphs from Octicons Set
╢████████████████████████████████████████╟ 100%

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontComplete-Regular
```
</details>
<details>
<summary>./gotta-patch-em-all-font-patcher\!.sh JetBrainsMono</summary>
  
```shell
./gotta-patch-em-all-font-patcher\!.sh JetBrainsMono
# [Nerd Fonts]  Parameter given, limiting search and patch to pattern 'JetBrainsMono' given
# [Nerd Fonts]  Total source fonts found: 28
# [Nerd Fonts]  Complete Variation Count after max parallel process is  0

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontComplete-Bold Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Bold Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFo-Bold Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFo-Bold Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-Regular

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-ExtraBold

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontComplete-Italic

Generated: JetBrainsMonoNerdFontComplete-Bold

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-Italic

Generated: JetBrainsMonoNLNerdFontComplete-Light

Generated: JetBrainsMonoNerdFontComplete-Regular

Generated: JetBrainsMonoNerdFontComplete-Medium

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-Thin

Generated: JetBrainsMonoNLNerdFontComplete-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontComplete-ExtraLight

Generated: JetBrainsMonoNerdFontComplete-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-Italic

Generated: JetBrainsMonoNLNerdFontComplete-Medium

Generated: JetBrainsMonoNLNerdFontComplete-Bold Italic

Generated: JetBrainsMonoNLNerdFontComplete-Italic

Generated: JetBrainsMonoNLNerdFontComplete-Italic

Generated: JetBrainsMonoNLNerdFontComplete-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontComplete-Bold

Generated: JetBrainsMonoNLNerdFontComplete-ExtraLight

Generated: JetBrainsMonoNerdFontComplete-Thin

Done with Patch Sets, generating font...
Done with Patch Sets, generating font...


Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontComplete-Light

Generated: JetBrainsMonoNerdFontComplete-Italic
Generated: JetBrainsMonoNerdFontComplete-ExtraBold


Generated: JetBrainsMonoNerdFontComplete-Italic

Generated: JetBrainsMonoNerdFontComplete-Italic

Generated: JetBrainsMonoNerdFontComplete-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Regular

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-ExtraBold

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Light

Generated: JetBrainsMonoNLNerdFontCompleteM-Italic

Generated: JetBrainsMonoNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Bold

Generated: JetBrainsMonoNerdFontCompleteM-Regular

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Medium

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Thin

Generated: JetBrainsMonoNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-ExtraLight

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Light

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Bold Italic

Generated: JetBrainsMonoNLNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Italic

Generated: JetBrainsMonoNLNerdFontCompleteM-Medium

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-ExtraLight

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCompleteM-Bold

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Thin

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-Italic

Generated: JetBrainsMonoNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompleteM-ExtraBold

Generated: JetBrainsMonoNerdFontCompleteM-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFont-Regular

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFo-ExtraBold

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCo-Light

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCo-Regular

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompl-Bold

Generated: JetBrainsMonoNLNerdFontC-Italic

Generated: JetBrainsMonoNLNerdFontCom-Thin

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Medium

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFon-ExtraLight

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontComp-Light

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Generated: JetBrainsMonoNLNerd-Bold Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Generated: JetBrainsMonoNLNerdFontC-Medium

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdF-ExtraLight

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCom-Bold

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompl-Thin

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Generated: JetBrainsMonoNerdFont-ExtraBold

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFont-Regular

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFo-ExtraBold

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCo-Light

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCom-Thin

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompl-Bold

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Medium

Generated: JetBrainsMonoNerdFontCo-Regular

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Generated: JetBrainsMonoNerdFon-ExtraLight

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Generated: JetBrainsMonoNerdFontComp-Light

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerd-Bold Italic

Done with Patch Sets, generating font...

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontC-Medium

Generated: JetBrainsMonoNLNerdFontC-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdF-ExtraLight

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNLNerdFontCom-Bold

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCompl-Thin

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFont-ExtraBold

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic

Done with Patch Sets, generating font...

Generated: JetBrainsMonoNerdFontCom-Italic
# [Nerd Fonts]  Generating info for 'JetBrainsMono-BoldItalic.ttf':
# [Nerd Fonts]  * Re-generate parent directory readme
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-ThinItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-LightItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-Regular.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-ExtraBoldItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-Bold.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-Light.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-MediumItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-Medium.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-ExtraLight.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-ExtraLightItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-ExtraBold.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-Italic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMono-Thin.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-BoldItalic.ttf':
# [Nerd Fonts]  * Re-generate parent directory readme
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-ThinItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-LightItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-Regular.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-ExtraBoldItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-Bold.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-Light.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-MediumItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-Medium.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-ExtraLight.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-ExtraLightItalic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-ExtraBold.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-Italic.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Generating info for 'JetBrainsMonoNL-Thin.ttf':
# [Nerd Fonts]  * Adding 'Possible Combinations' section
# [Nerd Fonts]  * Copying license files
# [Nerd Fonts]  Total runtime: 0:00:13:28
# All fonts patched to sub-directories in                       'patched-fonts'
# The total number of font typefaces patched was                '51'
# The total number of font families patched was                 '28'
# The total number of 'complete' patched fonts created was      '112'
# The total number of 'variation' patched fonts created was     '114632'
# The total number of patched fonts created was                 '114744'
```

### CODE REVIEW

**Comment by aaccioly** [comment]
Hi guys, any update on this one?

**Comment by FlorianFranzen** [comment]
It seems patching the font breaks the alignment of the already included powerline symbols. Maybe we could tell the patcher not to overwrite those.

**Comment by moritzdietz** [comment]
> It seems patching the font breaks the alignment of the already included powerline symbols. Maybe we could tell the patcher not to overwrite those.

Yup, that been going on for some time now and I mentioned it a couple times.
As well that I don't know how to move forward to fixing that.
I would but would need a bit of guidance / pointers first.

I'll even fix the outstanding / older PRs for JetBrains Mono.

I presume that this problem occurs in other fonts as well?

**Comment by ryanoasis** [comment]
I'm going ahead and merging things. We can create issues for anything in particular 😄

**Pull request merged**
