### PR TITLE
Remake the original-source font file

### PR DESCRIPTION
**Pull request by danbee**
#### Description

I sourced a bunch of replacement SVG's for this font because many of the originals were a little rough looking. There were also many glyphs that were made up of multiple overlapping/intersecting shapes so I spent some time reducing these down to a single path each. I also made a few changes to some of the icons to improve clarity.

I used IcoMoon to put together the font, and then converted it to OTF using FontForge. I used Glyphs to clean up the paths as FontForge seemed to be having trouble doing that.

I have been unable to rebuild the fonts on my Mac to check. I managed to run the script (`./gotta-patch-em-all-font-patcher\!.sh`) but I don't get any font files in the `patched-fonts` directory. The script did not output any errors 😕.

#### Any background context you can provide?

The last three icons in the font didn't seem to be rendering. The icons are blank on the web interface when you search for `custom`. My original intention was to add the Elixir icon, but I found it was already there, just not working correctly. I believe it was broken due to the problems with the glyphs.

#### Screenshots (if appropriate or helpful)

screen shot 2018-03-25 at 18 40 58

### CODE REVIEW

**Comment by ryanoasis** [comment]
@danbee This is great thanks!

> I sourced a bunch of replacement SVG's for this font because many of the originals were a little rough looking.

Were they the elixir, gulp, and the go ones? Or quite a few more than that? Those are the ones I noticed right away. 

> There were also many glyphs that were made up of multiple overlapping/intersecting shapes so I spent some time reducing these down to a single path each

Were these mostly the folder glyphs with the logo on top (I created these in FontForge by combining already existing ones :blush:)? Or do you remember which?

> I have been unable to rebuild the fonts on my Mac to check. I managed to run the script (./gotta-patch-em-all-font-patcher\!.sh) but I don't get any font files in the patched-fonts directory. The script did not output any errors confused.

Hmm can you paste the output or screenshot? I am assuming you are passing 1 argument so that it limits to a specific font family?

```
./gotta-patch-em-all-font-patcher\!.sh Source
```

You can also specify a specific output directory to check, for example here is what I was doing just a few minutes ago to rebuild the 'symbol only' versions:

```
./font-patcher -ext ttf -out ./src/glyphs/ --complete ./src/glyphs/Symbols\ Template\ 2048\ em.ttf
```

> The last three icons in the font didn't seem to be rendering. The icons are blank on the web interface when you search for custom. My original intention was to add the Elixir icon, but I found it was already there, just not working correctly. I believe it was broken due to the problems with the glyphs.

Hmmm they seem to be showing for me, can you give a screenshot here ? Thanks.

**Comment by danbee** [comment]
> Were they the elixir, gulp, and the go ones? Or quite a few more than that? Those are the ones I noticed right away.

I sourced new SVG's for: sass, rails, python, heroku, handlebars, gulp, grunt, npm, bower, coffeescript, lua, react, go, elm, elixir, and atom.

> Were these mostly the folder glyphs with the logo on top (I created these in FontForge by combining already existing ones 😊)? Or do you remember which?

The NPM folder was definitely one offender! The others were elixir, twig and the C/C++ icons.

> Hmm can you paste the output or screenshot? I am assuming you are passing 1 argument so that it limits to a specific font family?

I was running it without an argument so it was trying to build all the fonts. Here's the output if I limit it to `Source`:

```sh
$ ./gotta-patch-em-all-font-patcher\!.sh Source
# [Nerd Fonts]  Parameter given, limiting search and patch to pattern 'Source' given
# [Nerd Fonts]  Total source fonts found: 13
# [Nerd Fonts]  Complete Variation Count after max parallel process is  0
# [Nerd Fonts]  Generating info for 'SourceCodePro-Semibold.ttf'
# [Nerd Fonts]  Re-generate parent directory readme
# [Nerd Fonts]  Adding 'Possible Combinations' section
# [Nerd Fonts]  Generating info for 'SourceCodePro-LightIt.ttf'
# [Nerd Fonts]  Adding 'Possible Combinations' section
# [Nerd Fonts]  Generating info for 'SourceCodePro-ExtraLight.ttf'
# [Nerd Fonts]  Adding 'Possible Combinations' section
# [Nerd Fonts]  Generating info for 'SourceCodePro-SemiboldIt.ttf'
# [Nerd Fonts]  Adding 'Possible Combinations' section
# [Nerd Fonts]  Generating info for 'SourceCodePro-BoldIt.ttf'
# [Nerd Fonts]  Adding 'Possible Combinations' section
# [Nerd Fonts]  Generating info for 'SourceCodePro-Medium.ttf'
# [Nerd Fonts]  Adding 'Possible Combinations' section
# [Nerd Fonts]  Generating info for 'SourceCodePro-MediumIt.ttf'
# [Nerd Fonts]  Adding 'Possible Combinations' section
# [Nerd Fonts]  Generating info for 'SourceCodePro-Bold.ttf'
# [Nerd Fonts]  Adding 'Possible Combinations' section
# [Nerd Fonts]  Generating info for 'SourceCodePro-Light.ttf'
# [Nerd Fonts]  Adding 'Possible Combinations' section
# [Nerd Fonts]  Generating info for 'SourceCodePro-ExtraLightIt.ttf'
# [Nerd Fonts]  Adding 'Possible Combinations' section
# [Nerd Fonts]  Generating info for 'SourceCodePro-Regular.ttf'
# [Nerd Fonts]  Adding 'Possible Combinations' section
# [Nerd Fonts]  Generating info for 'SourceCodePro-Black.ttf'
# [Nerd Fonts]  Adding 'Possible Combinations' section
# [Nerd Fonts]  Generating info for 'SourceCodePro-BlackIt.ttf'
# [Nerd Fonts]  Adding 'Possible Combinations' section
# [Nerd Fonts]  Total runtime: 0:00:00:02
# All fonts patched to sub-directories in 			'patched-fonts'
# The total number of font typefaces patched was 		'      43'
# The total number of font families patched was 		'13'
# The total number of 'complete' patched fonts created was 	'52'
# The total number of 'variation' patched fonts created was 	'26598'
# The total number of patched fonts created was 		'26650'
```

I'll try just running `./font-patcher` on its own like you suggest. I should be able to find time to dig into this more later this week.

> Hmmm they seem to be showing for me, can you give a screenshot here ? Thanks.

This is what it looks like in Safari:

screen shot 2018-03-26 at 22 58 26

I tried with Firefox also and the icons do show up there. The Elixir one looks a mess, however, due to all the overlapping shapes.

screen shot 2018-03-26 at 22 59 42

**Comment by danbee** [comment]
Running that `font-patcher` command gives me the following output:

```sh
$ ./font-patcher -ext ttf -out ./src/glyphs/ --complete ./src/glyphs/Symbols\ Template\ 2048\ em.ttf
Nerd Fonts: FontForge module is probably not installed. [See: http://designwithfontforge.com/en-US/Installing_Fontforge.html]
```

FontForge is installed (although this is a symlink to the binary in the Mac application package):

```sh
$ which fontforge
/usr/local/bin/fontforge
```

**Comment by ryanoasis** [comment]
Hmm seems like you might be missing the bindings for the command line part. Either missing fontforge python module and/or the psMat one.

Of relevance to you:

> FontForge implements two python modules – one great huge one called fontforge which provides access to as much of FontForge’s functionality as I’ve had time to write, and one tiny one called psMat which provides quick access to some useful transformations expressed as PostScript matrices.

source: http://fontforge.github.io/en-US/documentation/scripting/python/

I think our error message here points to at least psMat missing. The error message should be updated...

We have installation instructions for Linux only at the moment: https://github.com/ryanoasis/nerd-fonts/wiki/Contributor-Developer-Setup#linux

Sorry I am not sure what the exact equivalent on macOS would be here

**Comment by danbee** [comment]
@ryanoasis Yes, I think you're right. I haven't found a way to install them in macOS yet so I'm trying in a Debian VM. I'll let you know how I get on!

**Comment by ryanoasis** [comment]
@danbee I see. Let us know how it goes or if you need any help! :smile: 

By the way I'd like to keep this guy/gal :wink:

little go

I have an `eps` file of it if you want, let me know if you want to check the paths

found in the latest seti UI icons that vscode uses and I think is easier to distinguish at smaller font sizes than the other go glyphs)

**Comment by danbee** [comment]
@ryanoasis Oh yeah, throw me the EPS file and I'll incorporate it, just let me know which glyph to replace. I'm hoping to find some more time to figure out my build issues this weekend.

**Comment by ryanoasis** [comment]
@danbee Here is the eps file I used for that Go glyph, you can use as is or optimize the paths as you see fit. Or find one that is similar is also okay.


[go_seti.eps.zip](https://github.com/ryanoasis/nerd-fonts/files/1866342/go_seti.eps.zip)

**Comment by danbee** [comment]
@ryanoasis New version of the font with the new Go glyph.

screen shot 2018-04-03 at 21 16 03

**Comment by ryanoasis** [comment]
@danbee Thanks. I'll try to check it out this weekend. :+1: 

I think this will be a quick merge but after that I'll have to repatch all of the fonts :laughing: . I might see what other items can be tackled before that step.

**Comment by ryanoasis** [comment]
@danbee hey, no sorry I haven't yet. I really was planning to and it even crossed my mind last weekend. I won't make any promises at this point but I'll look at it soon. Maybe this week :smile:

**Pull request merged**
