### PR TITLE
Update Font Logos to 1.1.1

### PR DESCRIPTION
**Pull request by hasecilu**
#### Description

- Update `font-logos.ttf` file to version 1.1.1
- Update upper limit range on `font-patcher` script
- Update `i_logos.sh` lib file

#### Requirements / Checklist

- [X] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [X] Verified the license of any newly added font, glyph, or glyph set

#### What does this Pull Request (PR) do?
Update Font Logos to 1.1.1
#### How should this be manually tested?
Check md5sum (ecc30c6fd3d35c8e9e2789b3d01ff36a) is the same to the one on release 1.1.1 and include it to SymbolsNerdFont.
#### Any background context you can provide?
After a little pause the `font-logos` project has been updated
#### What are the relevant tickets (if any)?
#1424 
#### Screenshots (if appropriate or helpful)
The new logos goes from `f330` to `f372`
image
Banner
header

### CODE REVIEW

**Comment by Finii** [comment]
Waaah @hasecilu :green_heart: 

Thank you so much!

**Comment by Finii** [comment]
What is this? :unamused: 

image

WHAT?

image

Anyhow, not my (ancient Nerd Font) font :relieved: 

How did you update the `i_*.sh` is there a script (just curiousity).

We also need to update the Wiki. https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points

**Comment by hasecilu** [comment]
> How did you update the `i_*.sh` is there a script (just curiousity).

I used:
```shell
from=F330
to=F372
from=$(printf '%d' "0x$from") to=$(printf '%d' "0x$to")
while test "$from" -le "$to"; do
        num=$(printf '%04x' "$from")
        echo -en "i='\u$num' i_linux_=\$i\n"
        from=$((from + 1))
done
```
Then I tried to do a visual copy with the names on `icons.tsv` file with Neovim but since the `\n` chars were copied I had to manually type the names -__-

> We also need to update the Wiki. https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points

Well, I don't have permissions in the wiki, so I leave that for your todo list.

**Comment by Finii** [comment]
Thank you.

Ah, I thought everyone can edit.
Unfortunately I have no rights to grant any rights. I have barely enough rights to keep this live :grimacing: 

And then ... when your workflows break apart for no obvious reasons...
I guess today the whole day will be release work :-/

image

The workflow, when it runs through, takes some hours (3..4?)

**Comment by Finii** [comment]
Ah, release workflow now running

https://github.com/ryanoasis/nerd-fonts/actions/runs/6940642493

Hoping for a smooth ride...

image

**Comment by Finii** [comment]
Wiki updated.

**Comment by Finii** [comment]
Something changed.... It's almost ready and only one hour?

And always NOTO, how I do hate NOTO

image

**Comment by Finii** [comment]
OH NO!!!!

Just noticed that I called `Monaspace Radon` -> `Monaspice Rd` which should have been `Rn` :unamused: 

I guess I will correct that manually afterwards. There is always something.

**Comment by hasecilu** [comment]
Cool!, new version is out.

Is the **Diagram created using [@SankeyMATIC](http://sankeymatic.com/)** automagically updated or manually? Now there are 115 logos 😎

**Comment by Finii** [comment]
There are instructions in the readme

https://github.com/ryanoasis/nerd-fonts/tree/master/bin/scripts/data/sankey

But with such a small change I would rather just edit the svg and sneak in the 'wrong' (=new) number :-D

This is not hard in `inkscape` and I did it before for 3.0.2 iirc.

Also the Seti+Custom number of icons increased by ... 3 or so.

**Comment by Finii** [comment]
Addendum:

I would not recommend creating a completely new diagram, because there are several manual steps involved, change font size, put the icon visual left and right etc pp. That really takes time. Editing the svg is ... ready in 5 Minutes.

**Comment by Finii** [comment]
This is the source of all images: https://github.com/ryanoasis/nerd-fonts/blob/master/bin/scripts/data/sankey/sankey-glyphs-3.0.0.svgz, change that, export as png and optimized svg, save the new version also here as full-inkspace-compressed svg with version in the filename.

**Comment by Finii** [comment]
Sankey diagram updated.

**Comment by hasecilu** [comment]
Thanks!, I was about to start on that, just a minor detail: the white background doesn't "fills" the whole text string, it's a little short
image

**Pull request merged**
