### PR TITLE
Add icons for Emacs and Orgmode

### LINKED ISSUE #342: [Request] icons for Emacs, elisp and orgmode
#### 🎯 Subject of the issue

It will be great for Emacs user.

- https://www.gnu.org/software/emacs/
- https://en.wikipedia.org/wiki/Emacs_Lisp
- https://orgmode.org

Some icons:

- https://commons.wikimedia.org/wiki/File:EmacsIcon.svg
- https://www.emacswiki.org/emacs/EmacsIcons

### PR DESCRIPTION
**Pull request by ashfinal**
#### Description

Add icons for Emacs and Orgmode.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What does this Pull Request (PR) do?

I used Inkscape to edit the SVG files, then imported them into Fontforge. In the meanwhile, I uploaded the SVG files to [IcoMoon](https://icomoon.io/app) to see if they triggered any warnings. And add them to `original-source.otf` as `e532` and `e533`. Also, I update `font-patcher` to include new icons in patched fonts.

#### What are the relevant tickets (if any)?

Closes #342 

Similar PR #429 

#### Screenshots (if appropriate or helpful)

Changes in `original-source.otf`

fontforge

Patched font:

kfontview

Nvim with patched font:

nvim_devicons

Let me know if I miss something.
Thanks!

### CODE REVIEW

**Comment by Finii** [comment]
_Technical remark:_

@ryanoasis I do not see how the `src/svgs/` are converted to the `original-source` font. Is that really manual? Should maybe automated with for example [`font-custom`](https://github.com/FontCustom/fontcustom/) and a fixed-codepoint configuration.

Additionally there is at least one glyph in `original-source` that is not in `src/svgs/`, origin unclear:

image

On the other hand `src/svgs/go.svg` is not included.

_P.S. Oh man is font-custom old_ :->

**Comment by Finii** [comment]
I think the orgmode svg is needlessly detailed (and thus big in file size). Maybe it can be simplified?

See also https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#3-optimize-the-icon

Just a gut feeling.

**Comment by Finii** [comment]
Ah, and ... thanks for the contrib :-)

**Comment by ashfinal** [comment]
Good idea! I managed to reduce the size of orgmode using SVGO. (from 16.2 KiB to 5.5 KiB) Also I updated `original-source.otf`.

Let me know if I miss something. :)

**Comment by ashfinal** [comment]
:smile_cat:  I actually optimized SVGs before filing this PR. But there is a `--precision` argument I overlooked. Obviously orgmode svg could be smaller. As for emacs svg, I don't see much sense in this.

> how the `src/svgs/` are converted to the `original-source` font. Is that really manual?

I think that's manual. `src/svgs` is not much important, as you can easily export svgs from Fontforge. IMO, [IcoMoon](https://icomoon.io/app) acts like some kind of QC measure in case your svgs are too complicated to be understood by IcoMoon. But I'm new to this project, I may be wrong. :smiley:

**Comment by Finii** [comment]
> > how the `src/svgs/` are converted to the `original-source` font. Is that really manual?
> 
> I think that's manual. `src/svgs` is not much important, as you can easily export svgs from Fontforge

It's the other way around. This repo should aim to assemble all its parts from the basic building blocks (in this case the `svg`s.).
Any manual steps are a burden and should be replaced by CI jobs. That was just a nudge for Ryan ;)

**Comment by iris-garcia** [comment]
Any update here?

**Comment by tecosaur** [comment]
Any reason why you didn't go for a simplified version of the Org logo? E.g.

org-mode-simplister

**Comment by Finii** [comment]
> Any reason why you didn't go for

Who is 'you'? :-)

I dont even know what orgmode is. 
Answer is: Noone suggested that. 
What do orgmode users prefer/expect?

**Comment by tecosaur** [comment]
> Who is 'you'? :-)

You = the author of the PR.

The merged version is the full-detail outline, but as I think of nerd-font being used at smaller sizes I wonder if a simplified form would be more appropriate. When re-doing the website (https://orgmode.org) last year, I created a range of detail levels of the logo. The reduced-detail version I shared above is now used in the file-icons package as of https://github.com/file-icons/icons/pull/88.

**Comment by tecosaur** [comment]
Cool. If you do whip up a PR from this, you'll probably be most interested in file-icons' optimised path version: https://raw.githubusercontent.com/file-icons/icons/master/svg/Org-Mode.svg.

**Pull request merged**
