### PR TITLE
Update FiraCode to v3.1

### PR DESCRIPTION
**Pull request by iamolivinius**
#### Description

_Please explain the changes you made here._

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [ ] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### What does this Pull Request (PR) do?

This PR adds patched and unpatched FiraCode v.3.1 files to the repository

#### How should this be manually tested?

1. Install Fira Code Regular Nerd Font Complete
2. Configure your editor or terminal of choice to use `FiraCode Nerd Font`
3. Enable ligatures if possible
4. Check if you can see the adjusted combinations in your editor or terminal as they are shown here: https://github.com/tonsky/FiraCode#whats-in-the-box

### CODE REVIEW

**Comment by dein0s** [comment]
as a follow up on this - FiraCode author released [v4](https://github.com/tonsky/FiraCode/releases/tag/4) yesterday with some noticeable changes
maybe consider switching to it instead of v3.1?

**Comment by felipecassiors** [comment]
Actually, it's currently on [v5.2](https://github.com/tonsky/FiraCode/releases/tag/5.2).

**Comment by gitfool** [comment]
FWIW, I wanted to learn more about how nerd fonts worked so I created PR #497 with the latest version.

**Comment by ryanoasis** [comment]
My bad this should've gotten merged in long ago. I'll probably work to get this in and then merge #497 so both will get counted

**Pull request merged**
