### PR TITLE
fix: rename issue form files for consistency

### PR DESCRIPTION
**Pull request by gu5e**
#### Description

This PR renames the issue form files to use `-` instead of `_`. Sorry for not remembering this in #1667

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [ ] I've discussed this with core contributors already. If not checked, I'm ready to accept this work might be rejected in favor of a different grand plan.
      Issue number where discussion took place: #xxx
- [x] If this contains a font/glyph add its origin as background info below (e.g. URL)
- [x] Verified the license of any newly added font, glyph, or glyph set. License is: xxx

#### What does this Pull Request (PR) do?
It renames the issue form files to match GitHub **issue form yaml file** naming conventions.

#### How should this be manually tested?
If you have functional eyes, you can look at the filenames of the issue forms.

#### Any background context you can provide?
Nope.

### CODE REVIEW

**Comment by Finii** [comment]
> to match GitHub naming conventions

The only 'convention' I could find was this:

image

And `ISSUE_TEMPLATE/FORM-NAME.yml` (with underscore in the path and dash in the file name) is far from consistent in my eyes?

image

Maybe you have a link to the naming convention?

**Comment by gu5e** [comment]
Unfortunately i don't, but there's not documentation referencing that you should name the file with underscores.

**Comment by gu5e** [comment]
And you're also naming your github actions with dashes

**Comment by Finii** [comment]
Here the history of how we came to the current names (via #782)

image

and they still say underscore is the thing ;-)

image

**Comment by gu5e** [comment]
But you are already using dashes for the workflow file names

**Comment by Finii** [comment]
Some examples for repos I work with

image

image

And this

image

I just checked these 3, so I guess underscore is ok ;)

**Comment by Finii** [comment]
> But you are already using dashes for the workflow file names

I have no clue why, but that tends to be what people do.
The same 3 repos:

image


image
_Azure of course for Microsoft_

image

**Comment by gu5e** [comment]
Okay, i actually didn't know that, gonna close it. Thanks!

**Comment by Finii** [comment]
Thank you for caring for the details like filenames :+1:

**Pull request closed without merging**
