### PR TITLE
doc: Correct name for AnonymicePro Nerd Font

### PR DESCRIPTION
**Pull request by kingarrrt**
#### Description

The AnonymicePro Nerd Font is incorrectly named Anonymice Nerd Font.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [ ] Verified the license of any newly added font, glyph, or glyph set

### CODE REVIEW

**Comment by Finii** [comment]
Good catch!

Thanks for the PR!

Hmm, I see more strangenesses...:

image

Some have `Nerd Font` in the listed name, and some dont. :thinking: 

Also checked `fonts.json`, but there AnonymicePro is correct.

**Comment by Finii** [comment]
@allcontributors please add @kingarrrt for doc

**Comment by Finii** [comment]
Maybe you like to comment on this...:

image

I would drop the Win-Linux-Mac indicators, the table would get vertically condensed - and the indicators are defunct anyhow.

Then we should unify the naming, add - or remove - the `Nerd Font` part from the patched font names (column 1)?

The column names (column 1 and 2) are also rather ... similar `Font Name` and `Font Name and Repo`...
Maybe change first column header to `Patched Font Name`?

**Comment by kingarrrt** [comment]
Yes re defunct Win-Linux-Mac indicators.

It looks like the Patched Fonts table could be generated from `fonts.json`  and the fonts' `README.md` files to ensure correctness.

**Comment by Finii** [comment]
> could be generated from `fonts.json`

**Excellent** idea! :+1:

(Except at least ProFont which has more than one entry in the table because of different versions. Hmm, I seem to remember that there are other fonts also with a variety of versions. But that is just a detail.)

I would even put the version information into `fonts.json`. We could reuse that information for nerdfonts.com then.

Are you interested in implementing something? Otherwise I would code something up.

**Comment by kingarrrt** [comment]
Very sorry, I don't have bandwidth to implement.

**Pull request merged**
