### PR TITLE
feat: use standard Docker build Actions, enable builds for ARM architecture

### PR DESCRIPTION
**Pull request by sammcj**
#### Description

Refactor docker-release (aka build and push) workflow to use the standard Docker Github Actions.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What does this Pull Request (PR) do?

This adds the following features:

- Builds for both AMD64 and ARM64 (other architectures can be enabled if required).
- Automatic tagging and labelling (including 'latest').

#### How should this be manually tested?

- I don't have access to _your_ Docker hub credentials so wasn't able to test I could publish as your user, just check it does successfully publish with your creds the first time (but it should be fine!).

#### Any background context you can provide?

I went to run the nerd-fonts patcher and found the provided container image was only built for  AMD64, many modern computers are ARM64 hence this PR.

https://github.com/marketplace/actions/build-and-push-docker-images

### CODE REVIEW

**Review by Finii — APPROVED** [review]
Thank you for this nice PR.

First I had a deja vu feeling, but that was https://github.com/ryanoasis/nerd-fonts/pull/882#issuecomment-1226377309

I will just pull as is, and see if the docker is still working on my machine (i.e. amd64).

**Comment by Finii** [comment]
Had a small problem that `meta` tags it as `master` but we always tagged as `latest`.
Solved with 1322285f3fb45080d3a0620a8494ab0744b2a37d

Tried patching with the docker on `amd64` and it works.

@sammcj Can you confirm `arm64` please?

(Interestingly the image size did not really increase.)

**Comment by Finii** [comment]
Hmm, looking [here](https://hub.docker.com/r/nerdfonts/patcher/tags), I see only `amd64` and no `arm64` ?

@sammcj Any ideas? I am a docker noob.

**Comment by sammcj** [comment]
Hey sorry just saw this it's midnight here but I'll fork the repo, create a docker hub account and test it out using my own token. Feel free to temporarily revert if it's causing any issues!

**Comment by Finii** [comment]
Ah, I managed to create the arm thing :tada:

image

via commit
  df58a7809 `CI: Entice docker to create arm64 container [skip ci]`

But maybe you can try to patch a font with that. And report which `fontforge` version it has?

**Comment by sammcj** [comment]
ooohhhh I didn't release it needed the platform there as well! Good spotting and thanks!

I'll be testing it out shortly.

**Comment by sammcj** [comment]
Seems to work fine, only error is about iconv encoding - but that won't be ARM build related.

I've run the patched fonts through font book and they validated without issue.

- macOS 13.0
- Apple Macbook Air (m1)

```
1.006; ttfautohintv1.8.3;Nerd Fonts 2.3.0-RC
```

```
docker run -v /Users/samm/Downloads/Atkinson_Hyperlegible:/in -v /Users/samm/Downloads/Atkinson_Hyperlegible-nerd:/out nerdfonts/patcher
Running with options:

Internal Error: Your version of iconv does not support the "Mac Roman" encoding.
If this causes problems, reconfigure --without-iconv.
Copyright (c) 2000-2022. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20220308
 Based on sources from 2022-07-24 20:58 UTC-D.
 Based on source from git with hash: 3714b0323943afc54607f9404b672ca469364cb3
The truetype encoding specified by platform=1 specific=0 (which we map to Mac) is not supported by your version of iconv(3).
Nerd Fonts Patcher v2.3.0-RC (3.2.0) executing

Nerd Fonts: Processing Atkinson Hyperlegible Bold (1/1)
No configfile given, skipping configfile related actions
Adding 177 Glyphs from Seti-UI + Custom Set
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set
╢████████████████████████████████████████╟ 100%

Done with Patch Sets, generating font...

Nerd Fonts: Tweaking 1/1
Changing lowestRecPPEM from 8 to 6

Generated: Atkinson Hyperlegible Bold Nerd Font in '/out/Atkinson Hyperlegible Bold Nerd Font.ttf'
Internal Error: Your version of iconv does not support the "Mac Roman" encoding.
If this causes problems, reconfigure --without-iconv.
Copyright (c) 2000-2022. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20220308
 Based on sources from 2022-07-24 20:58 UTC-D.
 Based on source from git with hash: 3714b0323943afc54607f9404b672ca469364cb3
The truetype encoding specified by platform=1 specific=0 (which we map to Mac) is not supported by your version of iconv(3).
Nerd Fonts Patcher v2.3.0-RC (3.2.0) executing

Nerd Fonts: Processing Atkinson Hyperlegible Bold Italic (1/1)
No configfile given, skipping configfile related actions
Adding 177 Glyphs from Seti-UI + Custom Set
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set
╢████████████████████████████████████████╟ 100%

Done with Patch Sets, generating font...

Nerd Fonts: Tweaking 1/1
Changing lowestRecPPEM from 8 to 6

Generated: Atkinson Hyperlegible Bold Italic Nerd Font in '/out/Atkinson Hyperlegible Bold Italic Nerd Font.ttf'
Internal Error: Your version of iconv does not support the "Mac Roman" encoding.
If this causes problems, reconfigure --without-iconv.
Copyright (c) 2000-2022. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20220308
 Based on sources from 2022-07-24 20:58 UTC-D.
 Based on source from git with hash: 3714b0323943afc54607f9404b672ca469364cb3
The truetype encoding specified by platform=1 specific=0 (which we map to Mac) is not supported by your version of iconv(3).
Nerd Fonts Patcher v2.3.0-RC (3.2.0) executing

Nerd Fonts: Processing Atkinson Hyperlegible Italic (1/1)
No configfile given, skipping configfile related actions
Adding 177 Glyphs from Seti-UI + Custom Set
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set
╢████████████████████████████████████████╟ 100%

Done with Patch Sets, generating font...

Nerd Fonts: Tweaking 1/1
Changing lowestRecPPEM from 8 to 6

Generated: Atkinson Hyperlegible Italic Nerd Font in '/out/Atkinson Hyperlegible Italic Nerd Font.ttf'
Internal Error: Your version of iconv does not support the "Mac Roman" encoding.
If this causes problems, reconfigure --without-iconv.
Copyright (c) 2000-2022. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Version: 20220308
 Based on sources from 2022-07-24 20:58 UTC-D.
 Based on source from git with hash: 3714b0323943afc54607f9404b672ca469364cb3
The truetype encoding specified by platform=1 specific=0 (which we map to Mac) is not supported by your version of iconv(3).
Nerd Fonts Patcher v2.3.0-RC (3.2.0) executing

Nerd Fonts: Processing Atkinson Hyperlegible Regular (1/1)
No configfile given, skipping configfile related actions
Adding 177 Glyphs from Seti-UI + Custom Set
╢████████████████████████████████████████╟ 100%
Adding 198 Glyphs from Devicons Set
╢████████████████████████████████████████╟ 100%

Done with Patch Sets, generating font...

Nerd Fonts: Tweaking 1/1
Changing lowestRecPPEM from 8 to 6

Generated: Atkinson Hyperlegible Regular Nerd Font in '/out/Atkinson Hyperlegible Regular Nerd Font.ttf'
```

**Comment by Finii** [comment]
> Internal Error: Your version of iconv does not support the "Mac Roman" encoding.

Ah, we base the docker on Alpine iirc, and they use musl's `iconv` instead of glibc's. And that indeed has no Mac encoding:

image

The relevant code is here: https://github.com/fontforge/fontforge/blob/8ce3216d492d4a249ffec163c005d098df28e58c/fontforge/encoding.c#L196

**Pull request merged**
