### PR TITLE
No need --cask params anymore

### PR DESCRIPTION
**Pull request by Goooler**
#### Description

No need `--cask` param to install cask via brew.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [ ] Verified the license of any newly added font, glyph, or glyph set

#### How should this be manually tested?

```sh
brew tap homebrew/cask-fonts
brew install font-hack-nerd-font
```

### CODE REVIEW

**Comment by Finii** [comment]
Thanks for the PR!

According to https://github.com/Homebrew/homebrew-cask-fonts#lets-try-it you are right.
Their own documentation does not mention `--cask` for the font install:

image


On the other hand, if you are like me, and try this on your own machine, there is a difference:

```
$ brew tap homebrew/cask-fonts
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
==> Updated Homebrew from 9c88c39ba to 3.6.20 (7e77b89e2).
No changes to formulae.


The 3.6.0 release notes are available on the Homebrew Blog:
  https://brew.sh/blog/3.6.0
The 3.6.20 changelog can be found at:
  https://github.com/Homebrew/brew/releases/tag/3.6.20
==> Tapping homebrew/cask-fonts
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts'...
remote: Enumerating objects: 66096, done.
remote: Counting objects: 100% (161/161), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 66096 (delta 114), reused 137 (delta 97), pack-reused 65935
Receiving objects: 100% (66096/66096), 13.01 MiB | 8.64 MiB/s, done.
Resolving deltas: 100% (48972/48972), done.
Tapped 2007 casks (2,042 files, 16.2MB).
$
```

So far, so good. And now the actual install:

```
$ brew install font-inconsolata
Warning: No available formula with the name "font-inconsolata". Did you mean fonts-encodings?
==> Searching for similarly named formulae...
==> Formulae
fonts-encodings

To install fonts-encodings, run:
  brew install fonts-encodings
$
```

"WAT?!! What does that mean?!?!". Lets add the `--cask`, as suggested in the Nerd Font readmes:

```
$ brew install --cask font-inconsolata
Error: Invalid `--cask` usage: Casks do not work on Linux
$
```


AH!! Right.
That error message makes much more sense.

Is it really better to not say `--cask` but have people come here and complain it fails with unreadable error messages?

**Comment by Goooler** [comment]
Seems no such a error occurs on my device, do you use brew on Linux?

```sh
Last login: Thu Jan 26 19:28:23 on ttys000
 snebula@MBP  ~  brew tap homebrew/cask-fonts
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 5 taps (mdogan/zulu, jandedobbeleer/oh-my-posh, homebrew/core, homebrew/cask and homebrew/services).
==> New Formulae
ancient                  m1ddc                    mdless                   zsh-autopair
==> New Casks
serene

You have 5 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Tapping homebrew/cask-fonts
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-cask-fonts'...
remote: Enumerating objects: 66096, done.
remote: Counting objects: 100% (161/161), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 66096 (delta 114), reused 137 (delta 97), pack-reused 65935
Receiving objects: 100% (66096/66096), 13.01 MiB | 884.00 KiB/s, done.
Resolving deltas: 100% (48972/48972), done.
Tapped 2007 casks (2,042 files, 16.1MB).
 snebula@MBP  ~  brew install font-hack-nerd-font
==> Downloading https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/27
##############################################                            64.1%curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

Error: Download failed on Cask 'font-hack-nerd-font' with message: Download failed: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip
 ✘ snebula@MBP  ~  brew install font-hack-nerd-font
==> Downloading https://github.com/ryanoasis/nerd-fonts/releases/download/v2.3.3/Hack.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/27
######################################################################## 100.0%
==> Installing Cask font-hack-nerd-font
==> Moving Font 'Hack Regular Nerd Font Complete.ttf' to '/Users/snebula/Library/Fonts/Hack Regular
==> Moving Font 'Hack Bold Italic Nerd Font Complete.ttf' to '/Users/snebula/Library/Fonts/Hack Bold
==> Moving Font 'Hack Bold Nerd Font Complete Mono.ttf' to '/Users/snebula/Library/Fonts/Hack Bold N
==> Moving Font 'Hack Bold Nerd Font Complete.ttf' to '/Users/snebula/Library/Fonts/Hack Bold Nerd F
==> Moving Font 'Hack Italic Nerd Font Complete Mono.ttf' to '/Users/snebula/Library/Fonts/Hack Ital
==> Moving Font 'Hack Italic Nerd Font Complete.ttf' to '/Users/snebula/Library/Fonts/Hack Italic Ne
==> Moving Font 'Hack Regular Nerd Font Complete Mono.ttf' to '/Users/snebula/Library/Fonts/Hack Reg
==> Moving Font 'Hack Bold Italic Nerd Font Complete Mono.ttf' to '/Users/snebula/Library/Fonts/Hack
🍺  font-hack-nerd-font was successfully installed!
 snebula@MBP  ~  brew install fonts-encodings
==> Fetching fonts-encodings
==> Downloading https://ghcr.io/v2/homebrew/core/fonts-encodings/manifests/1.0.6
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/homebrew/core/fonts-encodings/blobs/sha256:863542f9892912c4f98cf5
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:863542f9892912c
######################################################################## 100.0%
==> Pouring fonts-encodings--1.0.6.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/fonts-encodings/1.0.6: 56 files, 653KB
==> Running `brew cleanup fonts-encodings`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
 snebula@MBP  ~  brew install font-inconsolata
==> Downloading https://github.com/google/fonts/raw/main/ofl/inconsolata/Inconsolata%5Bwdth%2Cwght%5
==> Downloading from https://raw.githubusercontent.com/google/fonts/main/ofl/inconsolata/Inconsolata
######################################################################## 100.0%
Warning: No checksum defined for cask 'font-inconsolata', skipping verification.
==> Installing Cask font-inconsolata
==> Moving Font 'Inconsolata[wdth,wght].ttf' to '/Users/snebula/Library/Fonts/Inconsolata[wdth,wght]
🍺  font-inconsolata was successfully installed!
 snebula@MBP  ~ 
```

**Comment by Finii** [comment]
> Seems no such a error occurs on my device, do you use brew on Linux?

Shure ;-) That's the point. You can leave the `--cask` off, until you cant ;-)

**Comment by Goooler** [comment]
I'm trying to repro, this might be a bug of brew.

**Comment by Finii** [comment]
You think the casks should work on Linux?

**Comment by Goooler** [comment]
We should not use `--cask` on Linux, see https://github.com/Homebrew/discussions/discussions/3999.

**Comment by Finii** [comment]
Yes. So they do not work for me.
But if I follow instructions (without `--cask`) I get no meaningful error message.
With `--cask` I at least know the reason.

**Comment by Goooler** [comment]
Filed it at https://github.com/Homebrew/homebrew-cask-fonts/issues/7040.

**Comment by Finii** [comment]
Rebase on master, force push

**Comment by Finii** [comment]
As 'they' themselves suggest installing without `--cask` we should follow that.

Thanks for the PR!

@all-contributors Do you want to add @Goooler for doc?

**Pull request merged**
