### PR TITLE
archive-fonts: Create tar.xz packs

### PR DESCRIPTION
**Pull request by Finii**
See #1233

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What are the relevant tickets (if any)?

Fixes: #1233

### CODE REVIEW

**Comment by Finii** [comment]
This started as a test but the feedback was overwhelmingly good and ppl seem to expect that this stays :grimacing:

**Comment by Finii** [comment]
@allcontributors please add N-R-K for ideas

**Comment by N-R-K** [comment]
> Could not find the user `N-R#/#K` on github.

image

**Comment by Finii** [comment]
Am I blind? Why is the link on your avatar working but clicking on your name on the contributors page is not?!?

image

image

**Comment by N-R-K** [comment]
image

Missing the colon :thinking:

**Comment by Finii** [comment]
image

colons ... :grimacing:

**Comment by Finii** [comment]
> > Could not find the user `N-R#/#K` on github.
> 
> image

Related:
* #1192 

:grimacing:

**Pull request merged**
