### PR TITLE
Draft: Add font: Envy Code R

### PR DESCRIPTION
**Pull request by Finii**
#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

**RFN clause, renaming still tbd**

#### What does this Pull Request (PR) do?

Add new font Envy Code R

#### What are the relevant tickets (if any)?

#1205

### CODE REVIEW

**Comment by Finii** [comment]
Sorry this took so long, and we still have no new-release-scheme (which is what kept me from adding new fonts).

Anyhow, there is one question to @damieng:
The license has an RFN clause. That means that we can not name the patched font "EnvyCodeR Nerd Font" (which would be the 'normal' patched name) - except you give us an exception to the license (like for example Mononoki).

Maybe you have a good patched font name, usually with RFN we try to come up with a somehow similar name.
Or you allow reusing the name parts just here for the Nerd Font patching.

Either is ok of course. And also if you prefer to not suggest anything we will come up with a 'new' name.

Thank you again for the font, the responses, the patience :-)

**Comment by damieng** [comment]
I give my permission for it to be called "Envy Code R Nerd Font"

**Comment by Finii** [comment]
I sneaked it in as 'Release v3.0.2'; noticed that we have no real way to add fonts, as half the commits are automated but they would have to wait till the next release etc... For the other pending font additions I have to think about a solution.

Anyhow, Envy Code R now fully published:

image

**Comment by Finii** [comment]
Note to self:

Additional commits needed, full commit list:

9512cddd4 `Add font: Envy Code R`
57f17e23b `Add font: Envy Code R (fix)`
ad8ee0ce2 `Add Envy Code R patched`

And for the pages:

763c03cb1 `[ci] Sync fonts.json`
3f232dbec `Add Envy Code R preview`

**Comment by Finii** [comment]
Publish on Homebrew finished: https://github.com/Homebrew/homebrew-cask-fonts/pull/7915

I do not contribute to other packagers.

**Pull request merged**
