### PR TITLE
Release master fontpatcher

### PR DESCRIPTION
**Pull request by b-**
#### Description

Fixes https://github.com/ryanoasis/nerd-fonts/issues/1040

@all-contributors please add @b- for infra

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [ ] Verified the license of any newly added font, glyph, or glyph set _(N/A)_

#### What does this Pull Request (PR) do?

 - Adds a Github Actions workflow to release _just_ an updated fontpatcher.zip from master

### CODE REVIEW

**Comment by b-** [comment]
I think something is wrong with the github actions thing I'm using to perform the release, but I know I've got the tag wrong anyway. Could I ask someone else to please fix that step in the workflow for me and then mark it as ready?

**Comment by Finii** [comment]
But you do know that multiple people get an email for each commit you push, like ... every 10 minutes?

I close this now here, please reopen when PR is ready.

**Comment by Finii** [comment]
grafik

**Comment by b-** [comment]
> But you do know that multiple people get an email for each commit you push, like ... every 10 minutes?
> 
> I close this now here, please reopen when PR is ready.

Oh no, I didn't realize this at all! Thanks for letting me know, I'm sure I've caused others this headache too... 🤢

**Comment by b-** [comment]
Anyway, at this point I _think_ I actually am done except that I do not know why it's not committing to my repository. It gets a 403 when I think I'm using the add-and-commit action the same way it's used in packsvgs, which confuses me.

Could I ask you (or another maintainer) take a look at it and see if you can see what's wrong, and if there's anything else I need to change for it to be okay to merge, please?

**Comment by Finii** [comment]
image

In your repo you need to grant rw access to workflow runs.

Maybe it's here:

image

**Comment by b-** [comment]
Thank you! That was it. I've now got a FontPatcher.zip in my relevant branch, committed and pushed by ~~my minions~~ _GitHub Actions_.

I'm gonna reread what you mentioned before about the scope, because I probably could improve that a bit. As it stands, it's `on: push:` but I added a path filter roughly equivalent to the sparse worktree I'm using in my checkout (i.e., on update of `font-patcher` or its glyphs or dependencies).

Once I'm more confident it's all kosher I'll reopen the pull request (or open a new one, I'm not 100% certain if I can reopen one).

**Comment by Finii** [comment]
>. As it stands, it's `on: push:` but I added

Well, that is on `push` to any branch, i.e. also for PR branches. That is in principle possible, messes with the PRs what, I guess, will confuse a lot of contributors (at least when I assume they are as versed as my colleagues at work :grimacing:)

You could limit it to 'push to master' (which is executed by explicit pushes to master as well as merging/ff-ing PRs to master).

**Pull request closed without merging**
