### PR TITLE
Add Martian Mono

### PR DESCRIPTION
**Pull request by skryukov**
#### Description

This PR adds [Martian Mono](https://github.com/evilmartians/mono) font.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### Any background context you can provide?

As far as I understand, contributing guide is a bit outdated, I'm not quite sure that I made all the changes required:

- added all license/readme files
- added all the fonts
- added font metadata to the `bin/scripts/lib/fonts.json`
- additionally provided a small sh script to update font on upcoming releases

#### What are the relevant tickets (if any)?

https://github.com/ryanoasis/nerd-fonts/issues/937

### CODE REVIEW

**Comment by Finii** [comment]
This looks good, thanks for the PR!

Missing is just the change in `README.md` where all fonts are listed.
And I believe it should have `--makegroup` in the `config.cfg`, but that will be thrown on all fonts with `v3.0.0` anyhow, so no worries.

What I ask myself, is it really necessary to include all width and weights? Given the source is a VF people might 'miss' any number of intermediate values on all axis :grimacing: And the package size is considerable. Are these all relevant for coding? What is the goal of patching them all?

**Comment by Finii** [comment]
Hmm, noted that they put the very abbreviated names everywhere, ID16/17 could benefit from expanded names :thinking: 

image

How should non-font-geeks decode these?

See also http://glyphsapp.com/learn/naming

Maybe raise an issue over there? What do you think?

**Comment by skryukov** [comment]
> What I ask myself, is it really necessary to include all width and weights? Given the source is a VF people might 'miss' any number of intermediate values on all axis 😬 And the package size is considerable. Are these all relevant for coding? What is the goal of patching them all?

Sure, let's get a subset! Any suggestions from your experience? I personally use only `Std Rg` for terminal 😅

**Comment by romashamin** [comment]
Regarding to the naming system.

This naming convention has its own benefits. That was well-considred decision, made with Glyphs app “Naming” tutorial in mind.

**Comment by hirenchauhan2** [comment]
Any plans to merge this one?

**Comment by Finii** [comment]
Well, it does not have a 3.0.0 milestone tag.

I would rather push out 3.0.0 asap and add other stuff only afterwards.
A lot of documentary changes are missing in the PR, which is no problem, but still need to be done.
And then, this is again a font with a whole lot of styles and weights; _SemiWide_, ... _Narrow_, is that really of a general interest. And the big weights set. Nowadays people create fonts a two axis variable font and create instances for a 5*5 matrix of the axises ... It's too easy ;-)

So I guess someone needs to sit down and think, and I personally would rather spend the time on getting 3.0.0 out, finally.

**Comment by Finii** [comment]
Rebase on master, force push.

Also added some more commits, for example to improve the naming and dropped quite some fontfaces.

**Comment by Finii** [comment]
@allcontributors please add @skryukov for code

**Comment by Finii** [comment]
@allcontributors please add @skryukov for code

**Pull request merged**
