### PR TITLE
Fixed some fonts names

### PR DESCRIPTION
**Pull request by samuelramox**
#### Description

_Please explain the changes you made here._

#### Requirements / Checklist

- [ x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [ x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x ] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [ ] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [ ] Extended the README and documentation if necessary, e.g. You added a new font please update the table

#### What does this Pull Request (PR) do?
Fixed some fonts names in Patched Fonts section in readme.md.

#### How should this be manually tested?
Check the Fira, Hasklig, Hack, Share and Terminus fonts names in Patched Fonts section.

#### Any background context you can provide?
It is not necessary

#### What are the relevant tickets (if any)?
It is not necessary

#### Screenshots (if appropriate or helpful)
It is not necessary

### CODE REVIEW

**Comment by ryanoasis** [comment]
@samuelramox Thanks for this and we appreciate it, however these names are quite intentionally due to licensing of those particular fonts.

For more information see: [Why do some of the fonts names appear incorrect or appear to have typos?](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting#why-do-some-of-the-fonts-names-appear-incorrect-or-appear-to-have-typos)

Either way I will suggest a change you can make where we would accept your Pull Request 😄

**Comment by samuelramox** [comment]
Thanks for explaining. I noticed that the installed fonts were with the wrong names too and I was already thinking of working on that fix as well.
Thank you!

**Comment by ryanoasis** [comment]
Sure no problem this wasn't the first time there has been confusion and it won't be the last.

If you make the change I suggested for those fonts in the table we can merge this 😄

**Comment by samuelramox** [comment]
Thanks for your patience. I made the requested changes.
If you need help with something, test fonts and etc, please let me know.

**Comment by ryanoasis** [comment]
@samuelramox Thanks

**Comment by samuelramox** [comment]
I thank you!

**Pull request merged**
