### PR TITLE
Add TOML icon

### PR DESCRIPTION
**Pull request by cpea2506**
#### Description

The logo is taken from the official repo of [TOML](https://github.com/toml-lang/toml/blob/main/logos/toml.svg).

There is a little change that made the SVG change to black/white color and better optimized.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What does this Pull Request (PR) do?

Add new icon for TOML

#### Screenshots (if appropriate or helpful)

Screenshot 2023-11-22 at 23 12 49

### CODE REVIEW

**Comment by Finii** [comment]
Thanks for the nice PR!

Just curiosity, what is your use-case? Yes, to mark your TOML files, I mean what do you use TOML for?
I had the impression everybody is using json these days, even if the readability is less.

**Comment by cpea2506** [comment]
> Thanks for the nice PR!
> 
> Just curiosity, what is your use-case? Yes, to mark your TOML files, I mean what do you use TOML for? I had the impression everybody is using json these days, even if the readability is less.

Hi, it just as a Rust user we have a lot of `TOML` files. Since everyone prefer to mark them with the setting icon, I just want us to respect the correct icon for the file

**Comment by Finii** [comment]
Sneaking this in, thanks again

**Comment by Finii** [comment]
@allcontributors please add @cpea2506 for code

**Comment by jcypret** [comment]
Excited to see this TOML addition! ❤️ 

FYI: It looks like the [Glyph Sets and Code Points](https://github.com/ryanoasis/nerd-fonts/wiki/Glyph-Sets-and-Code-Points#seti-ui--custom) Wiki entry is missing this additional codepoint:


```diff
- Code Point Ranges: e5fa-e6b1
+ Code Point Ranges: e5fa-e6b2
```

I noticed when using that wiki as a reference for my Kitty config based on this other discussion: https://github.com/ryanoasis/nerd-fonts/issues/1189.

**Pull request merged**
