### PR TITLE
Update JetBrainsMono to 1.0.3

### PR DESCRIPTION
**Pull request by alindeman**
#### Description

JetBrainsMono [1.0.3](https://github.com/JetBrains/JetBrainsMono/releases/tag/v1.0.3) was released recently.

The `font-patcher` and `gotta-patch-em-all-font-patcher!.sh` run without error for me, but they also generated a lot of churn in the generated READMEs and also generated fonts with slightly different names than were already there. I can't tell if this is an issue on my end or not. Feedback from someone else who has run those before would be helpful.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Read or at least glanced at the [FAQ](https://github.com/ryanoasis/nerd-fonts/wiki/FAQ-and-Troubleshooting)
- [x] Read or at least glanced at the [Wiki](https://github.com/ryanoasis/nerd-fonts/wiki)
- [x] Scripts execute without error (if necessary):
  - If any of the scripts were modified they have been tested and execute without error, e.g.:
    - `./font-patcher Inconsolata.otf --fontawesome --octicons --pomicons`
    - `./gotta-patch-em-all-font-patcher\!.sh Hermit`
- [x] Extended the README and documentation if necessary, e.g. You added a new font please update the table

### CODE REVIEW

**Comment by ryanoasis** [comment]
I think this is a good step, looks good. Thanks!

>  a lot of churn in the generated READMEs and also generated fonts with slightly different names

I've seen it before, I'll need to look into

**Comment by damnskippy** [comment]
@alindeman shot in the dark, any chance you could update your fork to 1.5 until @ryanoasis  can get to this on master?  Seems like this is one font that is actively developed and it would be nice to keep the patched version up as well.  Thanks.

**Comment by alindeman** [comment]
> @alindeman shot in the dark, any chance you could update your fork to 1.5 until @ryanoasis can get to this on master? Seems like this is one font that is actively developed and it would be nice to keep the patched version up as well. Thanks.

Sure. I've opened #459

**Comment by damnskippy** [comment]
@alindeman thanks so much!

**Comment by damnskippy** [comment]
@alindeman sorry, but for some reason using the patched version, the box drawing symbols (tmux pane separators etc) don't seem to be getting rendered properly.  I don't see the issue in the original unpatched version (1.0.5).  Just thought I'd mention.

**Pull request merged**
