### PR TITLE
Add Ubuntu Sans

### PR DESCRIPTION
**Pull request by Finii**
Prevent the "SansMono" becomes "SansM" rule for UbuntuSansMono.

Fixes: #1435

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/-/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

### CODE REVIEW

**Comment by olivercalder** [comment]
Does this entail that Ubuntu Sans Mono will be available as part of the Ubuntu Sans nerd font?

**Comment by Finii** [comment]
I thought it would be ok to have one release archive with `UbuntuSans` and `UbuntuSansMono` together. Is that not good?

**Comment by Finii** [comment]
We can still change that, I just realized I need to create a new Font-Logos release first to pull that into Nerd Font :grimacing:

**Comment by olivercalder** [comment]
That's great, I just wanted to make sure that it was the case that mono would be included as well (I'm not very familiar with font packaging). Thanks!

**Pull request merged**
