### PR TITLE
Add Kotlin icon

### PR DESCRIPTION
**Pull request by Finii**
#### Description

Add Kotlin icon to Seti & Custom glyph source font.

#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What does this Pull Request (PR) do?

Add a hand drawn Kotlin icon to the `original-source` font.

#### What are the relevant tickets (if any)?

Feature request #861 

#### Screenshots (if appropriate or helpful)

image

### CODE REVIEW

**Comment by Finii** [comment]
This clashes with #833 - codepoints 'overlap'

And I wonder still ... is there no automaton for `original-source.otf`? :-/

**Comment by danielcherubini** [comment]
Is there anything that needs help on this? It would be great to get this icon in there

**Comment by Finii** [comment]
Still busy with Release 2.2.x aftermath.
Lets wait a bit before working on new additions.

**Comment by Finii** [comment]
Rebase on master - needed to shift codepoint of new glyph - force push

**Pull request merged**
