### PR TITLE
List AUR packages for Jetbrains & Victor Mono

### PR DESCRIPTION
**Pull request by avalonv**
#### Description
Added two fonts to the AUR section of the README

These are currently the 3rd and 4th most popular Nerd Fonts packages in the AUR respectively, and I felt they should be included.
#### Requirements / Checklist

- [x] Read the [Contributing Guidelines](https://github.com/ryanoasis/nerd-fonts/blob/master/contributing.md)
- [x] Verified the license of any newly added font, glyph, or glyph set

#### What does this Pull Request (PR) do?
See description.

#### Screenshots (if appropriate or helpful)
image

### CODE REVIEW

**Comment by Finii** [comment]
Excellent, thank you!

Wouldn't it make sense to list the packages in popularity or at least alphabetical order? \*ponder\*

**Comment by avalonv** [comment]
Up to you really, I could reorder them if you'd like.

I think alphabetical order makes more sense since popularity fluctuates with time.

**Comment by avalonv** [comment]
@Finii would you like me to do that and open a new PR?

**Comment by Finii** [comment]
Well, I just added a commit with the reordering.

And I learned about `nerd-fonts-git` which is nice.

Thanks again for the PR and that you care :-)

**Comment by Finii** [comment]
Hmm, somehow your commit vanished?!?
I hate merge commits, but somehow github said it was needed and no FF could be performed (on the command line it was no problem, though)

image

Sorry :-(

**Comment by Finii** [comment]
Hmm, you commit IS in the repo, but just not shown by the github web frontend?

This is the repo on current `master` in `tig`
image

**Pull request merged**
