### PR TITLE
Improve bazel icon

### PR DESCRIPTION
**Pull request by zaucy**
#### Description

Improved bazel icon. The old icon didn't have the separation lines which makes it look bad when used in applications such as neovim or other TUI applications.

#### Any background context you can provide?

Bazel icon was modified by myself

#### Screenshots (if appropriate or helpful)

| old | new |
| --- | --- |
| image | TODO  |

### CODE REVIEW

**Comment by Finii** [comment]
Thanks for the improvement!

codepoint `e63a` aka `nf-seti-bazel`

**Comment by Finii** [comment]
image

Turns out good, just one nitpick, the gap seems to be non-constant in width? A bit narrower at A than at B?

image

**Comment by Finii** [comment]
I wonder if these two have the same 'problem'?

image

_Kotlin and Rubi_

image

image
_But then, 'rubi' is a bad search term_

**Comment by Finii** [comment]
And firebase?

image


And we have some alternative kotlin icon in the repo, which would turn out the same because fonts just have color or transparent, so one needs to crate the gaps.

image

---

As usual, each bug is a rabbit hole.

**Comment by zaucy** [comment]
> Turns out good, just one nitpick, the gap seems to be non-constant in width? A bit narrower at A than at B?

That's fair! It was eyeballed. I could clean it up a bit.

> I wonder if these two have the same 'problem'?

Yeah I think a few icons could benefit from some transparent gaps. They show up so much better that way IMO.

**Comment by Finii** [comment]
Codepoint `E552`, related:

* https://github.com/ryanoasis/nerd-fonts/issues/1321#issuecomment-1764174337

Also remember having seen `E511` with eyes :thinking:

**Comment by Finii** [comment]
### Kotlin

The striped logo is obsolete, with the one rouchgly K shaped block we have already the latest and correct one.
See assets in https://kotlinlang.org/docs/kotlin-brand-assets.html

### Firebase

They have a monochrome icon, see https://firebase.google.com/brand-guidelines/
Will change.

### Ruby

Does not have a canonical monochrome icon, https://www.ruby-lang.org/en/about/logo/

### Bazel

There is no monochrome icon, but from the design ideas presented here https://blog.bazel.build/2017/07/05/new-logo-and-homepage.html it seems that the proposed change by zaucy is 'correct', at least if one does not want just the outside lines of the cubes.

image

**Comment by Finii** [comment]
Ruby monochrome ...

image

The left one would be my favorite, but the angles are all wrong :unamused: 
The one in the middle looks too coarse for my eyes. Hmm.

image

This looks nice ;-)

**Comment by Finii** [comment]
image

**Comment by Finii** [comment]
@allcontributors please add @zaucy for code

**Pull request merged**
